// Loading quiz belongs to the vocabulary library, independently of profile UI.
(function(){
'use strict';
window.injectLoadQuizSettings=function(){};window.updateLoadQuizBookSelect=function(){};
const pin=()=>{const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-label','ロードクイズ出題対象');svg.classList.add('loading-quiz-pin');svg.innerHTML='<path d="m16 3 5 5-4 1-3 6-5-5 6-3zM9 15l-6 6" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/>';return svg;};
function matches(num,bookId,q=window.UserProfile.read().loadingQuiz){return !!q&&q.bookId===bookId&&Number(num)>=q.from&&Number(num)<=q.to;}
window.filterLoadingQuizWords=function(words,bookId){if(window.LibraryState.isDeleted('book',bookId))return [];const q=window.UserProfile.read().loadingQuiz;return q&&q.bookId===bookId?words.filter(word=>matches(word.num,bookId,q)):words;};
const oldQuizInit=window.__initLoadQuiz;window.__initLoadQuiz=function(){const q=window.UserProfile.read().loadingQuiz;if(q)localStorage.setItem('core_v4_loadquiz_book',q.bookId);return oldQuizInit.apply(this,arguments);};
function pins(){document.querySelectorAll('.loading-quiz-pin').forEach(el=>el.remove());const q=window.UserProfile.read().loadingQuiz;if(!q)return;document.querySelectorAll('.textbook-list-item[data-book-id]').forEach(row=>{if(row.dataset.bookId===q.bookId)row.querySelector('.textbook-list-name')?.append(pin());});document.querySelectorAll('.word-row-container[data-word-num]').forEach(row=>{if(matches(row.dataset.wordNum,currentTextbook,q))row.prepend(pin());});}
window.openLoadingQuizSettings=async function(bookId){const account=myId||'GUEST-000',book=textbooksPool.find(book=>book.id===bookId);if(!book)return;const modal=window.openLibraryDialog('ロード画面のクイズ','<p class="library-editor-hint"></p><label><input type="checkbox" id="quizUseBook">この単語帳から出題する</label><div class="quiz-range"><label>開始番号<input type="number" min="1" id="quizFrom" value="1"></label><label>終了番号<input type="number" min="1" id="quizTo"></label></div><p class="library-editor-error" role="alert"></p><div class="library-editor-actions"><button type="button" data-library-close>閉じる</button><button type="button" id="quizSave">設定を保存</button></div>');modal.querySelector('.library-editor-hint').textContent=book.name;const q=window.UserProfile.read().loadingQuiz,check=modal.querySelector('#quizUseBook');check.checked=!!q&&q.bookId===bookId;modal.querySelector('#quizTo').value=q&&q.bookId===bookId?q.to:1;try{const words=await window.__getBookMasterWords(bookId);if((myId||'GUEST-000')!==account||!modal.isConnected)return;modal.querySelector('#quizTo').value=q&&q.bookId===bookId?q.to:words.reduce((max,word)=>Math.max(max,Number(word.num)||1),1);modal.querySelector('#quizFrom').value=q&&q.bookId===bookId?q.from:1;}catch(error){modal.querySelector('.library-editor-error').textContent='単語帳の読み込みに失敗しました。';}
 modal.querySelector('#quizSave').onclick=()=>{if((myId||'GUEST-000')!==account)return;const from=Number(modal.querySelector('#quizFrom').value),to=Number(modal.querySelector('#quizTo').value);if(!Number.isInteger(from)||!Number.isInteger(to)||from<1||to<from){modal.querySelector('.library-editor-error').textContent='出題番号の範囲を確認してください。';return;}const data=window.UserProfile.read();data.loadingQuiz=check.checked?{bookId,from,to}:null;data.updatedAt=Math.max(Date.now(),Number(data.updatedAt||0)+1);window.UserProfile.store(data);localStorage.setItem('core_v4_loadquiz_book',check.checked?bookId:'auto');pins();window.UserProfile.sync();window.closeLibraryDialog();};};
const actions=window.openLibraryBookActions;window.openLibraryBookActions=function(bookId){actions.apply(this,arguments);const modal=document.querySelector('dialog.library-editor-dialog');if(!modal)return;const button=document.createElement('button');button.type='button';button.textContent='ロード画面クイズの設定';button.onclick=()=>window.openLoadingQuizSettings(bookId);modal.querySelector('.library-editor-actions')?.prepend(button);};
['renderVocabLibrarySelection','renderVocabList'].forEach(name=>{const original=window[name];if(typeof original==='function')window[name]=function(){const result=original.apply(this,arguments);pins();return result;};});
window.onAppLoaded(pins);window.onTabChange(tab=>{if(tab==='vocab')pins();});window.addEventListener('storage',pins);
})();
