(function(){
    const WEEK=7*86400000;
    function timestamp(value){if(value&&typeof value.toMillis==='function')return value.toMillis();if(value&&typeof value.seconds==='number')return value.seconds*1000;return typeof value==='number'?value:Date.parse(value||'')||0;}
    function active(doc,now){const stats=window.StudyTimeModel.readStats(doc),time=timestamp(doc.lastActiveAt||stats.lastLoginAt||doc.lastLoginAt||doc.updatedAt);return time>0&&time<=now&&now-time<=WEEK;}
    window.PeopleModel={timestamp,active};
    let owner='',users=[],loadedAt=0,pending=null;
    const uid=()=>myId||'GUEST-000';
    function title(text){const heading=document.createElement('h3');heading.className='people-section-heading';heading.textContent=text;return heading;}
    function detail(person){const doc=person.doc||{},stats=window.StudyTimeModel.readStats(doc),time=timestamp(doc.lastActiveAt||stats.lastLoginAt||doc.updatedAt||person.timestamp);const dialog=window.openLibraryDialog('プロフィール','<div class="people-detail-person"></div><dl class="people-detail-data"></dl><div class="library-editor-actions"><button type="button" data-library-close>閉じる</button></div>');dialog.querySelector('.library-editor-eyebrow').textContent='PEOPLE';const header=dialog.querySelector('.people-detail-person'),name=document.createElement('h3');window.RankingVisuals.name(name,person.name);header.append(window.RankingVisuals.avatar(person.avatar,person.name),name);const ranking=window.LearningRankingModel.merge(stats.learning_ranking_v2_json,doc.learningRankingV2Json);[['ID',person.id],['目標',doc.userTarget||doc.target||'未設定'],['最終アクティブ',time?new Date(time).toLocaleString('ja-JP'):'記録なし'],['合計勉強時間',Math.floor(window.StudyTimeModel.rankingSeconds(stats,'total',Date.now())/60)+'分'],['理解度の記録',window.LearningRankingModel.wordCount(ranking)+'語'],['フラッシュ',window.LearningRankingModel.flashCount(ranking)+'回']].forEach(([label,value])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;dialog.querySelector('dl').append(dt,dd);});}
    function row(person,friend){const wrapper=document.createElement('div');wrapper.className='people-row';const button=document.createElement('button');button.type='button';button.className='people-profile-button';button.setAttribute('aria-label',person.name+'のプロフィール');const name=document.createElement('span');name.className='people-name';window.RankingVisuals.name(name,person.name);const code=document.createElement('small');code.textContent=person.id;const text=document.createElement('span');text.append(name,code);button.append(window.RankingVisuals.avatar(person.avatar,person.name),text);button.onclick=()=>detail(person);wrapper.append(button);if(friend){const remove=document.createElement('button');remove.type='button';remove.className='people-remove';remove.textContent='解除';remove.setAttribute('aria-label',person.name+'をフレンドから解除');remove.onclick=event=>window.removeFriendDirect(person.id,event);wrapper.append(remove);}return wrapper;}
    function render(){const host=document.getElementById('friendListContainer');if(!host)return;const lookup=new Map(users.map(person=>[person.id,person])),friends=(myFriendList||[]).map(friend=>lookup.get(friend.code)||{id:friend.code,name:friend.name||friend.code,avatar:friend.customAvatar||'',timestamp:friend.timestamp});host.replaceChildren();host.append(title('フレンド'));if(!friends.length){const hint=document.createElement('p');hint.className='people-hint';hint.textContent='IDコードからフレンドを追加できます。';host.append(hint);}friends.forEach(person=>host.append(row(person,true)));host.append(title('最近1週間のアクティブユーザー'));const ids=new Set(friends.map(person=>person.id));const recent=users.filter(person=>!ids.has(person.id)&&active(person.doc,Date.now())).sort((a,b)=>timestamp(b.doc.lastActiveAt||window.StudyTimeModel.readStats(b.doc).lastLoginAt||b.doc.updatedAt)-timestamp(a.doc.lastActiveAt||window.StudyTimeModel.readStats(a.doc).lastLoginAt||a.doc.updatedAt));recent.forEach(person=>host.append(row(person,false)));if(!recent.length){const hint=document.createElement('p');hint.className='people-hint';hint.textContent=loadedAt?'対象のユーザーはいません。':'接続後にユーザーを取得します。';host.append(hint);}}
    async function refresh(force){if(owner!==uid()){owner=uid();users=[];loadedAt=0;}if(!force&&Date.now()-loadedAt<60000){render();return;}if(pending)return pending;const account=owner;pending=(async()=>{try{if(!window.db||!window.fbGetDocs)return;const docs=await window.fbGetDocs(window.fbCollection(window.db,'users')),list=[];docs.forEach(doc=>{const data=doc.data();if(!data.deleted&&doc.id!=='GUEST-000')list.push({id:doc.id,name:data.playerName||data.userName||data.name||doc.id,avatar:data.avatar||'',doc:data});});if(uid()===account){users=list;loadedAt=Date.now();render();}}catch(error){console.warn('ユーザー一覧の取得は次回に再試行します',error);}finally{pending=null;}})();return pending;}
    window.sortAndRenderFriendList=render;
    window.People={render,refresh};
    window.onTabChange(tab=>{if(tab==='community'){render();refresh(false);}});
    let heartbeatOwner='',heartbeatAt=0;
    async function heartbeat(){const account=uid(),gate=document.getElementById('auth-gate-screen');if(account==='GUEST-000'||!account||document.visibilityState!=='visible'||gate&&getComputedStyle(gate).display!=='none'||!window.db||!window.fbSetDoc)return;if(heartbeatOwner===account&&Date.now()-heartbeatAt<300000)return;try{await window.fbSetDoc(window.fbDoc(window.db,'users',account),{lastActiveAt:new Date().toISOString()},{merge:true});if(uid()===account){heartbeatOwner=account;heartbeatAt=Date.now();}}catch(error){console.warn('アクティブ日時は次回に同期します',error);}}
    window.onAppLoaded(()=>{render();heartbeat();});setInterval(heartbeat,300000);

    const oldRefresh=window.refreshFriendListFromFirebase;if(typeof oldRefresh==='function')window.refreshFriendListFromFirebase=async function(force){await oldRefresh.apply(this,arguments);return refresh(!!force);};
})();
