// Listen only to the current room. No global room scans or matchmaking polling.
(function(){
'use strict';
const m=window.WordDuelModel,uid=()=>myId||'GUEST-000';
const ratings=new Map();
let dialog=null,session=null,unsubscribe=null,timer=null,waitingTimer=null,sending=null,revision=0,published=-1,finishing=false;
const rateKey=()=> 'core_v4_word_duel_rating_'+uid();
function localRating(){if(ratings.has(uid()))return ratings.get(uid());try{return m.rating(Number(localStorage.getItem(rateKey())||1500));}catch{return 1500;}}
function mergeRating(doc){if(Number.isFinite(doc?.wordDuelRating)){const value=m.rating(doc.wordDuelRating);ratings.set(uid(),value);try{if(localStorage.getItem(rateKey())!==String(value))localStorage.setItem(rateKey(),String(value));}catch(error){console.warn('対戦レートはクラウドの確定値を表示します',error);}}renderRating();}
function renderRating(){const el=document.getElementById('headerDuelRating');if(el)el.textContent='R '+localRating();}
function ms(value){return value?.toMillis?value.toMillis():typeof value==='number'?value:0;}
function ref(code){return window.fbDoc(window.db,'wordDuelRooms',code);}
function connected(){if(uid()==='GUEST-000')throw Error('対戦はログインしたアカウントで参加できます。一人プレイはゲストでも使えます。');if(!window.db||!window.fbRunTransaction||!window.fbOnSnapshot)throw Error('対戦にはクラウドへの接続が必要です。');if(window.FirestoreReadGuard?.paused())throw Error('クラウドの利用上限に達しています。今は一人プレイを利用してください。');}
function status(text){const node=dialog?.querySelector('.duel-status');if(node)node.textContent=text;}
function stop(){unsubscribe?.();unsubscribe=null;clearInterval(timer);clearTimeout(waitingTimer);timer=null;waitingTimer=null;}
function cleanup(){stop();session=null;dialog=null;finishing=false;}
function view(title,html){const el=window.openLibraryDialog(title,'<div class="duel-content">'+html+'<p class="duel-status" role="status"></p></div>');el.classList.add('word-duel-dialog');dialog=el;el.addEventListener('close',()=>{if(dialog!==el)return;if(session&&!session.solo&&!session.finished){const old=session;old.answers=old.answers.slice();publish(old,true,true).catch(()=>{});}cleanup();});return el;}
function selection(){const books=typeof textbooksPool==='undefined'?[]:textbooksPool;const select=dialog.querySelector('select');for(const book of books){if(window.LibraryState?.isDeleted('book',book.id))continue;const option=document.createElement('option');option.value=book.id;option.textContent=book.name||book.title||book.id;select.append(option);}if(typeof currentTextbook==='string')select.value=currentTextbook;}
async function words(){const id=dialog.querySelector('select').value||currentTextbook;let source=window.VocabMaster.resolve(id)?.master;if(!source&&window.db){const snap=await window.fbGetDoc(window.fbDoc(window.db,'shared','vocab_'+id));source=snap.exists()?snap.data().custom_words:null;}const result=m.pool(source||[]);if(result.length<10)throw Error('異なる意味を持つ単語が10個以上の単語帳を選んでください。');return result;}
function player(){return {name:String(myName||uid()).slice(0,40),answers:[],done:false,abandoned:false};}
function locked(fn){return async event=>{const button=event.currentTarget;button.disabled=true;status('準備しています…');try{await fn();}catch(error){status(error.message||'接続を確認して再試行してください。');}finally{if(button.isConnected)button.disabled=false;}};}
window.openWordDuel=function(){
 if(dialog?.open)return;view('単語対戦','<p class="duel-intro">60秒。10択。コンボで得点アップ。</p><label class="duel-book-label">出題する単語帳<select aria-label="対戦の単語帳"></select></label><div class="duel-lobby-actions"><button type="button" data-duel-solo>一人プレイ</button><button type="button" data-duel-create>部屋を作る</button></div><div class="duel-join"><input aria-label="部屋番号" inputmode="numeric" maxlength="6" placeholder="6桁の部屋番号"><button type="button" data-duel-join>参加</button></div><p class="duel-rules">正解 +100。連続正解ごとに +10%。ミス −50、コンボ解除。対戦レートは1500から。</p><button type="button" data-library-close>閉じる</button>');selection();
 dialog.querySelector('[data-duel-solo]').onclick=locked(async()=>{const pool=await words();session={solo:true,id:uid(),pool,seed:crypto.getRandomValues(new Uint32Array(1))[0],start:Date.now(),answers:[],finished:false};play();});
 dialog.querySelector('[data-duel-create]').onclick=locked(async()=>{connected();const pool=await words(),account=uid();let code;for(let attempt=0;attempt<5;attempt++){code=String(100000+crypto.getRandomValues(new Uint32Array(1))[0]%900000);const made=await window.fbRunTransaction(window.db,async tx=>{const roomRef=ref(code),snap=await tx.get(roomRef);if(snap.exists())return false;tx.set(roomRef,{version:1,host:account,guest:'',status:'waiting',createdAt:window.fbServerTimestamp(),pool,seed:crypto.getRandomValues(new Uint32Array(1))[0],players:{[account]:player()}});return true;});if(made)break;code=null;}if(!code)throw Error('部屋番号を作れませんでした。再試行してください。');session={id:account,code,answers:[],finished:false};wait(code);});
 dialog.querySelector('[data-duel-join]').onclick=locked(async()=>{connected();const code=dialog.querySelector('input').value.trim(),account=uid();if(!/^\d{6}$/.test(code))throw Error('6桁の部屋番号を入力してください。');await window.fbRunTransaction(window.db,async tx=>{const snap=await tx.get(ref(code));if(!snap.exists())throw Error('部屋が見つかりません。');const room=snap.data();if(!m.validRoom(room))throw Error('部屋のデータを確認できません。');if(room.status!=='waiting'||room.guest||room.host===account)throw Error('この部屋には参加できません。');if(Date.now()-ms(room.createdAt)>120000)throw Error('この部屋の待機時間は終了しました。');tx.set(ref(code),{guest:account,status:'playing',startsAt:window.fbServerTimestamp(),players:{...room.players,[account]:player()}},{merge:true});});session={id:account,code,answers:[],finished:false};wait(code);});
};
function wait(code){dialog.querySelector('.duel-content').innerHTML='<div class="duel-wait"><small>ROOM</small><strong>'+code+'</strong><p>相手の参加を待っています</p></div><p class="duel-status" role="status"></p><button type="button" data-duel-cancel>退出</button>';dialog.querySelector('[data-duel-cancel]').onclick=()=>dialog.close();listen(code);waitingTimer=setTimeout(()=>{if(session&&!session.start){status('待機時間が終了しました。部屋を作り直してください。');stop();}},120000);}
function listen(code){unsubscribe?.();unsubscribe=window.fbOnSnapshot(ref(code),snapshot=>{if(!session||session.code!==code||uid()!==session.id)return;if(!snapshot.exists()){status('部屋が見つかりません。');stop();return;}const room=snapshot.data();if(!m.validRoom(room)){status('部屋のデータを確認できません。');stop();return;}session.room=room;if(room.status==='cancelled'){status('対戦は中止されました。レートは変わりません。');stop();return;}if(room.status==='finished'){result(room);return;}const start=ms(room.startsAt);if(room.status==='playing'&&start&&!session.start){clearTimeout(waitingTimer);session.start=start+3000;session.pool=room.pool;session.seed=room.seed;play();}opponent();},error=>{status('接続できません。回答記録は保持しています。再接続後に終了結果を確認してください。');if(/resource-exhausted/.test(error.code||''))stop();});}
function play(){
 const body=dialog.querySelector('.duel-content');body.innerHTML='<div class="duel-scoreboard"><div><small>あなた</small><strong data-duel-score>0</strong></div><div class="duel-clock" role="timer">60</div><div><small data-opponent-name>一人プレイ</small><strong data-opponent-score>—</strong></div></div><div class="duel-combo" aria-live="polite"></div><h3 class="duel-prompt"></h3><div class="duel-options"></div><p class="duel-status" role="status"></p><button type="button" class="duel-leave">終了する</button>';
 dialog.querySelector('.duel-leave').onclick=()=>{if(session.solo){finish(true);}else{finish(true);}};question();clearInterval(timer);timer=setInterval(tick,100);tick();opponent();
}
function question(){if(!session||session.finished)return;const q=m.question(session.pool,session.seed,session.answers.length),host=dialog.querySelector('.duel-options');dialog.querySelector('.duel-prompt').textContent=q.prompt;host.replaceChildren();q.options.forEach((text,index)=>{const button=document.createElement('button');button.type='button';button.textContent=text;button.className=index===9?'duel-none':'';button.onclick=()=>answer(index);host.append(button);});}
function answer(choice){if(!session||session.finished||Date.now()<session.start||Date.now()-session.start>=60000||session.answers.length>=m.maxAnswers)return;const q=m.question(session.pool,session.seed,session.answers.length);session.answers.push({choice,at:Date.now()-session.start});revision++;const value=m.score(session.pool,session.seed,session.answers);dialog.querySelector('[data-duel-score]').textContent=value.total;const combo=dialog.querySelector('.duel-combo');combo.textContent=choice===q.correct?(value.combo>1?value.combo+' COMBO · +'+(100+(value.combo-1)*10):'+100'):'MISS −50';combo.classList.toggle('is-miss',choice!==q.correct);window.AppSounds?.play(choice===q.correct?'swipe-right':'swipe-left');question();if(!session.solo&&!sending){setTimeout(()=>{if(session&&!session.finished)publish(session).catch(error=>status(error.message));},250);}if(session.answers.length===m.maxAnswers)finish();}
function opponent(){if(!session?.room||!dialog?.querySelector('[data-opponent-score]'))return;const other=Object.entries(session.room.players).find(([id])=>id!==session.id);if(!other)return;dialog.querySelector('[data-opponent-name]').textContent=other[1].name;dialog.querySelector('[data-opponent-score]').textContent=m.score(session.pool,session.seed,other[1].answers||[]).total;}
function tick(){if(!session||session.finished)return;if(uid()!==session.id){stop();dialog.close();return;}const remain=session.start-Date.now();const clock=dialog.querySelector('.duel-clock'),text=remain>0?'開始 '+Math.ceil(remain/1000):String(Math.max(0,Math.ceil((60000+remain)/1000)));if(clock.textContent!==text)clock.textContent=text;clock.classList.toggle('is-urgent',remain<=-50000&&remain>-60000);dialog.querySelectorAll('.duel-options button').forEach(button=>button.disabled=remain>0);if(remain<=-60000)finish();}
async function publish(target,done=false,abandoned=false){
 if(target.solo)return;const account=target.id;if(uid()!==account)throw Error('アカウントが変更されました。');if(sending)await sending;const version=revision,answers=target.answers.slice();const task=window.fbRunTransaction(window.db,async tx=>{const roomRef=ref(target.code),snap=await tx.get(roomRef);if(!snap.exists())return;const room=snap.data(),old=room.players?.[account];if(!old)throw Error('この部屋の参加者ではありません。');if(room.status==='waiting'){if(abandoned&&room.host===account)tx.set(roomRef,{status:'cancelled'},{merge:true});return;}if(room.status!=='playing'||old.done)return;if(answers.length<(old.answers||[]).length)return;m.score(room.pool,room.seed,answers);tx.set(roomRef,{players:{...room.players,[account]:{...old,answers,done,abandoned}}},{merge:true});});sending=task;try{await task;published=version;}finally{if(sending===task)sending=null;}if(!done&&session===target&&revision!==published)await publish(target);
}
async function finish(abandoned=false){
 if(!session||finishing||session.finished)return;finishing=true;clearInterval(timer);const target=session;target.finished=true;dialog.querySelectorAll('.duel-options button').forEach(button=>button.disabled=true);if(target.solo){const value=m.score(target.pool,target.seed,target.answers);status('終了 · '+value.total+'点（一人プレイはレート変更なし）');const close=dialog.querySelector('.duel-leave');close.textContent='閉じる';close.onclick=()=>dialog.close();finishing=false;return;}
 status(abandoned?'退出を保存しています…':'回答を保存しています…');try{await publish(target,true,abandoned);status('相手の終了を確認しています…');await settle(target.code);if(dialog&&session===target){const snap=await window.fbGetDoc(ref(target.code));if(snap.exists()&&snap.data().status==='finished')result(snap.data());else waitingTimer=setTimeout(()=>settle(target.code).catch(error=>status(error.message)),Math.max(7000,target.start+67000-Date.now()));}}catch(error){status('結果の同期が完了していません。'+error.message);const retry=document.createElement('button');retry.type='button';retry.textContent='結果を再確認';retry.onclick=async()=>{try{await publish(target,true,abandoned);await settle(target.code);}catch(e){status(e.message);}};dialog?.querySelector('.duel-content').append(retry);}finally{finishing=false;}
}
async function settle(code){
 connected();const account=uid();return window.fbRunTransaction(window.db,async tx=>{const roomRef=ref(code),snap=await tx.get(roomRef);if(!snap.exists())return;const room=snap.data();if(!m.validRoom(room))throw Error('部屋のデータを確認できません。');if(!room.players?.[account]||!room.guest)throw Error('参加者を確認できません。');if(room.status==='finished'||room.status==='cancelled')return;if(!room.players[room.host].abandoned&&!room.players[room.guest].abandoned&&Date.now()<ms(room.startsAt)+63000)return;const players=room.players,first=players[room.host],second=players[room.guest];if(!first.abandoned&&!second.abandoned&&(!first.done||!second.done)&&Date.now()<ms(room.startsAt)+70000)return;const normalized={...room,players:{[room.host]:{...first,abandoned:first.abandoned||(!first.done&&Date.now()>=ms(room.startsAt)+70000)},[room.guest]:{...second,abandoned:second.abandoned||(!second.done&&Date.now()>=ms(room.startsAt)+70000)}}},win=m.outcome(normalized);if(win===null){tx.set(roomRef,{status:'cancelled'},{merge:true});return;}
 const hostRef=window.fbDoc(window.db,'users',room.host),guestRef=window.fbDoc(window.db,'users',room.guest),a=await tx.get(hostRef),b=await tx.get(guestRef);if(!a.exists()||!b.exists())throw Error('アカウントを確認できません。');const ratings=m.elo(a.data().wordDuelRating,b.data().wordDuelRating,win),scores=[m.score(room.pool,room.seed,first.answers||[]).total,m.score(room.pool,room.seed,second.answers||[]).total];tx.set(hostRef,{wordDuelRating:ratings[0],wordDuelGames:Number(a.data().wordDuelGames||0)+1},{merge:true});tx.set(guestRef,{wordDuelRating:ratings[1],wordDuelGames:Number(b.data().wordDuelGames||0)+1},{merge:true});tx.set(roomRef,{status:'finished',result:{winner:win===.5?'':win===1?room.host:room.guest,ratings:{[room.host]:ratings[0],[room.guest]:ratings[1]},scores:{[room.host]:scores[0],[room.guest]:scores[1]}}},{merge:true});});
}
function result(room){if(!session||!dialog)return;session.finished=true;stop();const mine=session.id,won=room.result.winner;mergeRating({wordDuelRating:room.result.ratings[mine]});const body=dialog.querySelector('.duel-content');body.replaceChildren();const heading=document.createElement('h3');heading.className='duel-result';heading.textContent=won===mine?'VICTORY':won?'DEFEAT':'DRAW';const score=document.createElement('p');score.textContent=room.result.scores[mine]+'点 · レート '+room.result.ratings[mine];const close=document.createElement('button');close.type='button';close.textContent='閉じる';close.onclick=()=>dialog.close();body.append(heading,score,close);window.renderLeaderboard?.(false);}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&session?.start&&!session.finished)finish(true);});window.addEventListener('pagehide',()=>{if(session&&!session.solo&&!session.finished)publish(session,true,true).catch(()=>{});stop();});
window.WordDuel={localRating,mergeRating,isPlaying:()=>!!session?.start&&!session.finished,settle};window.onAppLoaded(renderRating);
})();
