// Listen only to the current room. No global room scans or matchmaking polling.
(function(){
'use strict';
const m=window.WordDuelModel,uid=()=>myId||'GUEST-000';
const ratings=new Map();
let dialog=null,session=null,unsubscribe=null,timer=null,waitingTimer=null,sending=null,revision=0,published=-1,finishing=false,opener=null,inertElements=[],answerTimer=null;
const portraits=new Map();
const rateKey=()=> 'core_v4_word_duel_rating_'+uid();
function localRating(){if(ratings.has(uid()))return ratings.get(uid());try{return m.rating(Number(localStorage.getItem(rateKey())||1500));}catch{return 1500;}}
function mergeRating(doc){if(Number.isFinite(doc?.wordDuelRating)){const value=m.rating(doc.wordDuelRating);ratings.set(uid(),value);try{if(localStorage.getItem(rateKey())!==String(value))localStorage.setItem(rateKey(),String(value));}catch(error){console.warn('対戦レートはクラウドの確定値を表示します',error);}}renderRating();}
function renderRating(){const el=document.getElementById('headerDuelRating');if(el)el.textContent='R '+localRating();}
function ms(value){return value?.toMillis?value.toMillis():typeof value==='number'?value:0;}
function ref(code){return window.fbDoc(window.db,'wordDuelRooms',code);}
function connected(){if(uid()==='GUEST-000')throw Error('対戦はログインしたアカウントで参加できます。一人プレイはゲストでも使えます。');if(!window.db||!window.fbRunTransaction||!window.fbOnSnapshot)throw Error('対戦にはクラウドへの接続が必要です。');if(window.FirestoreReadGuard?.paused())throw Error('クラウドの利用上限に達しています。今は一人プレイを利用してください。');}
function status(text){const node=dialog?.querySelector('.duel-status');if(node)node.textContent=text;}
function stop(){unsubscribe?.();unsubscribe=null;clearInterval(timer);clearTimeout(waitingTimer);clearTimeout(answerTimer);answerTimer=null;timer=null;waitingTimer=null;}
function cleanup(){stop();session=null;dialog=null;finishing=false;}
function closeScreen(){
 if(!dialog)return;
 if(session&&!session.solo&&!session.finished){const old=session;old.answers=old.answers.slice();publish(old,true,true).then(()=>old.start&&settle(old.code)).catch(()=>{});}
 window.WordDuelProgress.flush(session?.id).catch(()=>{});
 const el=dialog;cleanup();el.remove();document.body.classList.remove('duel-screen-open');
 inertElements.forEach(([node,value])=>{if(node.isConnected)node.inert=value;});inertElements=[];
 if(opener?.isConnected)opener.focus();opener=null;
}
function view(title,html){
 const el=document.createElement('section');el.className='word-duel-screen';el.id='wordDuelScreen';el.setAttribute('aria-labelledby','duelScreenTitle');el.tabIndex=-1;
 el.innerHTML='<header class="duel-screen-header"><button type="button" aria-label="フレンドに戻る" data-duel-back>‹</button><div><h2 id="duelScreenTitle"></h2></div><span class="duel-screen-badge">60秒</span></header><div class="duel-content">'+html+'<p class="duel-status" role="status"></p></div>';
 el.querySelector('h2').textContent=title;opener=document.activeElement;
 inertElements=Array.from(document.body.children).filter(node=>!['SCRIPT','LINK','STYLE'].includes(node.tagName)).map(node=>[node,node.inert]);inertElements.forEach(([node])=>node.inert=true);
 document.body.append(el);document.body.classList.add('duel-screen-open');dialog=el;el.querySelector('[data-duel-back]').onclick=closeScreen;el.querySelectorAll('[data-library-close]').forEach(button=>button.onclick=closeScreen);el.focus();return el;
}
function selection(){const books=typeof textbooksPool==='undefined'?[]:textbooksPool;const select=dialog.querySelector('select');for(const book of books){if(window.LibraryState?.isDeleted('book',book.id))continue;const option=document.createElement('option');option.value=book.id;option.textContent=book.name||book.title||book.id;select.append(option);}if(typeof currentTextbook==='string')select.value=currentTextbook;}
async function words(seed){const id=dialog.querySelector('select').value||currentTextbook;let source=window.VocabMaster.resolve(id)?.master;if(!source&&window.db){const snap=await window.fbGetDoc(window.fbDoc(window.db,'shared','vocab_'+id));source=snap.exists()?snap.data().custom_words:null;}const normalized=window.migrateVocabData(window.stripVocabProgressFromWords(source||[]));for(const word of normalized){const meaning=word.meanings?.[0];if(meaning)word.duelRef={num:String(word.num),mid:String(meaning.id),sig:window.buildWordSignature(word),count:word.meanings.length};}const result=m.pool(normalized,seed);if(result.length<10)throw Error('異なる意味を持つ単語が10個以上の単語帳を選んでください。');return result;}
function player(){return {name:String(myName||uid()).slice(0,40),frame:window.IconFrames?.equipped()||'',answers:[],done:false,abandoned:false};}
function portrait(host,value,name,frame){if(!host)return;host.replaceChildren(window.RankingVisuals.avatar(value,name,JSON.stringify({frame})));}
async function opponentPortrait(target,id,person){
 const host=dialog?.querySelector('[data-player-id="'+CSS.escape(id)+'"] .duel-player-avatar');portrait(host,'',person.name,person.frame);
 const cached=portraits.get(id),known=window.People?.preview?.(id);
 let photo=cached&&Date.now()-cached.at<300000?cached.avatar:known?.avatar;
 if(photo===undefined&&window.db&&window.fbGetDoc){try{const snap=await window.fbGetDoc(window.fbDoc(window.db,'users',id));photo=snap.exists()?snap.data().avatar:'';if(typeof photo!=='string'||photo.length>100000)photo='';portraits.delete(id);portraits.set(id,{at:Date.now(),avatar:photo});if(portraits.size>4)portraits.delete(portraits.keys().next().value);}catch{photo='';}}
 if(session===target&&dialog?.querySelector('[data-player-id="'+CSS.escape(id)+'"] .duel-player-avatar')===host)portrait(host,photo||'',person.name,person.frame);
}
function locked(fn){return async event=>{const button=event.currentTarget,screen=dialog;if(screen.dataset.busy)return;screen.dataset.busy='true';button.disabled=true;status('準備しています…');try{await fn();}catch(error){if(dialog===screen)status(error.message||'接続を確認して再試行してください。');}finally{delete screen.dataset.busy;if(button.isConnected)button.disabled=false;}};}
function patch(tx,reference,fields){tx.set(reference,fields,{mergeFields:Object.keys(fields)});}
function setup(){return {duration:Number(dialog.querySelector('[data-duel-duration]').value),capacity:Number(dialog.querySelector('[data-duel-capacity]').value)};}
window.openWordDuel=function(){
 if(dialog)return;view('単語バトル','<p class="duel-intro">10択問題。一人でも、部屋番号で対戦でも。</p><label class="duel-book-label">出題する単語帳<select aria-label="対戦の単語帳"></select></label><div class="duel-settings"><label>プレイ時間<select data-duel-duration aria-label="プレイ時間"><option value="30000">30秒</option><option value="60000" selected>1分</option><option value="120000">2分</option><option value="180000">3分</option></select></label><label>対戦人数<select data-duel-capacity aria-label="対戦人数"><option value="2">2人</option><option value="3">3人</option><option value="4">4人</option></select></label></div><div class="duel-lobby-actions"><button type="button" data-duel-solo>一人プレイ</button><button type="button" data-duel-create>部屋を作る</button></div><div class="duel-join"><input aria-label="部屋番号" inputmode="numeric" maxlength="6" placeholder="6桁の部屋番号"><button type="button" data-duel-join>参加</button></div><p class="duel-rules">正解 +100。連続正解ごとに +10%。ミス −50。選んだ人数がそろうと開始します。参加する場合は部屋の設定が適用されます。</p><button type="button" data-library-close>閉じる</button>');selection();
 dialog.querySelector('[data-duel-solo]').onclick=locked(async()=>{const settings=setup(),seed=crypto.getRandomValues(new Uint32Array(1))[0],book=dialog.querySelector('select').value,account=uid(),screen=dialog,pool=await words(seed);if(dialog!==screen||uid()!==account)return;session={...settings,solo:true,id:account,book,pool,seed,start:Date.now(),answers:[],finished:false};play();});
 dialog.querySelector('[data-duel-create]').onclick=locked(async()=>{connected();const settings=setup(),seed=crypto.getRandomValues(new Uint32Array(1))[0],book=dialog.querySelector('select').value,account=uid(),screen=dialog,pool=await words(seed);if(new TextEncoder().encode(JSON.stringify(pool)).length>320000)throw Error('出題データが大きすぎます。別の単語帳を選んでください。');if(dialog!==screen||uid()!==account)return;let code;
 const room={version:4,...settings,book,host:account,status:'waiting',pool,seed,players:{[account]:player()}};if(!m.validRoom(room))throw Error('単語の出題データを確認できません。別の単語帳を選んでください。');
 for(let attempt=0;attempt<5;attempt++){code=String(100000+crypto.getRandomValues(new Uint32Array(1))[0]%900000);const made=await window.fbRunTransaction(window.db,async tx=>{const roomRef=ref(code),snap=await tx.get(roomRef);if(snap.exists())return false;tx.set(roomRef,{...room,createdAt:window.fbServerTimestamp()});return true;});if(made)break;code=null;}if(!code)throw Error('部屋番号を作れませんでした。再試行してください。');if(dialog!==screen||uid()!==account){await publish({id:account,code,answers:[]},true,true);return;}session={id:account,code,answers:[],finished:false};wait(code);});
 dialog.querySelector('[data-duel-join]').onclick=locked(async()=>{connected();const code=dialog.querySelector('input').value.trim(),account=uid(),screen=dialog;if(!/^\d{6}$/.test(code))throw Error('6桁の部屋番号を入力してください。');await window.fbRunTransaction(window.db,async tx=>{const snap=await tx.get(ref(code));if(!snap.exists())throw Error('部屋が見つかりません。');const room=snap.data();if(!m.validRoom(room))throw Error('部屋のデータを確認できません。全員アプリを更新して部屋を作り直してください。');if(room.status!=='waiting'||room.players[account]||Object.keys(room.players).length>=room.capacity)throw Error('この部屋には参加できません。');if(Date.now()-ms(room.createdAt)>120000)throw Error('この部屋の待機時間は終了しました。');const players={...room.players,[account]:player()},full=Object.keys(players).length===room.capacity;patch(tx,ref(code),{players,...(full?{status:'playing',startsAt:window.fbServerTimestamp()}:{})});});if(dialog!==screen||uid()!==account){await publish({id:account,code,answers:[]},true,true);await settle(code);return;}session={id:account,code,answers:[],finished:false};wait(code);});
};
function wait(code){dialog.querySelector('.duel-content').innerHTML='<div class="duel-wait"><small>部屋番号</small><strong>'+code+'</strong><p data-wait-count></p><p data-wait-names></p></div><p class="duel-status" role="status"></p><button type="button" data-duel-cancel>退出</button>';dialog.querySelector('[data-duel-cancel]').onclick=closeScreen;listen(code);waitingTimer=setTimeout(()=>{if(session&&!session.start){status('待機時間が終了しました。部屋を作り直してください。');publish(session,true,true).catch(()=>{});stop();}},120000);}
function listen(code){unsubscribe?.();unsubscribe=window.fbOnSnapshot(ref(code),snapshot=>{
 if(!session||session.code!==code||uid()!==session.id)return;if(!snapshot.exists()){status('部屋が見つかりません。');stop();return;}const room=snapshot.data();if(!m.validRoom(room)){status('部屋のデータを確認できません。');stop();return;}session.room=room;
 if(room.status==='cancelled'){status('対戦は中止されました。レートは変わりません。');stop();return;}if(!room.players[session.id]){status('部屋から退出しました。');stop();return;}if(room.status==='finished'){result(room);return;}
 const count=dialog.querySelector('[data-wait-count]');if(count){count.textContent=Object.keys(room.players).length+' / '+room.capacity+'人 · '+room.duration/1000+'秒';dialog.querySelector('[data-wait-names]').textContent=Object.values(room.players).map(person=>person.name).join('、');}
 const start=ms(room.startsAt);if(room.status==='playing'&&start&&!session.start){clearTimeout(waitingTimer);session.start=start+3000;session.book=room.book;session.duration=room.duration;session.capacity=room.capacity;session.pool=room.pool;session.seed=room.seed;play();}opponent();
 },()=>{status('接続できません。回答記録は保持しています。終了後に再確認できます。');});}

function play(){
 revision=0;published=-1;dialog.querySelector('.duel-screen-badge').textContent=session.duration/1000+'秒';
 const body=dialog.querySelector('.duel-content');body.innerHTML='<div class="duel-clock-row"><div class="duel-clock" role="timer"></div><small>秒</small></div><div class="duel-scoreboard"></div><div class="duel-time-track"><span></span></div><div class="duel-combo" aria-live="polite"></div><div class="duel-question-card"><small class="duel-question-label"></small><h3 class="duel-prompt"></h3></div><div class="duel-options"></div><div class="duel-correction" role="status" hidden><small>正しい意味</small><strong></strong><button type="button" data-duel-next>次の問題</button></div><p class="duel-status" role="status"></p><button type="button" class="duel-leave">終了する</button>';
 const players=session.solo?{[session.id]:player()}:session.room.players,host=dialog.querySelector('.duel-scoreboard');host.style.setProperty('--duel-players',Object.keys(players).length);
 for(const [id,person]of Object.entries(players)){const column=document.createElement('div');column.className='duel-player';column.dataset.playerId=id;column.innerHTML='<div class="duel-player-avatar"></div><small></small><strong>0</strong>';column.querySelector('small').textContent=person.name;host.append(column);if(id===session.id){column.querySelector('strong').setAttribute('data-duel-score','');portrait(column.querySelector('.duel-player-avatar'),localStorage.getItem('core_v4_user_avatar_'+id)||'',myName,window.IconFrames?.equipped());}else opponentPortrait(session,id,person);}
 dialog.querySelector('.duel-leave').onclick=()=>finish(true);dialog.querySelector('[data-duel-next]').onclick=question;question();clearInterval(timer);timer=setInterval(tick,100);tick();opponent();
}
function question(){if(!session||session.finished)return;session.reviewing=false;session.answering=false;const q=m.question(session.pool,session.seed,session.answers.length),host=dialog.querySelector('.duel-options');dialog.querySelector('.duel-prompt').textContent=q.prompt;dialog.querySelector('.duel-question-label').textContent='第'+(session.answers.length+1)+'問';dialog.querySelector('.duel-correction').hidden=true;host.replaceChildren();q.options.forEach((text,index)=>{const button=document.createElement('button');button.type='button';button.textContent=text;button.className=index===9?'duel-none':'';button.onclick=()=>answer(index);host.append(button);});}
function answer(choice){
 if(!session||session.finished||session.reviewing||session.answering||Date.now()<session.start||Date.now()-session.start>=session.duration||session.answers.length>=m.maxAnswers)return;
 const target=session,q=m.question(target.pool,target.seed,target.answers.length),right=choice===q.correct;target.answers.push({choice,at:Date.now()-target.start});revision++;
 const value=m.score(target.pool,target.seed,target.answers,target.duration);dialog.querySelector('[data-duel-score]').textContent=value.total;
 const combo=dialog.querySelector('.duel-combo');combo.textContent=right?(value.combo>1?value.combo+'連続正解 · +'+(100+(value.combo-1)*10):'+100'):'不正解 −50';combo.classList.toggle('is-miss',!right);if(!matchMedia('(prefers-reduced-motion: reduce)').matches)combo.animate?.([{transform:'scale(.9)',opacity:.4},{transform:'scale(1.08)',opacity:1},{transform:'scale(1)',opacity:1}],{duration:220});
 window.AppSounds?.play(right?'swipe-right':'swipe-left');
 const buttons=dialog.querySelectorAll('.duel-options button');buttons.forEach(button=>button.disabled=true);buttons[choice].classList.add('is-selected');buttons[choice].setAttribute('aria-pressed','true');
 try{window.WordDuelProgress.apply(target.book,q.ref,right,target.id);}catch(error){status('理解度の保存を確認できません。'+error.message);}
 if(target.answers.length%5===0)window.WordDuelProgress.flush(target.id).catch(()=>{});
 if(right){target.answering=true;buttons[choice].classList.add('is-correct');answerTimer=setTimeout(()=>{answerTimer=null;if(session===target&&!target.finished)question();},180);}else{
  target.reviewing=true;buttons[choice].classList.add('is-wrong');buttons[q.correct].classList.add('is-correct');
  const correction=dialog.querySelector('.duel-correction');correction.querySelector('strong').textContent=q.meaning;correction.hidden=false;correction.querySelector('button').focus();
 }
 if(!target.solo&&!sending)setTimeout(()=>{if(session===target&&!target.finished)publish(target).catch(error=>status(error.message));},250);
 if(target.answers.length===m.maxAnswers)finish();
}
function opponent(){if(!session?.room||!dialog?.querySelector('.duel-scoreboard'))return;for(const [id,person]of Object.entries(session.room.players)){if(id===session.id)continue;const column=dialog.querySelector('[data-player-id="'+CSS.escape(id)+'"]');if(!column)continue;const score=m.score(session.pool,session.seed,person.answers||[],session.duration).total,columnScore=column.querySelector('strong');if(columnScore.textContent!==String(score))columnScore.textContent=score;column.classList.toggle('is-abandoned',!!person.abandoned);}}
function tick(){if(!session||session.finished)return;if(uid()!==session.id){closeScreen();return;}const remain=session.start-Date.now(),duration=session.duration,clock=dialog.querySelector('.duel-clock'),text=remain>0?'開始 '+Math.ceil(remain/1000):String(Math.max(0,Math.ceil((duration+remain)/1000)));if(clock.textContent!==text){clock.textContent=text;dialog.querySelector('.duel-time-track span').style.transform='scaleX('+Math.max(0,Math.min(1,(duration+remain)/duration))+')';}clock.classList.toggle('is-urgent',remain<=10000-duration&&remain>-duration);dialog.querySelectorAll('.duel-options button').forEach(button=>button.disabled=remain>0||session.reviewing||session.answering);if(remain<=-duration)finish();}

async function publish(target,done=false,abandoned=false){
 if(target.solo)return;const account=target.id;if(uid()!==account)throw Error('アカウントが変更されました。');if(sending)await sending;if(!done&&!abandoned&&published===revision)return;const version=revision,answers=target.answers.slice();const task=window.fbRunTransaction(window.db,async tx=>{const roomRef=ref(target.code),snap=await tx.get(roomRef);if(!snap.exists())return;const room=snap.data(),old=room.players?.[account];if(!old)throw Error('この部屋の参加者ではありません。');if(room.status==='waiting'){if(abandoned){if(room.host===account)patch(tx,roomRef,{status:'cancelled'});else{const players={...room.players};delete players[account];patch(tx,roomRef,{players});}}return;}if(room.status!=='playing'||old.done)return;if(answers.length<(old.answers||[]).length)return;m.score(room.pool,room.seed,answers,room.duration);patch(tx,roomRef,{players:{...room.players,[account]:{...old,answers,done,abandoned}}});});sending=task;try{await task;published=version;}finally{if(sending===task)sending=null;}if(!done&&session===target&&revision!==published)await publish(target);
}
async function finish(abandoned=false){
 if(!session||finishing||session.finished)return;finishing=true;clearInterval(timer);const target=session;target.finished=true;clearTimeout(answerTimer);window.WordDuelProgress.flush(target.id).catch(()=>{});dialog.querySelectorAll('.duel-options button,[data-duel-next]').forEach(button=>button.disabled=true);if(target.solo){
  const value=m.score(target.pool,target.seed,target.answers,target.duration),summary=document.createElement('div');summary.className='duel-solo-result';summary.innerHTML='<small></small><strong></strong>';summary.querySelector('small').textContent=abandoned?'途中終了':'終了';summary.querySelector('strong').textContent=value.total+'点';dialog.querySelector('.duel-content').prepend(summary);
  dialog.querySelector('.duel-question-card').hidden=true;dialog.querySelector('.duel-options').hidden=true;dialog.querySelector('.duel-correction').hidden=true;status('一人プレイはレート変更なし');const close=dialog.querySelector('.duel-leave');close.textContent='閉じる';close.onclick=closeScreen;finishing=false;return;
 }
 status(abandoned?'退出を保存しています…':'回答を保存しています…');try{await publish(target,true,abandoned);status('相手の終了を確認しています…');await settle(target.code);if(dialog&&session===target){const snap=await window.fbGetDoc(ref(target.code));if(snap.exists()&&snap.data().status==='finished')result(snap.data());else waitingTimer=setTimeout(()=>settle(target.code).catch(error=>status(error.message)),Math.max(7000,target.start+target.duration+7000-Date.now()));}}catch(error){status('結果の同期が完了していません。'+error.message);const retry=document.createElement('button');retry.type='button';retry.textContent='結果を再確認';retry.onclick=async()=>{try{await publish(target,true,abandoned);await settle(target.code);}catch(e){status(e.message);}};dialog?.querySelector('.duel-content').append(retry);}finally{finishing=false;}
}
async function settle(code){
 connected();const account=uid();return window.fbRunTransaction(window.db,async tx=>{
 const roomRef=ref(code),snap=await tx.get(roomRef);if(!snap.exists())return;const room=snap.data();if(!m.validRoom(room))throw Error('部屋のデータを確認できません。');if(!room.players?.[account])throw Error('参加者を確認できません。');if(room.status!=='playing')return;
 const end=ms(room.startsAt)+3000+room.duration,people=Object.values(room.players);if(people.every(person=>person.abandoned)){patch(tx,roomRef,{status:'cancelled'});return;}if(Date.now()<end)return;if(people.some(person=>!person.done&&!person.abandoned)&&Date.now()<end+7000)return;
 const normalized={...room,players:Object.fromEntries(Object.entries(room.players).map(([id,person])=>[id,{...person,abandoned:person.abandoned||!person.done}]))},places=m.placements(normalized);if(!places){patch(tx,roomRef,{status:'cancelled'});return;}
 const accounts=[];for(const entry of places){const reference=window.fbDoc(window.db,'users',entry.id),profile=await tx.get(reference);if(!profile.exists())throw Error('アカウントを確認できません。');accounts.push({entry,reference,data:profile.data()});}
 const result={ratings:{},scores:{},places:{},deltas:{}};
 for(const {entry,reference,data}of accounts){const before=m.rating(data.wordDuelRating),after=Math.max(0,before+entry.delta);result.ratings[entry.id]=after;result.scores[entry.id]=entry.score;result.places[entry.id]=entry.place;result.deltas[entry.id]=after-before;tx.set(reference,{wordDuelRating:after,wordDuelGames:Number(data.wordDuelGames||0)+1},{merge:true});}
 patch(tx,roomRef,{status:'finished',result});
 });
}
function result(room){if(!session||!dialog)return;session.finished=true;stop();const mine=session.id;mergeRating({wordDuelRating:room.result.ratings[mine]});const body=dialog.querySelector('.duel-content');body.replaceChildren();const heading=document.createElement('h3');heading.className='duel-result';heading.textContent=room.result.places[mine]+'位';const board=document.createElement('ol');board.className='duel-results';
 Object.keys(room.players).sort((a,b)=>room.result.places[a]-room.result.places[b]||a.localeCompare(b)).forEach(id=>{const li=document.createElement('li'),person=room.players[id],name=document.createElement('span'),score=document.createElement('strong'),rate=document.createElement('small');name.textContent=room.result.places[id]+'位 '+person.name;score.textContent=room.result.scores[id]+'点';const delta=room.result.deltas[id];rate.textContent='レート '+room.result.ratings[id]+'（'+(delta>0?'+':'')+delta+'）';li.append(name,score,rate);board.append(li);});
 const close=document.createElement('button');close.type='button';close.textContent='閉じる';close.onclick=closeScreen;body.append(heading,board,close);window.renderLeaderboard?.(false);
}

document.addEventListener('visibilitychange',()=>{if(document.hidden&&session?.start&&!session.finished)finish(true);});window.addEventListener('pagehide',()=>{window.WordDuelProgress.flush(session?.id).catch(()=>{});if(session&&!session.solo&&!session.finished)publish(session,true,true).catch(()=>{});stop();});
document.addEventListener('keydown',event=>{if(!dialog)return;if(event.key==='Escape'){event.preventDefault();closeScreen();}else if(event.key==='Tab'){const nodes=Array.from(dialog.querySelectorAll('button,input,select')).filter(node=>!node.disabled&&node.getClientRects().length);if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===dialog)){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});
window.WordDuel={localRating,mergeRating,isPlaying:()=>!!session?.start&&!session.finished,settle};window.onAppLoaded(renderRating);
})();
