// Listen only to the current room. No global room scans or matchmaking polling.
(function(){
'use strict';
const m=window.WordDuelModel,uid=()=>myId||'GUEST-000';
const ratings=new Map();
let dialog=null,session=null,unsubscribe=null,timer=null,waitingTimer=null,sending=null,revision=0,published=-1,finishing=false,opener=null,inertElements=[],answerTimer=null;
const portraits=new Map();
const rateKey=()=> 'core_v4_word_duel_rating_'+uid();
function localRating(){if(ratings.has(uid()))return ratings.get(uid());try{return m.rating(Number(localStorage.getItem(rateKey())||1500));}catch{return 1500;}}
function mergeRating(doc){window.WordDuelSolo?.merge(doc);if(Number.isFinite(doc?.wordDuelRating)){const value=m.rating(doc.wordDuelRating);ratings.set(uid(),value);try{if(localStorage.getItem(rateKey())!==String(value))localStorage.setItem(rateKey(),String(value));}catch(error){console.warn('対戦レートはクラウドの確定値を表示します',error);}}renderRating();}
function renderRating(){const el=document.getElementById('headerDuelRating');if(el)el.textContent='R '+localRating();}
function ms(value){return value?.toMillis?value.toMillis():typeof value==='number'?value:0;}
function ref(code){return window.fbDoc(window.db,'wordDuelRooms',code);}
function connected(){if(uid()==='GUEST-000')throw Error('対戦はログインしたアカウントで参加できます。一人プレイはゲストでも使えます。');if(!window.db||!window.fbRunTransaction||!window.fbOnSnapshot)throw Error('対戦にはクラウドへの接続が必要です。');if(window.FirestoreReadGuard?.paused())throw Error('クラウドの利用上限に達しています。今は一人プレイを利用してください。');}
function status(text){const node=dialog?.querySelector('.duel-status');if(node)node.textContent=text;}
function stop(){unsubscribe?.();unsubscribe=null;clearInterval(timer);clearTimeout(waitingTimer);clearTimeout(answerTimer);answerTimer=null;timer=null;waitingTimer=null;}
function cleanup(){stop();session=null;dialog=null;finishing=false;}
function closeScreen(){
 if(!dialog)return;
 if(session&&!session.solo&&!session.finished){const old=session;old.answers=old.answers.slice();publish(old,true,true).then(()=>old.start&&settle(old.code)).catch(()=>{});}
 window.WordDuelProgress.flush(session?.id).catch(()=>{});
 const el=dialog;cleanup();el.remove();document.body.classList.remove('duel-screen-open');
 inertElements.forEach(([node,value])=>{if(node.isConnected)node.inert=value;});inertElements=[];
 if(opener?.isConnected)opener.focus();opener=null;
}
function view(title,html){
 const el=document.createElement('section');el.className='word-duel-screen';el.id='wordDuelScreen';el.setAttribute('aria-labelledby','duelScreenTitle');el.tabIndex=-1;
 el.innerHTML='<header class="duel-screen-header"><button type="button" aria-label="フレンドに戻る" data-duel-back>‹</button><div><h2 id="duelScreenTitle"></h2></div><span class="duel-screen-badge">60秒</span></header><div class="duel-content">'+html+'<p class="duel-status" role="status"></p></div>';
 el.querySelector('h2').textContent=title;opener=document.activeElement;
 inertElements=Array.from(document.body.children).filter(node=>!['SCRIPT','LINK','STYLE'].includes(node.tagName)).map(node=>[node,node.inert]);inertElements.forEach(([node])=>node.inert=true);
 document.body.append(el);document.body.classList.add('duel-screen-open');dialog=el;el.querySelector('[data-duel-back]').onclick=closeScreen;el.querySelectorAll('[data-library-close]').forEach(button=>button.onclick=closeScreen);el.focus();return el;
}
function selection(){const books=typeof textbooksPool==='undefined'?[]:textbooksPool;const select=dialog.querySelector('select');for(const book of books){if(window.LibraryState?.isDeleted('book',book.id))continue;const option=document.createElement('option');option.value=book.id;option.textContent=book.name||book.title||book.id;select.append(option);}if(typeof currentTextbook==='string')select.value=currentTextbook;}
async function words(seed){const id=dialog.querySelector('select').value||currentTextbook;let source=window.VocabMaster.resolve(id)?.master;if(!source&&window.db){const snap=await window.fbGetDoc(window.fbDoc(window.db,'shared','vocab_'+id));source=snap.exists()?snap.data().custom_words:null;}const normalized=window.migrateVocabData(window.stripVocabProgressFromWords(source||[]));for(const word of normalized){const meaning=word.meanings?.[0];if(meaning)word.duelRef={num:String(word.num),mid:String(meaning.id),sig:window.buildWordSignature(word),count:word.meanings.length};}const result=m.pool(normalized,seed);if(result.length<10)throw Error('異なる意味を持つ単語が10個以上の単語帳を選んでください。');return result;}
function player(){return {name:String(myName||uid()).slice(0,40),frame:window.IconFrames?.equipped()||'',answers:[],done:false,abandoned:false};}
function portrait(host,value,name,frame){if(!host)return;host.replaceChildren(window.RankingVisuals.avatar(value,name,JSON.stringify({frame})));}
async function opponentPortrait(target,id,person){
 const host=dialog?.querySelector('[data-opponent-avatar]');portrait(host,'',person.name,person.frame);
 const cached=portraits.get(id),known=window.People?.preview?.(id);
 let photo=cached&&Date.now()-cached.at<300000?cached.avatar:known?.avatar;
 if(photo===undefined&&window.db&&window.fbGetDoc){try{const snap=await window.fbGetDoc(window.fbDoc(window.db,'users',id));photo=snap.exists()?snap.data().avatar:'';if(typeof photo!=='string'||photo.length>100000)photo='';portraits.delete(id);portraits.set(id,{at:Date.now(),avatar:photo});if(portraits.size>4)portraits.delete(portraits.keys().next().value);}catch{photo='';}}
 if(session===target&&dialog?.querySelector('[data-opponent-avatar]')===host)portrait(host,photo||'',person.name,person.frame);
}
function locked(fn){return async event=>{const button=event.currentTarget,screen=dialog;button.disabled=true;status('準備しています…');try{await fn();}catch(error){if(dialog===screen)status(error.message||'接続を確認して再試行してください。');}finally{if(button.isConnected)button.disabled=false;}};}
window.openWordDuel=function(){
 if(dialog)return;view('単語バトル','<div class="duel-lobby-hero"><h3>単語バトル</h3><p class="duel-intro">60秒の10択問題。一人でも、部屋番号で対戦でも。</p></div><label class="duel-book-label">出題する単語帳<select aria-label="対戦の単語帳"></select></label><div class="duel-lobby-actions"><button type="button" data-duel-solo>一人プレイ</button><button type="button" data-duel-create>部屋を作る</button></div><div class="duel-join"><input aria-label="部屋番号" inputmode="numeric" maxlength="6" placeholder="6桁の部屋番号"><button type="button" data-duel-join>参加</button></div><p class="duel-rules">正解 +100。連続正解ごとに +10%。ミス −50、コンボ解除。対戦レートは1500から。</p><button type="button" data-library-close>閉じる</button>');selection();
 dialog.querySelector('[data-duel-solo]').onclick=locked(async()=>{const seed=crypto.getRandomValues(new Uint32Array(1))[0],book=dialog.querySelector('select').value,account=uid(),screen=dialog,pool=await words(seed);if(dialog!==screen||uid()!==account)return;session={solo:true,id:account,book,pool,seed,start:Date.now(),answers:[],finished:false};play();});
 dialog.querySelector('[data-duel-create]').onclick=locked(async()=>{connected();const seed=crypto.getRandomValues(new Uint32Array(1))[0],book=dialog.querySelector('select').value,account=uid(),screen=dialog,pool=await words(seed);if(new TextEncoder().encode(JSON.stringify(pool)).length>320000)throw Error('出題データが大きすぎます。別の単語帳を選んでください。');if(dialog!==screen||uid()!==account)return;let code;for(let attempt=0;attempt<5;attempt++){code=String(100000+crypto.getRandomValues(new Uint32Array(1))[0]%900000);const made=await window.fbRunTransaction(window.db,async tx=>{const roomRef=ref(code),snap=await tx.get(roomRef);if(snap.exists())return false;tx.set(roomRef,{version:3,book,host:account,guest:'',status:'waiting',createdAt:window.fbServerTimestamp(),pool,seed,players:{[account]:player()}});return true;});if(made)break;code=null;}if(!code)throw Error('部屋番号を作れませんでした。再試行してください。');if(dialog!==screen||uid()!==account){await publish({id:account,code,answers:[]},true,true);return;}session={id:account,code,answers:[],finished:false};wait(code);});
 dialog.querySelector('[data-duel-join]').onclick=locked(async()=>{connected();const code=dialog.querySelector('input').value.trim(),account=uid(),screen=dialog;if(!/^\d{6}$/.test(code))throw Error('6桁の部屋番号を入力してください。');await window.fbRunTransaction(window.db,async tx=>{const snap=await tx.get(ref(code));if(!snap.exists())throw Error('部屋が見つかりません。');const room=snap.data();if(!m.validRoom(room))throw Error('部屋のデータを確認できません。両者ともアプリを更新して部屋を作り直してください。');if(room.status!=='waiting'||room.guest||room.host===account)throw Error('この部屋には参加できません。');if(Date.now()-ms(room.createdAt)>120000)throw Error('この部屋の待機時間は終了しました。');tx.set(ref(code),{guest:account,status:'playing',startsAt:window.fbServerTimestamp(),players:{...room.players,[account]:player()}},{merge:true});});if(dialog!==screen||uid()!==account){await publish({id:account,code,answers:[]},true,true);await settle(code);return;}session={id:account,code,answers:[],finished:false};wait(code);});
};
function wait(code){dialog.querySelector('.duel-content').innerHTML='<div class="duel-wait"><small>部屋番号</small><strong>'+code+'</strong><p>相手の参加を待っています</p></div><p class="duel-status" role="status"></p><button type="button" data-duel-cancel>退出</button>';dialog.querySelector('[data-duel-cancel]').onclick=closeScreen;listen(code);waitingTimer=setTimeout(()=>{if(session&&!session.start){status('待機時間が終了しました。部屋を作り直してください。');stop();}},120000);}
function listen(code){unsubscribe?.();unsubscribe=window.fbOnSnapshot(ref(code),snapshot=>{if(!session||session.code!==code||uid()!==session.id)return;if(!snapshot.exists()){status('部屋が見つかりません。');stop();return;}const room=snapshot.data();if(!m.validRoom(room)){status('部屋のデータを確認できません。');stop();return;}session.room=room;if(room.status==='cancelled'){status('対戦は中止されました。レートは変わりません。');stop();return;}if(room.status==='finished'){result(room);return;}const start=ms(room.startsAt);if(room.status==='playing'&&start&&!session.start){clearTimeout(waitingTimer);session.start=start+3000;session.book=room.book;session.pool=room.pool;session.seed=room.seed;play();}opponent();},error=>{status('接続できません。回答記録は保持しています。再接続後に終了結果を確認してください。');if(/resource-exhausted/.test(error.code||''))stop();});}
function play(){
 const body=dialog.querySelector('.duel-content');body.innerHTML='<div class="duel-scoreboard"><div class="duel-player"><div data-self-avatar></div><small data-self-name></small><strong data-duel-score>0</strong></div><div><div class="duel-clock" role="timer">60</div><small class="duel-clock-label">秒</small></div><div class="duel-player"><div data-opponent-avatar></div><small data-opponent-name>相手</small><strong data-opponent-score>—</strong></div></div><div class="duel-time-track"><span></span></div><div class="duel-combo" aria-live="polite"></div><div class="duel-question-card"><small class="duel-question-label"></small><h3 class="duel-prompt"></h3></div><div class="duel-options"></div><div class="duel-correction" role="status" hidden><small>正しい意味</small><strong></strong><button type="button" data-duel-next>次の問題</button></div><p class="duel-status" role="status"></p><button type="button" class="duel-leave">終了する</button>';
 portrait(dialog.querySelector('[data-self-avatar]'),localStorage.getItem('core_v4_user_avatar_'+session.id)||'',myName,window.IconFrames?.equipped());dialog.querySelector('[data-self-name]').textContent=myName||'あなた';
 if(session.solo){dialog.querySelector('[data-opponent-name]').textContent='自己ベスト';dialog.querySelector('[data-opponent-score]').textContent=window.WordDuelSolo.best()??'—';portrait(dialog.querySelector('[data-opponent-avatar]'),'', '★','');}
 dialog.querySelector('.duel-leave').onclick=()=>finish(true);dialog.querySelector('[data-duel-next]').onclick=question;question();clearInterval(timer);timer=setInterval(tick,100);tick();opponent();
}
function question(){if(!session||session.finished)return;session.reviewing=false;session.answering=false;const q=m.question(session.pool,session.seed,session.answers.length),host=dialog.querySelector('.duel-options');dialog.querySelector('.duel-prompt').textContent=q.prompt;dialog.querySelector('.duel-question-label').textContent='第'+(session.answers.length+1)+'問';dialog.querySelector('.duel-correction').hidden=true;host.replaceChildren();q.options.forEach((text,index)=>{const button=document.createElement('button');button.type='button';button.textContent=text;button.className=index===9?'duel-none':'';button.onclick=()=>answer(index);host.append(button);});}
function answer(choice){
 if(!session||session.finished||session.reviewing||session.answering||Date.now()<session.start||Date.now()-session.start>=60000||session.answers.length>=m.maxAnswers)return;
 const target=session,q=m.question(target.pool,target.seed,target.answers.length),right=choice===q.correct;target.answers.push({choice,at:Date.now()-target.start});revision++;
 const value=m.score(target.pool,target.seed,target.answers);dialog.querySelector('[data-duel-score]').textContent=value.total;
 const combo=dialog.querySelector('.duel-combo');combo.textContent=right?(value.combo>1?value.combo+'連続正解 · +'+(100+(value.combo-1)*10):'+100'):'不正解 −50';combo.classList.toggle('is-miss',!right);if(!matchMedia('(prefers-reduced-motion: reduce)').matches)combo.animate?.([{transform:'scale(.9)',opacity:.4},{transform:'scale(1.08)',opacity:1},{transform:'scale(1)',opacity:1}],{duration:220});
 window.AppSounds?.play(right?'swipe-right':'swipe-left');
 const buttons=dialog.querySelectorAll('.duel-options button');buttons.forEach(button=>button.disabled=true);buttons[choice].classList.add('is-selected');buttons[choice].setAttribute('aria-pressed','true');
 try{window.WordDuelProgress.apply(target.book,q.ref,right,target.id);}catch(error){status('理解度の保存を確認できません。'+error.message);}
 if(target.answers.length%5===0)window.WordDuelProgress.flush(target.id).catch(()=>{});
 if(right){target.answering=true;buttons[choice].classList.add('is-correct');answerTimer=setTimeout(()=>{answerTimer=null;if(session===target&&!target.finished)question();},180);}else{
  target.reviewing=true;buttons[choice].classList.add('is-wrong');buttons[q.correct].classList.add('is-correct');
  const correction=dialog.querySelector('.duel-correction');correction.querySelector('strong').textContent=q.meaning;correction.hidden=false;correction.querySelector('button').focus();
 }
 if(!target.solo&&!sending)setTimeout(()=>{if(session===target&&!target.finished)publish(target).catch(error=>status(error.message));},250);
 if(target.answers.length===m.maxAnswers)finish();
}
function opponent(){if(!session?.room||!dialog?.querySelector('[data-opponent-score]'))return;const other=Object.entries(session.room.players).find(([id])=>id!==session.id);if(!other)return;dialog.querySelector('[data-opponent-name]').textContent=other[1].name;dialog.querySelector('[data-opponent-score]').textContent=m.score(session.pool,session.seed,other[1].answers||[]).total;if(session.opponentId!==other[0]){session.opponentId=other[0];opponentPortrait(session,other[0],other[1]);}}
function tick(){if(!session||session.finished)return;if(uid()!==session.id){closeScreen();return;}const remain=session.start-Date.now();const clock=dialog.querySelector('.duel-clock'),text=remain>0?'開始 '+Math.ceil(remain/1000):String(Math.max(0,Math.ceil((60000+remain)/1000)));if(clock.textContent!==text){clock.textContent=text;dialog.querySelector('.duel-time-track span').style.transform='scaleX('+Math.max(0,Math.min(1,(60000+remain)/60000))+')';}clock.classList.toggle('is-urgent',remain<=-50000&&remain>-60000);dialog.querySelectorAll('.duel-options button').forEach(button=>button.disabled=remain>0||session.reviewing||session.answering);if(remain<=-60000)finish();}
async function publish(target,done=false,abandoned=false){
 if(target.solo)return;const account=target.id;if(uid()!==account)throw Error('アカウントが変更されました。');if(sending)await sending;if(!done&&!abandoned&&published===revision)return;const version=revision,answers=target.answers.slice();const task=window.fbRunTransaction(window.db,async tx=>{const roomRef=ref(target.code),snap=await tx.get(roomRef);if(!snap.exists())return;const room=snap.data(),old=room.players?.[account];if(!old)throw Error('この部屋の参加者ではありません。');if(room.status==='waiting'){if(abandoned&&room.host===account)tx.set(roomRef,{status:'cancelled'},{merge:true});return;}if(room.status!=='playing'||old.done)return;if(answers.length<(old.answers||[]).length)return;m.score(room.pool,room.seed,answers);tx.set(roomRef,{players:{...room.players,[account]:{...old,answers,done,abandoned}}},{merge:true});});sending=task;try{await task;published=version;}finally{if(sending===task)sending=null;}if(!done&&session===target&&revision!==published)await publish(target);
}
async function finish(abandoned=false){
 if(!session||finishing||session.finished)return;finishing=true;clearInterval(timer);const target=session;target.finished=true;clearTimeout(answerTimer);window.WordDuelProgress.flush(target.id).catch(()=>{});dialog.querySelectorAll('.duel-options button,[data-duel-next]').forEach(button=>button.disabled=true);if(target.solo){
  const value=m.score(target.pool,target.seed,target.answers);let saved=null;
  if(!abandoned&&Date.now()>=target.start+60000)saved=window.WordDuelSolo.record(value.total,target.book,target.id);
  const summary=document.createElement('div');summary.className='duel-solo-result';summary.innerHTML='<small></small><strong></strong>';summary.querySelector('small').textContent=saved?.improved?'自己ベスト更新':abandoned?'途中終了':'終了';summary.querySelector('strong').textContent=value.total+'点';dialog.querySelector('.duel-content').prepend(summary);
  dialog.querySelector('.duel-question-card').hidden=true;dialog.querySelector('.duel-options').hidden=true;dialog.querySelector('.duel-correction').hidden=true;
  const message='終了 · '+value.total+'点（一人プレイはレート変更なし）';status(message+(saved?.saved===false?' · 端末に保存できませんでした。':'')+(saved?.improved&&target.id!=='GUEST-000'?' · ベストを同期しています…':''));
  const close=dialog.querySelector('.duel-leave');close.textContent='閉じる';close.onclick=closeScreen;finishing=false;
  if(saved?.improved)(async()=>{let localSaved=saved.saved;try{await window.AppStorage?.flush();}catch{localSaved=false;}const success=await window.WordDuelSolo.sync(target.id);if(session===target){status(message+(!localSaved&&!success?' · 端末への保存が未完了です。':target.id==='GUEST-000'?' · ベストはこの端末に保存':success?' · ベストを保存・同期しました':' · ベストは接続後に再同期します'));dialog.querySelector('[data-opponent-score]').textContent=window.WordDuelSolo.best()??'—';}window.renderLeaderboard?.(false);})();
  return;
 }
 status(abandoned?'退出を保存しています…':'回答を保存しています…');try{await publish(target,true,abandoned);status('相手の終了を確認しています…');await settle(target.code);if(dialog&&session===target){const snap=await window.fbGetDoc(ref(target.code));if(snap.exists()&&snap.data().status==='finished')result(snap.data());else waitingTimer=setTimeout(()=>settle(target.code).catch(error=>status(error.message)),Math.max(7000,target.start+67000-Date.now()));}}catch(error){status('結果の同期が完了していません。'+error.message);const retry=document.createElement('button');retry.type='button';retry.textContent='結果を再確認';retry.onclick=async()=>{try{await publish(target,true,abandoned);await settle(target.code);}catch(e){status(e.message);}};dialog?.querySelector('.duel-content').append(retry);}finally{finishing=false;}
}
async function settle(code){
 connected();const account=uid();return window.fbRunTransaction(window.db,async tx=>{const roomRef=ref(code),snap=await tx.get(roomRef);if(!snap.exists())return;const room=snap.data();if(!m.validRoom(room))throw Error('部屋のデータを確認できません。');if(!room.players?.[account]||!room.guest)throw Error('参加者を確認できません。');if(room.status==='finished'||room.status==='cancelled')return;if(!room.players[room.host].abandoned&&!room.players[room.guest].abandoned&&Date.now()<ms(room.startsAt)+63000)return;const players=room.players,first=players[room.host],second=players[room.guest];if(!first.abandoned&&!second.abandoned&&(!first.done||!second.done)&&Date.now()<ms(room.startsAt)+70000)return;const normalized={...room,players:{[room.host]:{...first,abandoned:first.abandoned||(!first.done&&Date.now()>=ms(room.startsAt)+70000)},[room.guest]:{...second,abandoned:second.abandoned||(!second.done&&Date.now()>=ms(room.startsAt)+70000)}}},win=m.outcome(normalized);if(win===null){tx.set(roomRef,{status:'cancelled'},{merge:true});return;}
 const hostRef=window.fbDoc(window.db,'users',room.host),guestRef=window.fbDoc(window.db,'users',room.guest),a=await tx.get(hostRef),b=await tx.get(guestRef);if(!a.exists()||!b.exists())throw Error('アカウントを確認できません。');const ratings=m.elo(a.data().wordDuelRating,b.data().wordDuelRating,win),scores=[m.score(room.pool,room.seed,first.answers||[]).total,m.score(room.pool,room.seed,second.answers||[]).total];tx.set(hostRef,{wordDuelRating:ratings[0],wordDuelGames:Number(a.data().wordDuelGames||0)+1},{merge:true});tx.set(guestRef,{wordDuelRating:ratings[1],wordDuelGames:Number(b.data().wordDuelGames||0)+1},{merge:true});tx.set(roomRef,{status:'finished',result:{winner:win===.5?'':win===1?room.host:room.guest,ratings:{[room.host]:ratings[0],[room.guest]:ratings[1]},scores:{[room.host]:scores[0],[room.guest]:scores[1]}}},{merge:true});});
}
function result(room){if(!session||!dialog)return;session.finished=true;stop();const mine=session.id,won=room.result.winner;mergeRating({wordDuelRating:room.result.ratings[mine]});const body=dialog.querySelector('.duel-content');body.replaceChildren();const hero=document.createElement('div');hero.className='duel-result-hero';portrait(hero,localStorage.getItem('core_v4_user_avatar_'+mine)||'',myName,window.IconFrames?.equipped());const heading=document.createElement('h3');heading.className='duel-result';heading.textContent=won===mine?'勝利':won?'敗北':'引き分け';const score=document.createElement('p');score.className='duel-result-score';score.textContent=room.result.scores[mine]+'点 · レート '+room.result.ratings[mine];const close=document.createElement('button');close.type='button';close.textContent='閉じる';close.onclick=closeScreen;body.append(hero,heading,score,close);window.renderLeaderboard?.(false);}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&session?.start&&!session.finished)finish(true);});window.addEventListener('pagehide',()=>{window.WordDuelProgress.flush(session?.id).catch(()=>{});if(session&&!session.solo&&!session.finished)publish(session,true,true).catch(()=>{});stop();});
document.addEventListener('keydown',event=>{if(!dialog)return;if(event.key==='Escape'){event.preventDefault();closeScreen();}else if(event.key==='Tab'){const nodes=Array.from(dialog.querySelectorAll('button,input,select')).filter(node=>!node.disabled&&node.getClientRects().length);if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===dialog)){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});
window.WordDuel={localRating,mergeRating,isPlaying:()=>!!session?.start&&!session.finished,settle};window.onAppLoaded(renderRating);
})();
