const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
 const page=await browser.newPage({viewport:{width:393,height:852},deviceScaleFactor:3,userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1',isMobile:true,hasTouch:true}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('crash',()=>errors.push('renderer crashed'));await page.route('https://**/*',r=>r.abort());await page.addInitScript(()=>localStorage.setItem('b3_tutorial_done','1'));
 await page.goto('http://127.0.0.1:8000');await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();
 await page.evaluate(()=>{const key=window.getVocabProgressStorageKey('retained-book');localStorage.setItem(key,JSON.stringify({7:{status:'ok',history:['bad','ok'],note:'保存済み'}}));localStorage.setItem(key+'__ts',String(Date.now()));localStorage.setItem('core_v4_profile_shop_owned_GUEST-000',JSON.stringify(['wood','retained-purchase']));window.__retainedRuntime={state:42};});
 const admin=page.frameLocator('#productManagerDialog iframe');
 const originalUrl=page.url(),password=fs.readFileSync('admin-access.js','utf8').match(/value!=='([^']+)'/)[1];
 await page.getByRole('button',{name:'プロフィール商品管理'}).click();
 const auth=page.frameLocator('#productAccessDialog iframe');await auth.locator('#password').waitFor({state:'visible'});
 assert.equal(await auth.locator('#password').getAttribute('type'),'password');assert.equal(await auth.locator('#keys,output').count(),0);assert.equal(await auth.locator('script').count(),1);
 assert.equal(await auth.locator('#password').evaluate(el=>getComputedStyle(el).fontSize),'16px');
 await page.evaluate(()=>{Object.defineProperty(visualViewport,'height',{configurable:true,get:()=>430});Object.defineProperty(visualViewport,'offsetTop',{configurable:true,get:()=>48});visualViewport.dispatchEvent(new Event('resize'));});await page.waitForFunction(()=>document.querySelector('#productAccessDialog').style.maxHeight==='406px');const box=await page.locator('#productAccessDialog').boundingBox();assert.ok(box.y>=12&&box.y+box.height<=430);await page.evaluate(()=>{delete visualViewport.height;delete visualViewport.offsetTop;visualViewport.dispatchEvent(new Event('resize'));});
 for(let i=0;i<5;i++){await auth.locator('#password').fill('wrong-pass');await auth.getByRole('button',{name:'認証',exact:true}).click();assert.equal(await auth.locator('#error').textContent(),'パスワードが違います。');assert.equal(page.url(),originalUrl);}
 await page.evaluate(()=>window.postMessage({type:'aiglish-admin-access',nonce:JSON.parse(sessionStorage.getItem('aiglish_admin_access_pending')).nonce,verified:true},location.origin));
 assert.equal(await page.locator('#productAccessDialog').count(),1,'another window cannot forge an auth completion');
 await auth.locator('#password').fill(password);await auth.getByRole('button',{name:'認証',exact:true}).click();
 await admin.locator('#shopAdd').waitFor({state:'visible',timeout:10000});assert.equal(page.url(),originalUrl);assert.equal(await page.evaluate(()=>__retainedRuntime.state),42);
 assert.equal(await page.locator('#auth-gate-screen').isVisible(),false);assert.equal(await page.locator('#productAccessDialog').count(),0);
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(window.getVocabProgressStorageKey('retained-book')))[7].status),'ok');assert.ok(await page.evaluate(()=>window.ProfileShop.owned().includes('retained-purchase')));assert.equal(await page.evaluate(()=>sessionStorage.getItem('aiglish_admin_access_ticket')),null);
 await admin.getByRole('button',{name:'ホームへ',exact:true}).click();await page.getByRole('button',{name:'プロフィール商品管理'}).click();await admin.locator('#shopAdd').waitFor({state:'visible'});assert.equal(await page.locator('#productAccessDialog').count(),0,'valid administrator session avoids repeated password prompts');
 await admin.getByRole('button',{name:'ホームへ',exact:true}).click();
 await page.route('**/product-admin.html?*',route=>route.fulfill({status:404,contentType:'text/html',body:'<!doctype html><p>Not found</p>'}));
 await page.getByRole('button',{name:'プロフィール商品管理'}).click();await page.locator('#adminHub').getByText('商品管理を読み込めませんでした。',{exact:true}).waitFor({state:'visible'});
 assert.equal(await page.locator('#productManagerDialog').count(),0);assert.equal(await page.evaluate(()=>document.body.classList.contains('password-prompt-open')),false);assert.equal(page.url(),originalUrl);
 await page.unroute('**/product-admin.html?*');await page.evaluate(()=>window.switchTab('home'));await page.getByRole('button',{name:'プロフィール商品管理'}).click();await admin.locator('#shopAdd').waitFor({state:'visible'});
 await admin.getByRole('button',{name:'ホームへ',exact:true}).click();await page.evaluate(()=>window.isAdmin=false);await page.getByRole('button',{name:'プロフィール商品管理'}).click();await auth.locator('#password').waitFor({state:'visible'});await auth.getByRole('button',{name:'戻る',exact:true}).click();await page.locator('#productAccessDialog').waitFor({state:'detached'});
 assert.equal(await page.locator('#productAccessDialog').count(),0);assert.equal(page.url(),originalUrl);assert.equal(await page.evaluate(()=>sessionStorage.getItem('aiglish_admin_access_pending')),null);assert.equal(await page.evaluate(()=>document.body.classList.contains('password-prompt-open')),false);assert.equal(await page.evaluate(()=>window.isAdmin),false);
 assert.deepEqual(errors,[]);console.log('PASS: native password field, wrong/cancel paths, source-checked iframe messages, no reload/login transition, retained runtime/learning/purchases and direct return to product manager');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
