const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict');
(async()=>{
 const type=process.env.BROWSER==='webkit'?webkit:chromium;
 const browser=await type.launch(type===chromium?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:{executablePath:process.env.WEBKIT_EXECUTABLE_PATH});
 try{
  const page=await browser.newPage({viewport:{width:393,height:852},deviceScaleFactor:3,userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Mobile Safari/604.1'}),errors=[];
  page.on('pageerror',error=>errors.push(error.message));page.on('crash',()=>errors.push('renderer crashed'));await page.route('https://**/*',r=>r.abort());
  await page.addInitScript(()=>{Object.defineProperty(navigator,'standalone',{value:true});window.__livePhotoUrls=new Set();window.__urlCreates=0;const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);URL.createObjectURL=blob=>{const url=create(blob);__urlCreates++;__livePhotoUrls.add(url);return url;};URL.revokeObjectURL=url=>{__livePhotoUrls.delete(url);revoke(url);};});
  await page.goto('http://127.0.0.1:8000');await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.waitForFunction(()=>window.__learningBootReady===true);
  await page.evaluate(()=>{localStorage.setItem(getVocabProgressStorageKey('retained-background-test'),JSON.stringify({1:{status:'ok',note:'保持'},2:{status:'bad'}}));toggleSidebar(true);});
  const openAdmin=async()=>{await page.evaluate(()=>toggleSidebar(true));await page.locator('#sidebarBackgroundAdmin').click();await page.locator('#backgroundAdminPassword').fill('tukinokopanda');await page.locator('#backgroundAdminAuth button').click();};
  await openAdmin();assert.equal(await page.locator('#backgroundAdminName').count(),0);assert.equal(await page.locator('#backgroundAdminRegister').textContent(),'登録する');
  // Oversized compressed camera headers never reach a browser image decoder.
  const large=Buffer.alloc(32);Buffer.from([137,80,78,71,13,10,26,10]).copy(large);large.write('IHDR',12);large.writeUInt32BE(8064,16);large.writeUInt32BE(6048,20);
  await page.locator('#sidebarBackgroundFile').setInputFiles({name:'48mp.png',mimeType:'image/png',buffer:large});const beforeDecode=await page.evaluate(()=>__urlCreates);await page.locator('#backgroundAdminRegister').click();await page.locator('#backgroundAdminSaveStatus').filter({hasText:'1300万画素'}).waitFor();assert.equal(await page.evaluate(()=>__urlCreates),beforeDecode);assert.equal(await page.locator('#backgroundAdminSelection option').count(),0);
  const fixture=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=1280;c.height=720;c.getContext('2d').fillRect(0,0,1280,720);return c.toDataURL('image/png').split(',')[1];});
  await page.locator('#sidebarBackgroundFile').setInputFiles({name:'photo.png',mimeType:'image/png',buffer:Buffer.from(fixture,'base64')});assert.equal(await page.locator('#backgroundAdminSelection option').count(),0);assert.match(await page.locator('#backgroundAdminSaveStatus').textContent(),/「登録する」/);
  // Registration has a visible pending state and acknowledges only durable completion.
  await page.evaluate(()=>{const original=AppStorage.flush;AppStorage.flush=()=>new Promise(resolve=>{window.__finishPhotoFlush=async()=>{AppStorage.flush=original;await original();resolve();};});});
  await page.locator('#backgroundAdminRegister').click();await page.locator('#backgroundAdminSaveStatus').filter({hasText:'保存しています'}).waitFor();assert.equal(await page.locator('#backgroundAdminRegister').isDisabled(),true);assert.equal(await page.locator('#backgroundAdminRegister').textContent(),'登録中…');assert.equal(await page.locator('#backgroundAdminSelection option').count(),0);await page.evaluate(()=>__finishPhotoFlush());await page.locator('#backgroundAdminSaveStatus').filter({hasText:'写真を登録しました（合計1枚）'}).waitFor();assert.equal(await page.locator('#backgroundAdminSelection option').count(),1);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('aiglish_app_background_'+myId)).mode),'default');
  // A failed confirmation can be retried without decoding again or registering duplicates.
  await page.locator('#sidebarBackgroundFile').setInputFiles({name:'retry.png',mimeType:'image/png',buffer:Buffer.from(fixture,'base64')});await page.evaluate(()=>{window.__realPhotoFlush=AppStorage.flush;AppStorage.flush=()=>Promise.reject(Error('controlled storage failure'));});await page.locator('#backgroundAdminRegister').click();await page.locator('#backgroundAdminSaveStatus').filter({hasText:'保存できませんでした'}).waitFor();assert.equal(await page.locator('#backgroundAdminSelection option').count(),1);await page.evaluate(()=>AppStorage.flush=__realPhotoFlush);await page.locator('#backgroundAdminRegister').click();await page.locator('#backgroundAdminSaveStatus').filter({hasText:'写真を登録しました（合計2枚）'}).waitFor();assert.equal(await page.locator('#backgroundAdminSelection option').count(),2);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('aiglish_app_background_catalog_'+myId)).backgrounds.length),2);
  // A cancelled image task must not disable the next administrator session or save late.
  await page.evaluate(()=>{window.__realPhotoDecode=ProfileImages.imageFile;ProfileImages.imageFile=(...args)=>new Promise((resolve,reject)=>{window.__finishCancelledDecode=()=>__realPhotoDecode(...args).then(resolve,reject);});});await page.locator('#sidebarBackgroundFile').setInputFiles({name:'cancel.png',mimeType:'image/png',buffer:Buffer.from(fixture,'base64')});await page.locator('#backgroundAdminRegister').click();await page.waitForFunction(()=>!!window.__finishCancelledDecode);await page.locator('#backgroundAdminClose').click();await page.locator('#backgroundAdminDialog').waitFor({state:'detached'});await openAdmin();await page.evaluate(()=>{ProfileImages.imageFile=__realPhotoDecode;__finishCancelledDecode();});await page.waitForTimeout(30);assert.equal(await page.locator('#sidebarBackgroundFile').isDisabled(),false);assert.equal(await page.locator('#backgroundAdminSelection option').count(),2);await page.locator('#backgroundAdminClose').click();
  await page.evaluate(()=>{const backgrounds=[];for(let i=0;i<12;i++){const c=document.createElement('canvas');c.width=960;c.height=540;const ctx=c.getContext('2d');ctx.fillStyle='hsl('+i*30+' 70% 40%)';ctx.fillRect(0,0,960,540);ctx.fillStyle='white';ctx.font='80px sans-serif';ctx.fillText(String(i),80,140);const image=c.toDataURL('image/jpeg',.6);c.width=320;c.height=180;ctx.fillStyle='hsl('+i*30+' 70% 40%)';ctx.fillRect(0,0,320,180);backgrounds.push({id:'budget-'+i,image,preview:c.toDataURL('image/jpeg',.5),position:30});}localStorage.setItem('aiglish_app_background_catalog_'+myId,JSON.stringify({backgrounds,updatedAt:Date.now()}));localStorage.setItem('aiglish_app_background_'+myId,JSON.stringify({mode:'photo',selected:'budget-0',updatedAt:Date.now()}));toggleSidebar(true);toggleSidebar(false);});
  const session=type===chromium?await page.context().newCDPSession(page):null;
  if(session){await session.send('Performance.enable');await session.send('HeapProfiler.collectGarbage');}
  const heap=async()=>session?Object.fromEntries((await session.send('Performance.getMetrics')).metrics.map(m=>[m.name,m.value])).JSHeapUsedSize:0;
  const beforeHeap=await heap();let maximumSources=0;
  for(let round=0;round<12;round++){
   await page.locator('#headerBackgroundButton').click();assert.equal(await page.locator('.background-preview').count(),13);assert.equal(await page.locator('.background-preview span').count(),0);
   for(const index of [0,6,11]){
    const button=page.locator('[data-background="budget-'+index+'"]');await button.scrollIntoViewIfNeeded();await button.click();await page.locator('#backgroundPickerStatus').filter({hasText:'背景を保存しました'}).waitFor();await page.waitForTimeout(40);
    const sources=await page.locator('.background-preview img[src]').count();maximumSources=Math.max(maximumSources,sources);assert.ok(sources<=3);assert.ok(await page.evaluate(()=>__livePhotoUrls.size)<=4);
   }
   await page.locator('#backgroundPickerClose').click();await page.locator('#backgroundPickerDialog').waitFor({state:'detached'});assert.equal(await page.locator('.background-preview img').count(),0);assert.equal(await page.evaluate(()=>__livePhotoUrls.size),1);
   // Native password field can reopen and accept edits repeatedly without touching the gallery.
   await openAdmin();assert.equal(await page.locator('#backgroundAdminSelection option').count(),12);await page.locator('#backgroundAdminClose').click();
   await page.evaluate(()=>{for(const tab of ['vocab','reader','study','titles','vocab'])switchTab(tab);});
  }
  if(session)await session.send('HeapProfiler.collectGarbage');const growth=await heap()-beforeHeap;assert.ok(growth<8*1024*1024,'unbounded retained heap: '+growth);
  const beforeHide=await page.evaluate(()=>localStorage.getItem('aiglish_app_background_'+myId));await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await page.evaluate(()=>__livePhotoUrls.size),0);assert.equal(await page.evaluate(()=>localStorage.getItem('aiglish_app_background_'+myId)),beforeHide);await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await page.evaluate(()=>__livePhotoUrls.size),1);
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(getVocabProgressStorageKey('retained-background-test')))[1].status),'ok');// Recovery remains across a clean reload until an explicit photo choice, without erasing saved artwork.
  await page.addInitScript(()=>{if(localStorage.getItem('__force_photo_crash_once')){localStorage.setItem('__aiglish_render_guard',JSON.stringify({active:true,at:Date.now()}));localStorage.removeItem('__force_photo_crash_once');}});
  await page.evaluate(()=>localStorage.setItem('__force_photo_crash_once','1'));await page.reload();await page.waitForFunction(()=>window.__learningBootReady===true);assert.equal(await page.locator('html').evaluate(el=>el.classList.contains('pwa-recovery-rendering')),true);assert.equal(await page.evaluate(()=>__livePhotoUrls.size),0);
  await page.reload();await page.waitForFunction(()=>window.__learningBootReady===true);assert.equal(await page.locator('html').evaluate(el=>el.classList.contains('pwa-recovery-rendering')),true);assert.equal(await page.evaluate(()=>__livePhotoUrls.size),0);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('aiglish_app_background_catalog_'+myId)).backgrounds.length),12);
  await page.locator('#headerBackgroundButton').click();const restore=page.locator('[data-background="budget-11"]');await restore.scrollIntoViewIfNeeded();await restore.click();await page.locator('#backgroundPickerStatus').filter({hasText:'背景を保存しました'}).waitFor();assert.equal(await page.locator('html').evaluate(el=>el.classList.contains('pwa-recovery-rendering')),false);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('__aiglish_render_guard')).recovery),false);await page.locator('#backgroundPickerClose').click();
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(getVocabProgressStorageKey('retained-background-test')))[1].status),'ok');assert.deepEqual(errors,[]);
  console.log(JSON.stringify({result:'PASS '+type.name()+': DPR3 PWA; explicit durable registration; oversized photos rejected before decode; 12-photo gallery/36 switches/12 admin opens/60 tab changes; bounded image sources and revoked URLs; hidden-page release; learning retained',maximumSources,heapGrowth:session?growth:'not available in WebKit'}));
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exit(1);});
