const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const type=process.env.BROWSER==='webkit'?webkit:chromium,browser=await type.launch(type===chromium?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:{executablePath:process.env.WEBKIT_EXECUTABLE_PATH});try{
 const page=await browser.newPage({viewport:{width:393,height:852}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());await page.addInitScript(()=>localStorage.setItem('aiglish_sound_settings',JSON.stringify({enabled:false})));await page.goto('http://127.0.0.1:8000');await page.waitForFunction(()=>window.IconFrames);await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.waitForFunction(()=>window.__learningBootReady===true);
 await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=32;canvas.getContext('2d').fillRect(0,0,32,32);localStorage.setItem('core_v4_user_avatar_'+myId,canvas.toDataURL());window.applyProfileToUi();window.__originalFrameSnapshot=StudyTime.snapshot;window.__frameSeconds=0;window.StudyTime.snapshot=()=>({version:1,epoch:'study-reset-2.62',days:{},offset:__frameSeconds*1000});});
 await page.locator('.menu-trigger').click();await page.locator('#profileMenuButton').click();assert.equal(await page.locator('.frame-option').count(),8);await page.waitForFunction(()=>[...document.querySelectorAll('.frame-example img')].every(img=>img.complete&&img.naturalWidth>0));assert.equal(await page.locator('.frame-example img').count(),8);
 const thresholds=await page.evaluate(()=>IconFrameCatalog.map(f=>f.seconds));assert.deepEqual(thresholds,[600,3600,18000,72000,180000,360000,900000,1800000]);
 for(let i=0;i<thresholds.length;i++){const checks=await page.evaluate(({i,seconds})=>{__frameSeconds=seconds-1;const below=IconFrames.unlocked(IconFrameCatalog[i].id);__frameSeconds=seconds;return {below,at:IconFrames.unlocked(IconFrameCatalog[i].id)};},{i,seconds:thresholds[i]});assert.deepEqual(checks,{below:false,at:true});}
 await page.evaluate(()=>{__frameSeconds=1800000;IconFrames.render();});
 const assets=await page.evaluate(async()=>{const results=[];for(const frame of IconFrameCatalog){const image=new Image();image.src='assets/frames/'+frame.id+'.webp';await image.decode();const canvas=document.createElement('canvas');canvas.width=canvas.height=384;const ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);results.push({width:image.naturalWidth,center:ctx.getImageData(192,192,1,1).data[3]});}return results;});for(const asset of assets){assert.equal(asset.width,384);assert.equal(asset.center,0);}
 await page.getByRole('button',{name:'ブラックダイヤのフレーム（解放済み）',exact:true}).click();await page.locator('#profileFrameAction').click();await page.getByText('フレームを装備しました。',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>UserProfile.read().frame),'black-diamond');
 await page.getByRole('button',{name:'木のフレーム（解放済み）',exact:true}).click();await page.locator('#profileFrameAction').click();await page.getByText('フレームを装備しました。',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>UserProfile.read().frame),'wood');assert.equal(await page.locator('#profileAvatarPreview>.frame-wood').count(),1);assert.equal(await page.locator('#sidebarIdentityAvatar>.frame-wood').count(),1);assert.equal(await page.locator('#sidebarIdentityAvatar>img').count(),1);assert.equal(await page.locator('#sidebarIdentityName').innerText(),'ゲストプレイヤー');
 assert.equal(await page.locator('#mailboxMenuButton,[data-wallet-balance],[data-ranking-period]').count(),0);
 const shared=await page.evaluate(()=>RankingVisuals.avatar('','人',JSON.stringify({frame:'wood'})).querySelector('.frame-wood')!==null);assert.equal(shared,true);
 await page.evaluate(async()=>{const account=myId,photo=localStorage.getItem('core_v4_user_avatar_'+account);myId='frame-ranking-test';window.db={};window.fbCollection=()=>'';const first=LearningRankingModel.empty();first.words.a=1;first.flash.sources.other=2;window.fbGetDocs=async()=>({forEach:fn=>fn({id:'framed-friend',data:()=>({playerName:'枠付き友達',avatar:photo,profileCustomizationJson:JSON.stringify({frame:'gold'}),learningRankingV2Json:JSON.stringify(first)})})});await LearningRanking.refresh(true);myId=account;});assert.equal(await page.locator('[data-podium-metric=flash] .frame-gold').count(),1);
 assert.equal(await page.locator('.frame-option').filter({hasText:'犬'}).count(),0);await page.getByRole('button',{name:'プロフィールを閉じる',exact:true}).click();await page.setViewportSize({width:320,height:720});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
 await page.evaluate(()=>{StudyTime.snapshot=__originalFrameSnapshot;StudyTime.mergeCloud({version:1,epoch:'study-reset-2.62',days:{},offset:1800000000,updatedAt:Date.now()});});await page.reload();await page.waitForFunction(()=>window.__learningBootReady===true);assert.equal(await page.evaluate(()=>UserProfile.read().frame),'wood');assert.equal(await page.evaluate(()=>IconFrames.equipped()),'wood');
 console.log('PASS '+type.name()+': eight study-time thresholds; exact unlock boundaries; lower-frame equipment and reload persistence; transparent assets; shared decoration; coins/mail/weekly UI absent; 320px layout');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
