const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const type=process.env.BROWSER==='webkit'?webkit:chromium,browser=await type.launch(type===chromium?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:{executablePath:process.env.WEBKIT_EXECUTABLE_PATH});try{
 const page=await browser.newPage({viewport:{width:393,height:852}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());await page.addInitScript(()=>localStorage.setItem('aiglish_sound_settings',JSON.stringify({enabled:false})));await page.goto('http://127.0.0.1:8000');await page.waitForFunction(()=>window.IconFrames);await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.waitForFunction(()=>window.__learningBootReady===true);
 await page.evaluate(()=>{myId='frame-test';userStats={gold:100000};window.__frameDoc={userStats:{gold:100000},profileCustomizationJson:JSON.stringify({updatedAt:1,nickname:'フレーム',nameColor:'#ffeeaa',loadingQuiz:{bookId:'quiz'},other:'preserve'})};window.db={};window.fbDoc=(db,...path)=>path.join('/');window.fbRunTransaction=async(_,fn)=>fn({get:async()=>({exists:()=>true,data:()=>structuredClone(__frameDoc)}),set:(ref,fields)=>Object.assign(__frameDoc,structuredClone(fields))});});
 await page.locator('.menu-trigger').click();await page.locator('#profileMenuButton').click();assert.equal(await page.locator('.frame-option').count(),8);assert.deepEqual(await page.locator('.frame-option>span:not(.frame-example)').allTextContents(),['木','石','銅','銀','金','ダイヤ','プラチナ','ブラックダイヤ']);
 await page.getByRole('button',{name:'石のフレーム 500コイン',exact:true}).click();assert.equal(await page.locator('#profileFrameAction').isDisabled(),true);
 for(const [name,cost] of [['木',100],['石',500],['銅',2500],['銀',12500]]){await page.getByRole('button',{name:name+'のフレーム '+cost.toLocaleString('ja-JP')+'コイン',exact:true}).click();await page.locator('#profileFrameAction').click();await page.getByText('購入して装備しました。',{exact:true}).waitFor();}
 assert.equal(await page.evaluate(()=>LearningRewardsModel.balance(LearningWallet.read())),84400);await page.getByRole('button',{name:'木のフレーム（購入済み）',exact:true}).click();await page.locator('#profileFrameAction').click();await page.getByText('フレームを装備しました。',{exact:true}).waitFor();assert.equal(await page.locator('#profileAvatarPreview>.frame-wood').count(),1);assert.equal(await page.locator('#profileFrameAction').textContent(),'装備中');
 const shared=await page.evaluate(()=>{const profile=JSON.parse(__frameDoc.profileCustomizationJson),avatar=RankingVisuals.avatar('','人',__frameDoc.profileCustomizationJson);return {frame:profile.frame,other:profile.other,quiz:profile.loadingQuiz.bookId,decoration:avatar.querySelector('.frame-wood')!==null,owned:IconFrameCatalog.slice(0,4).every(f=>LearningRewardsModel.owned(LearningWallet.read(),f.id))};});assert.deepEqual(shared,{frame:'wood',other:'preserve',quiz:'quiz',decoration:true,owned:true});
 assert.equal(await page.locator('.frame-option').filter({hasText:'犬'}).count(),0);await page.getByRole('button',{name:'プロフィールを閉じる',exact:true}).click();await page.setViewportSize({width:320,height:720});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
 console.log('PASS '+type.name()+': eight ordered material frames; sequential prices/charges; no skipping; retained lower-grade equipment; shared avatar decoration; profile/quiz preserved; dog excluded; 320px layout');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
