const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const type=process.env.BROWSER==='webkit'?webkit:chromium,browser=await type.launch(type===chromium?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:{executablePath:process.env.WEBKIT_EXECUTABLE_PATH});try{
const page=await browser.newPage({viewport:{width:393,height:852}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());await page.addInitScript(()=>localStorage.setItem('aiglish_sound_settings',JSON.stringify({enabled:false})));
await page.clock.install();await page.goto('http://127.0.0.1:8000');await page.waitForFunction(()=>window.IdleSleep);await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.waitForFunction(()=>window.__learningBootReady===true);await page.locator('#nav-study').click();await page.getByRole('button',{name:'開始',exact:true}).click();await page.waitForTimeout(100);
await page.evaluate(()=>{StudyTime.mergeCloud({version:1,epoch:'study-reset-2.62',days:{},offset:3600000});window.__sleepSaves=0;window.__backgroundSaveAll=async()=>{__sleepSaves++;return {cloudSaved:true};};IdleSleep.activity();});await page.waitForTimeout(100);
const before=await page.evaluate(()=>StudyTimeModel.total(StudyTime.snapshot()));await page.clock.runFor(300000);assert.equal(await page.locator('#idleSleepWarning').count(),1);assert.match(await page.locator('#idleSleepWarning').innerText(),/あと10秒/);assert.ok(await page.evaluate(()=>StudyTimeModel.total(StudyTime.snapshot()))-before>290000,'active timer actually accrued before deduction');await page.clock.runFor(10000);await page.waitForFunction(()=>window.__sleepSaves===1);assert.equal(await page.locator('#idleSleepOverlay').count(),1);
const asleep=await page.evaluate(()=>StudyTimeModel.total(StudyTime.snapshot()));assert.ok(asleep>=3600000,'historical time retained');assert.ok(asleep-before<12000,'only the warning interval remains; inactive measured time removed');await page.clock.runFor(60000);assert.equal(await page.evaluate(()=>StudyTimeModel.total(StudyTime.snapshot())),asleep);assert.equal(await page.evaluate(()=>__sleepSaves),1);
await page.getByRole('button',{name:'タップして再開'}).click();assert.equal(await page.locator('#idleSleepOverlay').count(),0);await page.waitForTimeout(100);await page.clock.runFor(10000);assert.ok(await page.evaluate(()=>StudyTimeModel.total(StudyTime.snapshot()))>asleep);
await page.clock.runFor(290000);assert.equal(await page.locator('#idleSleepWarning').count(),1);await page.locator('.menu-trigger').click();assert.equal(await page.locator('#idleSleepWarning').count(),0);await page.clock.runFor(11000);assert.equal(await page.locator('#idleSleepOverlay').count(),0);
await page.locator('#profileMenuButton').click();assert.equal(await page.locator('.frame-option.is-locked').count(),6);await page.getByRole('button',{name:'金のフレーム（50時間で解放）',exact:true}).click();assert.equal(await page.locator('#profileAvatarPreview.frame-preview-locked').count(),1);assert.equal(await page.locator('.frame-option.is-locked .icon-frame-art').first().evaluate(el=>getComputedStyle(el).opacity),'0.1');await page.clock.fastForward(310000);await page.waitForFunction(()=>__sleepSaves===2);assert.equal(await page.locator('#idleSleepOverlay').evaluate(el=>el.matches(':modal')),true);await page.getByRole('button',{name:'タップして再開'}).click();await page.getByRole('button',{name:'プロフィールを閉じる'}).click();await page.locator('.menu-trigger').click();await page.locator('#usageGuideEntryBtn').click();assert.equal(await page.locator('#usageGuideOverlay .ug-acc').count(),10);assert.match(await page.locator('#usageGuideOverlay').innerText(),/スリープ/);assert.match(await page.locator('#usageGuideOverlay').textContent(),/500時間/);assert.deepEqual(errors,[]);
console.log('PASS '+type.name()+': 5-minute warning, 10-second sleep, one save, measured idle-only deduction, historical time retained, pause/wake, warning cancellation, detailed current guide');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
