const assert=require('node:assert/strict'),test=require('node:test');require('../image-metadata.js');
const png=(width,height)=>{const b=new Uint8Array(32),v=new DataView(b.buffer);b.set([137,80,78,71,13,10,26,10]);b.set([73,72,68,82],12);v.setUint32(16,width);v.setUint32(20,height);return b.buffer;};
test('PNG dimensions and standard 12MP camera photos remain accepted',async()=>{assert.deepEqual(ImageMetadata.dimensions(png(4032,3024)),{width:4032,height:3024});assert.deepEqual(await ImageMetadata.inspect(new Blob([png(4032,3024)])),{width:4032,height:3024});});
test('compressed oversized images are rejected before browser decoding',async()=>{await assert.rejects(ImageMetadata.inspect(new Blob([png(8064,6048)])),/1300万画素/);await assert.rejects(ImageMetadata.inspect(new Blob([png(20000,20)])),/1300万画素/);});
test('unknown, truncated and zero-sized headers never enter the decoder',async()=>{for(const header of [new ArrayBuffer(0),new Uint8Array([255,216,255,192,255,255]).buffer,png(0,100)])await assert.rejects(ImageMetadata.inspect(new Blob([header])),/サイズを確認/);});
test('JPEG segments with EXIF and a progressive frame preserve dimensions',()=>{const b=new Uint8Array([255,216,255,225,0,4,1,2,255,194,0,8,8,0,100,0,200,1]);assert.deepEqual(ImageMetadata.dimensions(b.buffer),{width:200,height:100});});
test('WebP extended, lossless and lossy dimension headers are recognized',()=>{for(const type of ['VP8X','VP8L','VP8 ']){const b=new Uint8Array(32),v=new DataView(b.buffer);b.set(Buffer.from('RIFF'),0);b.set(Buffer.from('WEBP'),8);b.set(Buffer.from(type),12);if(type==='VP8X'){b[24]=99;b[27]=49;}else if(type==='VP8L'){b[20]=47;v.setUint32(21,99|(49<<14),true);}else{b.set([157,1,42],23);v.setUint16(26,100,true);v.setUint16(28,50,true);}assert.deepEqual(ImageMetadata.dimensions(b.buffer),{width:100,height:50});}});
test('GIF dimensions are checked before decoded-frame allocation',()=>{const b=new Uint8Array(10),v=new DataView(b.buffer);b.set(Buffer.from('GIF89a'));v.setUint16(6,100,true);v.setUint16(8,50,true);assert.deepEqual(ImageMetadata.dimensions(b.buffer),{width:100,height:50});});
test('nested HEIC properties use the largest image dimensions, including oversized primary images',async()=>{const box=(type,...parts)=>{const result=Buffer.concat([Buffer.alloc(8),...parts]);result.writeUInt32BE(result.length);result.write(type,4);return result;},ispe=(width,height)=>{const bytes=Buffer.alloc(12);bytes.writeUInt32BE(width,4);bytes.writeUInt32BE(height,8);return box('ispe',bytes);};const data=Buffer.concat([box('ftyp',Buffer.from('heic')),box('meta',Buffer.alloc(4),box('iprp',box('ipco',ispe(512,512),ispe(8064,6048))))]);await assert.rejects(ImageMetadata.inspect(new Blob([data])),/1300万画素/);});
