const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:390,height:844},timezoneId:'Asia/Tokyo'});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',dialog=>dialog.accept());await page.route('https://**/*',route=>route.abort());await page.addInitScript(()=>localStorage.setItem('b3_tutorial_done','1'));await page.goto('http://127.0.0.1:8000',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.LearningRanking);await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();
await page.evaluate(()=>{
 window.__gcLoginShown=true;document.querySelectorAll('.gcModal').forEach(el=>el.remove());myId='rank-self';myName='自分 太郎';userStats={flash_count:4};currentTextbook='rank-book';vocabList=[{num:1,word:'a',meanings:[{id:'a',status:'none'}]},{num:2,word:'b',meanings:[{id:'b',status:'none'}]}];
 localStorage.setItem('core_v4_user_vocab_progress_rank-self_old-book',JSON.stringify({1:{meanings:{x:{status:'bad'}}}}));
 window.db={};window.fbCollection=(_, ...parts)=>parts.join('/');window.fbDoc=(_, ...parts)=>parts.join('/');const today=window.StudyTimeModel.dateKey(Date.now());
 const avatar='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aYaQAAAAASUVORK5CYII=';
 const stats=(time,words,flash)=>({study_calendar_v2:{version:1,epoch:'study-reset-2.62',offset:0,days:{[today]:{sources:{test:time*1000}}}},learning_ranking:{version:1,words:Object.fromEntries(Array.from({length:words},(_,i)=>['word'+i,1])),flash:{baseline:flash,sources:{}}}});
 window.__rankingDocs={a:{playerName:'青木 一郎',avatar,userStats:null,stats:stats(7200,20,30)},b:{playerName:'田中 次郎',avatar,userStats:{...stats(3600,40,10),study_calendar_v2:undefined,study_total_secs:3600,study_today_secs:3600,study_today_date:today}},c:{playerName:'山田 三郎',avatar,userStats:stats(600,10,50)},old:{playerName:'旧時間',userStats:{study_total_secs:999999,study_calendar_v2:{epoch:'old'}}},'rank-self':{playerName:myName,userStats:{}}};
 window.fbGetDocs=async()=>({forEach:fn=>Object.entries(window.__rankingDocs).forEach(([id,doc])=>fn({id,data:()=>doc}))});window.fbGetDoc=async ref=>({exists:()=>true,data:()=>window.__rankingDocs[ref.split('/')[1]]||{}});window.fbSetDoc=async()=>{};window.fbSetDocWithRetry=async()=>{};
 window.fbRunTransaction=async(_,fn)=>fn({get:async ref=>({exists:()=>true,data:()=>window.__rankingDocs[ref.split('/')[1]]||{}}),set:(ref,change)=>Object.assign(window.__rankingDocs[ref.split('/')[1]],change)});
 window.StudyTime.init();window.syncRankingMetrics();
});
assert.equal(await page.evaluate(()=>userStats.vocab_rated_count),1);await page.evaluate(()=>{window.recordRankedWord('rank-book',1);window.recordRankedWord('rank-book',1);window.recordRankedSwipe();window.recordRankedSwipe();});assert.equal(await page.evaluate(()=>userStats.vocab_rated_count),2);assert.equal(await page.evaluate(()=>userStats.flash_count),6);
await page.locator('#nav-titles').click();await page.locator('[data-podium-metric="time"] .place-1 .podium-name').waitFor();assert.equal(await page.locator('[data-podium-metric="time"] .place-1 .podium-name').textContent(),'青木一郎');assert.equal(await page.locator('[data-podium-metric="time"] .place-1 .podium-name br').count(),1);assert.equal(await page.locator('#rankingPodium img').count(),9);assert.equal(await page.locator('#titles-list, #titlesCollection, #sideSelectTitle, #profTitleLabel').count(),0);assert.match(await page.locator('#nav-titles').textContent(),/ランキング/);
await page.getByRole('button',{name:'合計勉強時間 1位 青木 一郎の詳細'}).click();assert.equal(await page.locator('dialog').isVisible(),true);assert.deepEqual(await page.locator('dialog dd').allTextContents(),['2時間0分','20語','30回']);await page.getByRole('button',{name:'閉じる',exact:true}).click();
assert.equal(await page.locator('[data-podium-metric="words"] .place-1 .podium-name').textContent(),'田中次郎');assert.equal(await page.locator('[data-podium-metric="flash"] .place-1 .podium-name').textContent(),'山田三郎');
const stable=await page.evaluate(()=>{const podium=document.querySelector('[data-podium-metric="time"] .place-1');window.__stablePodium=podium;for(let i=0;i<10;i++)window.LearningRanking.render();userStats.study_calendar_v2.days[window.StudyTimeModel.dateKey(Date.now())]={sources:{self:1000}};window.LearningRanking.render();return window.__stablePodium===document.querySelector('[data-podium-metric="time"] .place-1');});assert.equal(stable,true);
for(const viewport of [{width:390,height:844},{width:320,height:568}]){await page.setViewportSize(viewport);await page.waitForTimeout(400);const bounds=await page.evaluate(()=>{const stage=document.querySelector('.ranking-stage'),hint=document.querySelector('.ranking-hint'),host=document.querySelector('#view-titles');return{end:hint.getBoundingClientRect().bottom,bottom:host.getBoundingClientRect().bottom,overflow:stage.scrollHeight>stage.clientHeight+2,width:document.documentElement.scrollWidth>innerWidth};});assert.ok(bounds.end<=bounds.bottom+1,JSON.stringify(bounds));assert.equal(bounds.overflow,false);assert.equal(bounds.width,false);assert.equal(await page.locator('.ranking-mini-panel').evaluateAll(panels=>panels.every(panel=>Array.from(panel.querySelectorAll('.learning-podium-place')).every(column=>column.getBoundingClientRect().bottom<=panel.getBoundingClientRect().bottom))),true);}
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/learning-ranking.png'});
await page.locator('#nav-study').click();await page.locator('#studyFriendRanking .place-1 .study-podium-name').waitFor();assert.equal(await page.locator('#studyFriendRanking .place-1 .study-podium-name br').count(),1);assert.equal(await page.locator('#studyFriendRanking img').count(),3);await page.locator('#studyFriendRanking .place-1').click();assert.equal(await page.locator('dialog dd').first().textContent(),'2時間0分');await page.getByRole('button',{name:'閉じる',exact:true}).click();
await page.evaluate(async()=>{await window.saveUserStats();});assert.equal(await page.evaluate(()=>window.LearningRankingModel.flashCount(JSON.parse(window.__rankingDocs['rank-self'].learningRankingJson))),6);assert.equal(await page.evaluate(()=>window.LearningRankingModel.wordCount(JSON.parse(window.__rankingDocs['rank-self'].learningRankingJson))),2);
await page.evaluate(async()=>{const cloud=JSON.parse(window.__rankingDocs['rank-self'].learningRankingJson);cloud.flash.sources.other=7;cloud.words.remote=1;window.__rankingDocs['rank-self'].learningRankingJson=JSON.stringify(cloud);await window.loadUserStats();});assert.equal(await page.evaluate(()=>userStats.flash_count),13);assert.equal(await page.evaluate(()=>userStats.vocab_rated_count),3);
// An old cloud-only account imports saved ratings across all books and its swipe baseline.
await page.evaluate(async()=>{window.__rankingDocs.legacy={playerName:'以前のユーザー',userStats:{flash_count:70}};myId='legacy';myName='以前のユーザー';userStats={};currentTextbook='';vocabList=[];const original=window.fbGetDocs;window.fbGetDocs=async ref=>ref==='users/legacy/vocabProgress'?{forEach:fn=>fn({id:'old-cloud-book',data:()=>({wordsJson:JSON.stringify({8:{meanings:{m:{status:'so'}}},9:{status:'bad'},10:{status:'none'}})})})}:original(ref);await window.loadUserStats();window.fbGetDocs=original;});assert.equal(await page.evaluate(()=>userStats.flash_count),70);assert.equal(await page.evaluate(()=>userStats.vocab_rated_count),2);
// Preserve cumulative records on restart independently of integrated saves.
const saved=await page.evaluate(()=>localStorage.getItem('core_v4_learning_ranking_rank-self'));assert.equal(JSON.parse(saved).flash.sources.other,7);await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.LearningRanking);await page.evaluate(()=>{window.__gcLoginShown=true;document.querySelectorAll('.gcModal').forEach(el=>el.remove());myId='rank-self';myName='自分 太郎';userStats={};window.syncRankingMetrics();});assert.equal(await page.evaluate(()=>userStats.flash_count),13);assert.equal(await page.evaluate(()=>userStats.vocab_rated_count),3);assert.deepEqual(errors,[]);console.log('PASS: three metrics, top-three podium, photos, multiline names, details, small-screen fit, legacy progress, transaction merge and restart');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
