const test=require('node:test'),assert=require('node:assert/strict'),m=require('../learning-rewards-model.js');
test('Japan midnight and Monday boundaries are independent of device timezone',()=>{assert.equal(m.dateKey(Date.parse('2026-10-11T14:59:59Z')),'2026-10-11');assert.equal(m.dateKey(Date.parse('2026-10-11T15:00:00Z')),'2026-10-12');assert.equal(m.weekStart(Date.parse('2026-10-11T14:59:59Z')),'2026-10-05');assert.equal(m.weekStart(Date.parse('2026-10-11T15:00:00Z')),'2026-10-12');assert.equal(m.shiftDay('2026-01-01',-1),'2025-12-31');assert.equal(m.validDay('2026-02-30'),false);});
test('every explicit answer counts separately and merges without repeated delivery',()=>{const t=Date.parse('2026-10-10T03:00:00Z');let a=m.add(m.activity(),'ratings','phone',t);a=m.add(a,'ratings','phone',t);const b=m.add(m.activity(),'ratings','laptop',t);const combined=m.mergeActivity(a,b);assert.equal(m.count(combined,'ratings','2026-10-10'),3);assert.equal(m.count(m.mergeActivity(combined,a),'ratings','2026-10-10'),3);assert.deepEqual(m.mergeActivity(a,b),m.mergeActivity(b,a));assert.equal(m.count(m.mergeActivity({version:2,words:{legacy:1}}),'ratings','2026-10-10'),0);});
test('daily mail floors study minutes and includes each answer once',()=>{const letter=m.dailyMail('2026-10-10',119999,5);assert.equal(letter.amount,15);const first=m.claim(m.wallet(400),letter.id,letter.amount);assert.equal(m.balance(first),415);assert.deepEqual(m.claim(first,letter.id,letter.amount),first);assert.equal(m.balance(m.claim(first,letter.id,25)),425,'late synced activity only credits the difference');});
test('sequential purchases charge each full upgrade price and retain lower grades',()=>{const catalog=['wood','silver','gold'].map(id=>({id}));let w=m.wallet(3500);assert.throws(()=>m.purchase(w,'silver',catalog,1));w=m.purchase(w,'wood',catalog,1);assert.equal(m.balance(w),3400);w=m.purchase(w,'silver',catalog,2);assert.equal(m.balance(w),2900);w=m.purchase(w,'gold',catalog,3);assert.equal(m.balance(w),400);assert.ok(m.owned(w,'wood'));assert.ok(m.owned(w,'silver'));assert.equal(m.equip(w,'wood',4).equipped.id,'wood');assert.deepEqual(m.purchase(w,'silver',catalog,5),w);assert.throws(()=>m.equip(w,'dog',5));assert.equal(m.price(0),100);assert.equal(m.price(3),12500);});
test('a stale backup cannot undo received mail or frame purchases',()=>{const original=m.wallet(1000,'2026-10-10'),latest=m.purchase(m.claim(original,'daily:2026-10-09',100),'wood',[{id:'wood'}],10),restored=m.mergeWallet(original,latest);assert.equal(m.balance(restored),1000);assert.ok(m.owned(restored,'wood'));assert.deepEqual(restored,m.mergeWallet(latest,original));});
test('weekly awards are distinct per metric, ties stable, zero and guests excluded',()=>{const rows=[{id:'b',time:10,words:3,flash:0},{id:'a',time:10,words:1,flash:9},{id:'c',time:2,words:5,flash:3},{id:'GUEST-000',time:99,words:99,flash:99}];const letters=m.weeklyMail('2026-10-05',rows,'a');assert.deepEqual(letters.map(x=>[x.metric,x.place,x.amount]),[['time',1,10000],['words',3,1000],['flash',1,10000]]);let w=m.wallet();for(const l of letters)w=m.claim(w,l.id,l.amount);assert.equal(m.balance(w),21000);for(const l of letters)w=m.claim(w,l.id,l.amount);assert.equal(m.balance(w),21000);assert.equal(m.podium([{id:'empty',time:0}],'time').length,0);});

test('malformed wallets cannot be promoted to an empty replacement',()=>{assert.equal(m.validWallet(m.wallet(321)),true);assert.equal(m.validWallet('broken'),false);assert.equal(m.validWallet({version:1,base:-1,createdDay:'2026-10-10',credits:{},debits:{}}),false);assert.equal(m.validWallet({version:1,base:5,createdDay:'bad',credits:{},debits:{}}),false);});
