const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const stateSource=fs.readFileSync('library-state.js','utf8');const librarySource=fs.readFileSync('library.js','utf8');
function setup(owner='alice',sharedCloud=new Map()){
 const local=new Map();const ctx={console,crypto:require('node:crypto').webcrypto,myId:owner,textbooksCacheMap:{},addEventListener:()=>{},setInterval:()=>{},onAppLoaded:()=>{},userId:()=>ctx.myId,key:()=> 'core_v4_personal_library_'+ctx.myId,cloudAvailable:()=>true,publish:async()=>{},localStorage:{get length(){return local.size;},key:n=>[...local.keys()][n],getItem:k=>local.get(k)||null,setItem:(k,v)=>local.set(k,String(v)),removeItem:k=>local.delete(k)}};ctx.window=ctx;ctx.db={};ctx.fbDoc=(_, ...path)=>path.join('/');ctx.fbCollection=ctx.fbDoc;ctx.fbGetDoc=async path=>({exists:()=>sharedCloud.has(path),data:()=>sharedCloud.get(path)});ctx.fbRunTransaction=async(_,job)=>job({get:ctx.fbGetDoc,set:(path,data)=>sharedCloud.set(path,Object.assign({},sharedCloud.get(path),data))});ctx.fbSetDoc=async(path,data)=>sharedCloud.set(path,JSON.parse(JSON.stringify(data)));ctx.fbDeleteDoc=async path=>sharedCloud.delete(path);ctx.fbGetDocs=async prefix=>({forEach:cb=>{for(const [path,data] of sharedCloud)if(path.startsWith(prefix+'/')&&!path.slice(prefix.length+1).includes('/'))cb({id:path.split('/').pop(),data:()=>data});}});
 ctx.getVocabProgressStorageKey=id=>'core_v4_user_vocab_progress_'+ctx.myId+'_'+id;ctx.__manualVocabLocalKey=id=>'core_v4_vocab_draft_'+ctx.myId+'_'+encodeURIComponent(id);ctx.__manualVocabCloudId=id=>encodeURIComponent(id);ctx.__gameSaveChecksum=x=>require('node:crypto').createHash('sha256').update(x).digest('hex');vm.runInNewContext(stateSource,ctx);return {ctx,local,cloud:sharedCloud,state:ctx.LibraryState};
}
function snapshot(){return {savedAt:'2099-01-01',data:{localStorage:{core_v4_personal_library_alice:JSON.stringify({books:[{id:'book-a'},{id:'keep'}],hidden:[]}),vv4_works_alice:JSON.stringify([{id:'work-a',units:[{note:'secret'}]},{id:'keep-work'}]),core_v4_cache_book_a:'other',core_v4_cache_book_b:'keep',core_v4_custom_words_alice_book_a:'other',core_v4_custom_words_alice_book_b:'keep'},memory:{vocabBooks:{'book-a':{master:['secret']},keep:{master:['keep']}},textbooksPool:[{id:'book-a'},{id:'keep'}],vocabBookKey:'book-a',currentTextbook:'book-a',vocabMaster:['secret'],vocabList:['secret'],vocabProgress:{1:{note:'secret'}}}}};}
test('deletion records remove books and workbooks from a newer integrated save',async()=>{const {state}=setup();await state.mark('book','book-a',{});await state.mark('work','work-a',{});const save=snapshot();state.sanitizeSave(save);assert.equal(save.data.memory.vocabBooks['book-a'],undefined);assert.equal(save.data.memory.vocabBooks.keep.master[0],'keep');assert.equal(save.data.memory.vocabList.length,0);
 // Owner-scoped workbook and library arrays are handled without affecting another account.
 const other=snapshot();state.sanitizeSave(other,'bob');assert.equal(JSON.parse(other.data.localStorage.vv4_works_alice).length,2);assert.equal(JSON.parse(save.data.localStorage.vv4_works_alice)[0].id,'keep-work');
});
test('cloud deletion history protects a fresh device and merged old snapshots',async()=>{const first=setup();await first.state.mark('book','book-a',{});await first.state.complete('book','book-a');await first.state.mark('work','work-a',{});await first.state.complete('work','work-a');const fresh=setup('alice',first.cloud);await fresh.state.loadCloud();const save=snapshot();fresh.state.sanitizeSave(save);assert.deepEqual(JSON.parse(save.data.localStorage.vv4_works_alice).map(w=>w.id),['keep-work']);assert.deepEqual(JSON.parse(save.data.localStorage.core_v4_personal_library_alice).books.map(b=>b.id),['keep']);assert.equal(save.data.memory.vocabBooks['book-a'],undefined);assert.equal(fresh.state.read()['book:book-a'].pending,false);
 const older={'book:book-a':{kind:'book',id:'book-a',pending:true,updatedAt:1}};assert.equal(fresh.state.merge(fresh.state.read(),older)['book:book-a'].pending,false);
});
test('permanent workbook deletion rewrites local and chunked cloud backups',async()=>{const {ctx,state,local,cloud}=setup();const save=snapshot();local.set('vv4_works_alice',save.data.localStorage.vv4_works_alice);local.set('save_studio_alice_main',JSON.stringify(save));cloud.set('users/alice/saves/main',{partCount:1,generation:'old'});cloud.set('users/alice/saves/main/parts/old_p0',{d:JSON.stringify(save)});cloud.set('publicWorkbooks/work-a',{ownerId:'alice'});
 vm.runInNewContext(librarySource.slice(librarySource.indexOf('    function bookStorageKeys'),librarySource.indexOf('    window.openLibraryBookActions')),ctx);
 await ctx.eraseLibraryItem('work-a',{visibility:'public'},'work');assert.deepEqual(JSON.parse(local.get('vv4_works_alice')).map(w=>w.id),['keep-work']);assert.equal(cloud.has('publicWorkbooks/work-a'),false);assert.equal(cloud.has('users/alice/saves/main/parts/old_p0'),false);const meta=cloud.get('users/alice/saves/main');const clean=JSON.parse(cloud.get('users/alice/saves/main/parts/'+meta.generation+'_p0').d);assert.deepEqual(JSON.parse(clean.data.localStorage.vv4_works_alice).map(w=>w.id),['keep-work']);assert.equal(state.read()['work:work-a'].pending,false);assert.equal(clean.data.memory.vocabBooks.keep.master[0],'keep');
});
test('deletion waits for an in-flight save before scrubbing its last write',async()=>{const {state}=setup();let release,finished=false;const write=state.track('alice',()=>new Promise(resolve=>release=()=>{finished=true;resolve();}));await Promise.resolve();await state.mark('book','book-a',{});let waited=false;const wait=state.waitForWrites('alice').then(()=>waited=true);await Promise.resolve();assert.equal(waited,false);release();await write;await wait;assert.equal(finished,true);assert.equal(waited,true);});
test('a local hidden book remains hidden when a newer snapshot restores its catalogue',()=>{const {state,local}=setup();local.set('core_v4_personal_library_alice',JSON.stringify({books:[],hidden:['old-hidden']}));const save=snapshot();state.sanitizeSave(save);assert.equal(JSON.parse(save.data.localStorage.core_v4_personal_library_alice).hidden.includes('old-hidden'),true);});

test('the real auto-loader cannot restore a deleted workbook or cached book from a newer snapshot',async()=>{const {ctx,state,local}=setup();await state.mark('work','work-a',{});await state.complete('work','work-a');await state.mark('book','book-a',{});await state.complete('book','book-a');const save=snapshot();save.data.localStorage['core_v4_cache_book-a']='secret';save.data.localStorage['core_v4_custom_words_alice_book-a']='secret';local.set('restore',JSON.stringify(save));ctx.loginUid=()=> 'alice';ctx.localKey=()=> 'restore';ctx.cloudMetaKey=()=> 'cloud-meta';ctx.localMetaKey=()=> 'local-meta';ctx.applySavedMemory=()=>{};const source=fs.readFileSync('save-system.js','utf8');vm.runInNewContext(source.slice(source.indexOf('async function autoLoadOnce()'),source.indexOf('\nfunction openPanel()',source.indexOf('async function autoLoadOnce()'))),ctx);await ctx.autoLoadOnce();assert.equal(local.has('core_v4_cache_book-a'),false);assert.equal(local.has('core_v4_custom_words_alice_book-a'),false);assert.deepEqual(JSON.parse(local.get('vv4_works_alice')).map(work=>work.id),['keep-work']);assert.equal(ctx.__pendingGameSaveMemory.data.vocabBooks['book-a'],undefined);assert.equal(state.isDeleted('book','book-a'),true);});

test('permanent deletion removes owned legacy publications and keeps other owners copies',async()=>{const {ctx,cloud}=setup();cloud.set('public_works/all',{worksJson:JSON.stringify([{id:'legacy',sharedBy:'alice',entries:{1:{note:'secret'}}},{id:'legacy',sharedBy:'bob'},{id:'other',sharedBy:'bob'}])});cloud.set('publicWorkbooks/legacy',{ownerId:'bob',masterJson:'keep'});vm.runInNewContext(librarySource.slice(librarySource.indexOf('    function bookStorageKeys'),librarySource.indexOf('    window.openLibraryBookActions')),ctx);await ctx.eraseLibraryItem('legacy',{visibility:'private'},'work');const remaining=JSON.parse(cloud.get('public_works/all').worksJson);assert.equal(remaining.length,2);assert.equal(remaining.every(record=>record.sharedBy==='bob'),true);assert.equal(cloud.get('publicWorkbooks/legacy').masterJson,'keep');});

test('restoring a catalogue never drops a locally added shared-book copy',()=>{const {local,state}=setup();local.set('core_v4_personal_library_alice',JSON.stringify({savedAt:'2026-10-08',hidden:[],books:[{id:'new-copy',personal:true,name:'追加した共有単語帳'}]}));const save={data:{localStorage:{core_v4_personal_library_alice:JSON.stringify({savedAt:'2099-01-01',hidden:[],books:[{id:'other'}]})}}};state.sanitizeSave(save,'alice');assert.deepEqual(JSON.parse(save.data.localStorage.core_v4_personal_library_alice).books.map(book=>book.id).sort(),['new-copy','other']);});

test('the catalogue cloud transaction retains copies added on another device',async()=>{const {ctx,local,cloud}=setup();ctx.pendingCatalogs=new Set();ctx.refreshPool=()=>{};ctx.renderVocabLibrarySelection=()=>{};ctx.readLibrary=()=>JSON.parse(local.get('core_v4_personal_library_alice'));const own={savedAt:'2026-10-08',hidden:[],books:[{id:'phone-copy',personal:true}]};local.set('core_v4_personal_library_alice',JSON.stringify(own));cloud.set('users/alice/library/catalog',{libraryJson:JSON.stringify({savedAt:'2026-10-07',hidden:[],books:[{id:'other-device-copy',personal:true}]})});vm.runInNewContext(librarySource.slice(librarySource.indexOf('    function mergeLibraries('),librarySource.indexOf('    window.onAppLoaded(async function()',librarySource.indexOf('    function mergeLibraries('))),ctx);await ctx.syncLibraryCloud(own);assert.deepEqual(JSON.parse(cloud.get('users/alice/library/catalog').libraryJson).books.map(book=>book.id).sort(),['other-device-copy','phone-copy']);});
test('unrelated newer catalogue edits cannot undo a book-specific hide',()=>{const {state}=setup();const local={books:[{id:'a'}],hidden:['a'],visibility:{a:{hidden:true,updatedAt:20}},savedAt:'2026-01-01'};const remote={books:[{id:'b'}],hidden:[],savedAt:'2026-12-01'};const merged=state.mergeCatalog(local,remote);assert.deepEqual(Array.from(merged.hidden),['a']);assert.equal(merged.books.length,2);});
test('explicit restore survives an older hidden backup in either merge order',()=>{const {state}=setup();const old={books:[],hidden:['a'],visibility:{a:{hidden:true,updatedAt:20}}};const restored={books:[],hidden:[],visibility:{a:{hidden:false,updatedAt:21}}};for(const [a,b] of [[old,restored],[restored,old]])assert.equal(state.mergeCatalog(a,b).hidden.length,0);});
test('failed cloud deletion keeps a local pending tombstone and can retry',async()=>{const {ctx,state,cloud}=setup();const real=ctx.fbSetDoc;ctx.fbSetDoc=async()=>{throw Error('offline');};await state.mark('book','offline-book',{});assert.equal(state.isDeleted('book','offline-book'),true);assert.equal(state.read()['book:offline-book'].pending,true);ctx.fbSetDoc=real;await state.mark('book','offline-book',{});const fresh=setup('alice',cloud);await fresh.state.loadCloud();assert.equal(fresh.state.isDeleted('book','offline-book'),true);});

test('legacy backup timestamp cannot override an explicit visibility choice',()=>{const {state}=setup();const old={books:[],hidden:['a'],savedAt:'2099-01-01'};const current={books:[],hidden:[],visibility:{a:{hidden:false,updatedAt:20}}};for(const [a,b] of [[old,current],[current,old]])assert.equal(state.mergeCatalog(a,b).hidden.length,0);});
