const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:390,height:844}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.route('https://**/*',r=>r.abort());await page.addInitScript(()=>localStorage.setItem('b3_tutorial_done','1'));await page.goto('http://127.0.0.1:8000',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.openLibraryBookEditor);await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.locator('#nav-vocab').click();await page.getByRole('button',{name:'＋ 単語帳を作る',exact:true}).click();await page.locator('#libraryBookName').fill('古文単語315');await page.locator('#libraryBookWords').fill(JSON.stringify([{num:1,word:'study',meaning:'(名) の例文についての説明',meanings:[{id:'1-0',text:'(名) の例文についての説明',partOfSpeech:'動'}]}]));await page.getByRole('button',{name:'単語帳を作る',exact:true}).click();
const book=await page.evaluate(()=>textbooksPool.find(b=>b.name==='古文単語315').id);const name=page.locator('.textbook-list-name').filter({hasText:'古文単語315'});assert.equal(await name.textContent(),'古文単語315');assert.equal(await name.evaluate(el=>getComputedStyle(el).fontVariantNumeric),'lining-nums tabular-nums');assert.equal(await name.evaluate(el=>getComputedStyle(el).fontFamily.includes('Georgia')),false);
await page.getByRole('button',{name:'古文単語315のフラッシュ単語設定'}).click();await page.getByRole('button',{name:'カードを開始する'}).click();await page.locator('#flashcardPartOfSpeech').waitFor({state:'visible'});assert.equal(await page.locator('#flashcardPartOfSpeech').textContent(),'動');await page.locator('#flashcard-play-screen').getByRole('button',{name:'戻る',exact:true}).click();assert.equal(await page.locator('#view-vocab').evaluate(el=>el.classList.contains('active')),true);
await page.locator('#vocabLibraryBooks .textbook-list-item').filter({hasText:'古文単語315'}).click();await page.evaluate(()=>window.updateMeaningStatus('1','1-0','ok'));await page.waitForTimeout(700);await page.locator('.card-edit-btn').first().click();await page.getByRole('combobox',{name:'意味1の品詞'}).selectOption('名');await page.getByRole('button',{name:'保存する',exact:true}).click();assert.equal(await page.evaluate(()=>vocabList[0].meanings[0].partOfSpeech),'名');assert.equal(await page.evaluate(()=>vocabList[0].meanings[0].status),'ok');await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.openLibraryBookEditor);await page.locator('#nav-vocab').click();await page.getByRole('button',{name:'古文単語315のフラッシュ単語設定'}).click();await page.getByRole('button',{name:'カードを開始する'}).click();assert.equal(await page.locator('#flashcardPartOfSpeech').textContent(),'名');await page.locator('#flashcard-play-screen').getByRole('button',{name:'戻る',exact:true}).click();
// Rankings belong only to titles; opening friends cannot hide or move the ranking section.
assert.equal(await page.locator('#view-community #leaderboardContainer').count(),0);assert.equal(await page.locator('#view-titles #rankingPodium').count(),1);await page.locator('#nav-titles').click();assert.equal(await page.locator('#rankingPodium').isVisible(),true);await page.locator('#nav-community').click();assert.equal(await page.locator('#friendListContainer').isVisible(),true);assert.equal(await page.getByText('スワイプでスコアボード',{exact:true}).count(),0);
// Delete a book with a stale backup, then attempt restoring the backup after reload.
await page.evaluate(id=>{window.__staleSnapshot={savedAt:'2099-01-01',data:{localStorage:{core_v4_personal_library_GUEST_ignored:'keep'},memory:{textbooksPool:JSON.parse(JSON.stringify(textbooksPool)),vocabBooks:{[id]:{master:[{num:1,word:'secret'}]}},vocabBookKey:id,vocabMaster:[{num:1,word:'secret'}],vocabList:[{num:1,word:'secret'}]}}};localStorage.setItem('save_studio_GUEST-000_main',JSON.stringify(window.__staleSnapshot));},book);await page.locator('#nav-vocab').click();await page.getByRole('button',{name:'古文単語315の管理',exact:true}).click();await page.getByRole('button',{name:'単語帳を完全削除',exact:true}).click();await page.getByRole('button',{name:'完全削除する',exact:true}).click();await page.waitForFunction(id=>!textbooksPool.some(b=>b.id===id),book);const clean=await page.evaluate(()=>JSON.parse(localStorage.getItem('save_studio_GUEST-000_main')));assert.equal(clean.data.memory.vocabBooks[book],undefined);assert.equal(await page.evaluate(id=>window.LibraryState.read()['book:'+id].pending,book),false);
await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.openLibraryBookEditor);await page.locator('#nav-vocab').click();assert.equal(await page.getByText('古文単語315',{exact:true}).count(),0);assert.deepEqual(errors,[]);await page.screenshot({path:'/tmp/library-regression.png'});console.log('PASS: independent POS edit/restart, flash close to vocabulary, lining book digits, ranking relocation and deletion backup cleanup');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
