// Requires Playwright, Chromium and a local HTTP server.
const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
try{
const page=await browser.newPage({viewport:{width:390,height:844}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());
await page.addInitScript(()=>localStorage.setItem('b3_tutorial_done','1'));await page.goto(process.env.FLASHCARD_TEST_URL||'http://127.0.0.1:8000',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.openLibraryBookEditor);
await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.locator('#nav-vocab').click();
await page.getByRole('button',{name:'＋ 単語帳を作る'}).click();await page.waitForTimeout(300);await page.screenshot({path:'/tmp/library-editor.png'});await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>window.__copiedPhotoPrompt=text},configurable:true}));await page.locator('#libraryCopyPhotoPrompt').click();assert.match(await page.evaluate(()=>window.__copiedPhotoPrompt),/番号:英単語:日本語の意味:サブ情報/);await page.locator('#libraryBookName').fill('自分の単語帳');await page.locator('#libraryBookWords').fill('1:study:①学ぶ②研究する:study English\n2:read:読む:');
await page.locator('#libraryBookCover').setInputFiles('Header.png');await page.waitForFunction(()=>document.querySelector('#libraryBookCoverPreview').src.startsWith('data:image/jpeg'));await page.locator('#libraryBookVisibility').selectOption('public');await page.getByRole('button',{name:'単語帳を作る',exact:true}).click();await page.getByText('みんなに公開するにはログインしてください。自分だけの単語帳はゲストでも作れます。').waitFor();
await page.locator('#libraryBookVisibility').selectOption('private');await page.getByRole('button',{name:'単語帳を作る',exact:true}).click();assert.equal(await page.locator('dialog').count(),0);
await page.locator('#vocabLibraryBooks .textbook-list-item').click();await page.waitForFunction(()=>vocabList.length===2);assert.equal(await page.evaluate(()=>window.isAdmin),false);assert.equal(await page.evaluate(()=>window.canEditCurrentTextbook()),true);assert.equal(await page.evaluate(()=>vocabList[0].meanings.length),2);assert.equal(await page.evaluate(()=>vocabList[0].sub),'study English');assert.equal(await page.evaluate(()=>textbooksPool.find(b=>b.id===currentTextbook).coverType),'image');
await page.evaluate(()=>{vocabList[0].meanings[0].status='ok';vocabList[0].meanings[0].history=['ok'];window.saveVocabProgressLocally(1);window.__captureManualVocabDraft();});
await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.openLibraryBookEditor);await page.locator('#nav-vocab').click();await page.getByRole('button',{name:'自分の単語帳の管理'}).click();await page.getByRole('button',{name:'名前・表紙を編集 / 単語を追加'}).click();await page.locator('#libraryBookWords').fill('3:write:書く:');await page.getByRole('button',{name:'変更を保存'}).click();
await page.locator('#vocabLibraryBooks .textbook-list-item').click();await page.waitForFunction(()=>vocabList.length===3);assert.equal(await page.evaluate(()=>vocabList[0].meanings[0].status),'ok');
await page.evaluate(()=>window.showVocabLibrarySelection());await page.getByRole('button',{name:'自分の単語帳の管理',exact:true}).click();await page.getByRole('button',{name:'自分の一覧から外す',exact:true}).click();await page.locator('#libraryConfirmRemove').click();await page.getByRole('button',{name:'非表示の自分の単語帳',exact:true}).click();await page.getByRole('button',{name:'管理',exact:true}).click();assert.equal(await page.getByRole('button',{name:'単語帳を完全削除',exact:true}).count(),1);await page.getByRole('button',{name:'一覧に戻す',exact:true}).click();await page.getByRole('button',{name:'自分の単語帳の管理',exact:true}).waitFor();
// Mock the public catalogue and cloud writes, without network access or real publishing.
await page.evaluate(()=>{window.__gcLoginShown=true;myId='library-test';window.db={};window.__libraryWrites=[];window.fbDoc=(...args)=>args;window.fbCollection=(...args)=>args;window.fbSetDoc=async(...args)=>{if(args[0].includes('publicTextbooks'))window.__libraryWrites.push(args);};window.fbGetDoc=async(ref)=>{const stored=window.__libraryWrites.find(write=>Array.isArray(write[0])&&write[0].includes('publicTextbooks')&&write[0].at(-1)===ref.at(-1));return {exists:()=>!!stored,data:()=>stored&&stored[1]};};window.fbDeleteDoc=async(...args)=>window.__libraryWrites.push(['delete',...args]);window.fbGetDocs=async(ref)=>ref[1]!=='publicTextbooks'?{forEach:()=>{}}:({forEach:cb=>cb({id:'other-book',data:()=>({ownerId:'other-user',name:'みんなのテスト単語帳',masterJson:JSON.stringify([{num:1,word:'hello',meaning:'こんにちは',note:'private',status:'ok',history:['ok']}])})})});window.showVocabLibrarySelection();});
await page.getByRole('button',{name:'みんなの単語帳',exact:true}).click();await page.getByRole('button',{name:'自分用に追加'}).click();await page.getByRole('button',{name:'閉じる',exact:true}).click();assert.equal(await page.evaluate(()=>window.__libraryWrites.length),0);
await page.getByRole('button',{name:'みんなのテスト単語帳の管理'}).click();await page.getByRole('button',{name:'名前・表紙を編集 / 単語を追加'}).click();await page.locator('#libraryBookName').fill('公開する単語帳');await page.locator('#libraryBookVisibility').selectOption('public');await page.getByRole('button',{name:'変更を保存'}).click();
const payload=await page.evaluate(()=>window.__libraryWrites[0][1]);assert.equal(payload.ownerId,'library-test');const master=JSON.parse(payload.masterJson);assert.equal(master[0].note,undefined);assert.equal(master[0].status,undefined);assert.equal(master[0].history,undefined);
await page.getByRole('button',{name:'公開する単語帳の管理'}).click();await page.getByRole('button',{name:'単語帳を完全削除',exact:true}).click();await page.getByRole('button',{name:'完全削除する',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('dialog'));assert.equal(await page.getByRole('button',{name:'公開する単語帳の管理'}).count(),0);assert.equal(await page.evaluate(()=>window.__libraryWrites[1][0]),'delete');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('core_v4_personal_library_library-test')).books.length),0);
// Legacy shared books must expose personal data deletion without unpublishing the source.
await page.evaluate(()=>{textbooksPool.push({id:'legacy-shared',name:'従来の配信単語帳',cover:'📔',coverType:'text',visibility:'public'});localStorage.setItem('core_v4_custom_words_library-test_legacy-shared','[{"num":1,"word":"old"}]');window.showVocabLibrarySelection();});
await page.getByRole('button',{name:'従来の配信単語帳の管理',exact:true}).click();await page.getByRole('button',{name:'自分の単語帳データを完全削除',exact:true}).click();await page.getByRole('button',{name:'完全削除する',exact:true}).click();assert.equal(await page.getByRole('button',{name:'従来の配信単語帳の管理',exact:true}).count(),0);assert.equal(await page.evaluate(()=>localStorage.getItem('core_v4_custom_words_library-test_legacy-shared')),null);assert.equal(await page.evaluate(()=>window.__libraryWrites.some(write=>write[0]==='delete'&&write[1].includes('publicTextbooks')&&write[1].includes('legacy-shared'))),false);
assert.deepEqual(errors,[]);console.log('PASS: non-admin creation, restart, word addition, retained understanding, public catalogue copy, publish without progress and public removal');
}finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
