const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const type=process.env.BROWSER==='webkit'?webkit:chromium;const browser=await type.launch(type===chromium?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:(process.env.WEBKIT_EXECUTABLE_PATH?{executablePath:process.env.WEBKIT_EXECUTABLE_PATH}:{} ));try{
 const page=await browser.newPage({viewport:{width:393,height:852}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());if(process.env.BASELINE_DIR){for(const name of ['app','save-system'])await page.route('**/'+name+'.js?*',r=>r.fulfill({contentType:'application/javascript',body:fs.readFileSync(process.env.BASELINE_DIR+'/'+name+'.js','utf8')}));await page.route('**/learning-data.js?*',r=>r.fulfill({contentType:'application/javascript',body:''}));}
 await page.addInitScript(()=>{if(localStorage.getItem('race-seeded'))return;localStorage.setItem('race-seeded','1');localStorage.setItem('b3_tutorial_done','1');localStorage.setItem('core_v4_userId','race-user');localStorage.setItem('core_v4_userName','検証');localStorage.setItem('core_v4_current_textbook_id','race-book');const master=[{num:1,word:'study',meaning:'学ぶ'},{num:2,word:'save',meaning:'保存する'}];localStorage.setItem('core_v4_cache_race-book',JSON.stringify(master));const progress={1:{sig:'1::study::学ぶ',status:'ok',history:['ok'],meanings:{'1-0':{status:'ok',history:['ok']}}},2:{sig:'2::save::保存する',status:'bad',history:['bad'],meanings:{'2-0':{status:'bad',history:['bad']}}}};localStorage.setItem('core_v4_user_vocab_progress_race-user_race-book',JSON.stringify(progress));localStorage.setItem('core_v4_user_vocab_progress_race-user_race-book__ts','1000');localStorage.setItem('core_v4_autosave_pending_race-user','1');const empty={1:{sig:'1::study::学ぶ',status:'none',history:[],meanings:{'1-0':{status:'none',history:[]}}},2:{sig:'2::save::保存する',status:'none',meanings:{'2-0':{status:'none'}}}};localStorage.setItem('save_studio_race-user_main',JSON.stringify({savedAt:new Date(2000).toISOString(),data:{localStorage:{},memory:{vocabBookKey:'race-book',vocabMaster:master,vocabProgress:empty,vocabBooks:{'race-book':{master,progress:empty,savedAt:new Date(2000).toISOString()}}}}}));});
 await page.goto('http://127.0.0.1:8000');if(process.env.BASELINE_DIR){await page.waitForFunction(()=>window.UserProfile&&typeof myId==='string'&&myId==='race-user');await page.waitForTimeout(500);}else await page.waitForFunction(()=>window.__learningBootReady===true);const status=()=>page.evaluate(()=>window.LearningData?LearningData.read('race-book')[1].status:JSON.parse(localStorage.getItem(getVocabProgressStorageKey('race-book')))[1].status);assert.equal(await status(),'ok');assert.equal(await page.evaluate(()=>vocabList.find(w=>String(w.num)==='1').status),'ok');
 // Closing/background-saving while the next load waits must not capture default values.
 await page.evaluate(async()=>{window.__learningBootReady=false;vocabList=[];let refused=false;try{await __backgroundSaveAll()}catch(e){refused=/読み込み/.test(e.message)}if(!refused)throw Error('load-time save was not blocked');window.__learningBootReady=true;await loadCurrentTextbookData();await __backgroundSaveAll();await AppStorage.flush();});assert.equal(await status(),'ok');
 for(let i=0;i<3;i++){await page.reload();await page.waitForFunction(()=>window.__learningBootReady===true);assert.equal(await status(),'ok');}
 await page.evaluate(async()=>{const k=getVocabProgressStorageKey('race-book');localStorage.setItem(k,'{}');LearningData.read('race-book');await AppStorage.flush();});assert.equal(await status(),'ok');
 assert.deepEqual(errors,[]);console.log('PASS '+type.name()+': newer empty backup cannot erase ratings; save blocked during load; repeated save/reload and recovery retain answers');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
