const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
 const page=await browser.newPage({viewport:{width:393,height:852},userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Mobile Safari/604.1'}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('crash',()=>errors.push('renderer crash'));await page.route('https://**/*',r=>r.abort());
 await page.addInitScript(()=>{localStorage.setItem('b3_tutorial_done','1');window.__polls=[];const native=setInterval;window.setInterval=(fn,ms,...args)=>{const p={stack:new Error().stack,ms,count:0};__polls.push(p);return native(()=>{p.count++;fn(...args);},ms);};});
 await page.goto('http://127.0.0.1:8000');await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.waitForTimeout(1800);
 await page.evaluate(()=>{switchTab('vocab');document.getElementById('vocabLibrarySelection').hidden=true;document.getElementById('vocabBookContents').hidden=false;currentTextbook='large-book';vocabList=migrateVocabData(Array.from({length:2000},(_,i)=>({num:i+1,word:'word-'+(i+1),meaning:'意味 '+(i+1)})));textbooksPool=[{id:'large-book',name:'大量単語帳'}];textbooksCacheMap['large-book']=vocabList;localStorage.setItem('core_v4_current_textbook_id','large-book');document.getElementById('vocabRangeStart').value=1;document.getElementById('vocabRangeEnd').value=2000;renderVocabList();});
 assert.equal(await page.locator('#vocabListContainer .word-row-container').count(),40);assert.match(await page.locator('.vocab-pages').textContent(),/1–40 \/ 2000/);
 await page.locator('.vocab-pages').getByRole('button',{name:'次へ',exact:true}).click();assert.equal(await page.locator('.word-row-container').first().getAttribute('data-word-num'),'41');
 await page.evaluate(()=>updateMeaningStatus(41,vocabList[40].meanings[0].id,'ok'));assert.equal(await page.locator('.word-row-container').first().getAttribute('data-word-num'),'41');assert.equal(await page.evaluate(()=>vocabList[40].meanings[0].status),'ok');
 await page.locator('#vocabSearchInput').fill('word-2000');await page.evaluate(()=>renderVocabList());assert.equal(await page.locator('#vocabListContainer .word-row-container').count(),1);assert.equal(await page.locator('.word-row-container').first().getAttribute('data-word-num'),'2000');await page.locator('#vocabSearchInput').fill('');await page.evaluate(()=>renderVocabList());
 await page.waitForTimeout(1700);for(const tab of ['reader','vocab','titles']){await page.evaluate(t=>{switchTab(t);__polls.forEach(p=>p.count=0);},tab);await page.waitForTimeout(1100);const hidden=await page.evaluate(()=>__polls.filter(p=>p.stack.includes('view-work.js')&&p.ms<1000&&p.count));assert.deepEqual(hidden,[],tab+' must not run game or gacha polls');}
 // The scheduler actually stops intervals, and restarts once on return.
 await page.evaluate(()=>{window.__scopeCount=0;ViewWork.interval(()=>__scopeCount++,50,['party']);switchTab('party');});await page.waitForTimeout(180);assert.ok(await page.evaluate(()=>__scopeCount)>0);await page.evaluate(()=>switchTab('reader'));const stopped=await page.evaluate(()=>__scopeCount);await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>__scopeCount),stopped);
 await page.evaluate(()=>switchTab('party'));await page.waitForTimeout(150);assert.ok(await page.evaluate(()=>__scopeCount)>stopped);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});const hiddenCount=await page.evaluate(()=>__scopeCount);await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>__scopeCount),hiddenCount);await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));switchTab('reader');});
 // Idle study UI must not rewrite the same labels/calendar every tick.
 await page.evaluate(()=>{switchTab('study');window.__studyMutations=0;new MutationObserver(rs=>__studyMutations+=rs.length).observe(document.getElementById('view-study'),{childList:true,subtree:true});});await page.waitForTimeout(1200);await page.evaluate(()=>__studyMutations=0);await page.waitForTimeout(2200);assert.equal(await page.evaluate(()=>__studyMutations),0);
 await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=800;canvas.getContext('2d').fillRect(0,0,800,800);const source=canvas.toDataURL();const img=RankingVisuals.avatar(source,'写真');document.body.append(img);window.__preview=img.querySelector('img');});await page.waitForFunction(()=>__preview.complete&&__preview.naturalWidth===64);assert.equal(await page.evaluate(()=>__preview.naturalHeight),64);
 assert.deepEqual(errors,[]);console.log('PASS: 2000-word book mounts 40 cards, full search and page-local rating; inactive game polls stop and resume; hidden pages suspend visual work; idle study DOM is unchanged; 64px podium photos');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
