const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const source=fs.readFileSync('app.js','utf8');
function setup(){const values=new Map(),ctx={myId:'user',currentTextbook:'book',console,localStorage:{getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value)}};ctx.window=ctx;ctx.getVocabProgressStorageKey=()=> 'progress';ctx.extractUserProgressFromVocabList=()=>ctx.rendered;ctx.markVocabProgressDirty=()=>{};return {ctx,values};}
test('a single rating preserves unrendered and unchanged saved words',()=>{const {ctx,values}=setup();values.set('progress',JSON.stringify({1:{status:'bad'},2:{status:'ok'},3:{status:'ok'}}));ctx.rendered={1:{status:'ok'},2:{status:'none'}};const start=source.indexOf('window.saveVocabProgressLocally = function');vm.runInNewContext(source.slice(start,source.indexOf('// 変更のあった教材',start)),ctx);ctx.saveVocabProgressLocally(1);assert.deepEqual(JSON.parse(values.get('progress')),{1:{status:'ok'},2:{status:'ok'},3:{status:'ok'}});ctx.rendered={};ctx.saveVocabProgressLocally(null,true);assert.equal(JSON.parse(values.get('progress'))[3].status,'ok');});
test('loading a newer partial cloud snapshot preserves missing words without writing on read',async()=>{const {ctx,values}=setup();values.set('progress',JSON.stringify({1:{status:'bad'},2:{status:'ok'}}));values.set('progress__ts','1000');ctx.db={};ctx.fbDoc=()=> 'doc';ctx.fbGetDoc=async()=>({exists:()=>true,data:()=>({wordsJson:JSON.stringify({1:{status:'ok'}}),updatedAt:new Date(2000).toISOString()})});let writes=0;ctx.fbSetDoc=async()=>writes++;const start=source.indexOf('window.loadUserVocabProgress = async function',source.indexOf('// 【E】理解度リセット防止'));vm.runInNewContext(source.slice(start,source.indexOf('// ------------------------------------------------------------------',start)),ctx);await ctx.loadUserVocabProgress('book');assert.equal(JSON.parse(values.get('progress'))[2].status,'ok');assert.equal(writes,0);values.set('progress__ts','3000');await ctx.loadUserVocabProgress('book');assert.equal(writes,0);});
test('closing a stale displayed list cannot overwrite completed ratings or advance their edit date',async()=>{
 const {ctx,values}=setup();values.set('progress',JSON.stringify({1:{status:'ok'},2:{status:'bad'}}));values.set('progress__ts','1000');ctx.rendered={1:{status:'none'}};ctx.vocabList=[];ctx.userStats={};let flushed=0;ctx.AppStorage={flush:async()=>flushed++};
 const localStart=source.indexOf('window.saveVocabProgressLocally = function');vm.runInNewContext(source.slice(localStart,source.indexOf('// 変更のあった教材',localStart)),ctx);
 const start=source.indexOf('window.saveUserVocabProgress = async function()',source.indexOf('// 【E】理解度リセット防止'));vm.runInNewContext(source.slice(start,source.indexOf('window.loadUserVocabProgress = async function',start)),ctx);await ctx.saveUserVocabProgress();
 assert.deepEqual(JSON.parse(values.get('progress')),{1:{status:'ok'},2:{status:'bad'}});assert.equal(values.get('progress__ts'),'1000');assert.equal(flushed,1);
});
test('a full draft captures canonical ratings instead of a stale display',()=>{
 const {ctx,values}=setup();values.set('progress',JSON.stringify({1:{status:'ok'},2:{status:'bad'}}));ctx.vocabList=[{num:1}];ctx.rendered={1:{status:'none'}};ctx.__manualVocabDrafts={};ctx.__manualVocabLocalKey=()=> 'draft';ctx.stripVocabProgressFromWords=words=>words;
 const multi=fs.readFileSync('save-system.js','utf8'),start=multi.indexOf('window.__captureManualVocabDraft = function()');vm.runInNewContext(multi.slice(start,multi.indexOf('// 単語帳を閉じる時だけ',start)),ctx);
 const draft=ctx.__captureManualVocabDraft();assert.deepEqual(JSON.parse(JSON.stringify(draft.progress)),{1:{status:'ok'},2:{status:'bad'}});
});
