const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const type=process.env.BROWSER==='webkit'?webkit:chromium,browser=await type.launch(type===chromium?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:{executablePath:process.env.WEBKIT_EXECUTABLE_PATH});try{
const page=await browser.newPage({viewport:{width:393,height:852},deviceScaleFactor:3,userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Mobile Safari/604.1',isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('crash',()=>errors.push('renderer crash'));await page.route('https://**/*',r=>r.abort());await page.addInitScript(()=>{localStorage.setItem('b3_tutorial_done','1');Object.defineProperty(navigator,'standalone',{value:true});});await page.goto('http://127.0.0.1:8000');await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.waitForFunction(()=>__learningBootReady===true);
await page.evaluate(()=>{window.__gcLoginShown=true;document.querySelectorAll('.gcModal').forEach(el=>el.remove());myId='pwa-self';myName='検証';myFriendList=[{code:'user-000',name:'古いフレンド'}];window.db={};window.fbCollection=()=> 'users';window.fbQuery=(ref,...parts)=>({parts});window.fbOrderBy=()=>({order:true});window.fbDocumentId=()=> '__name__';window.fbLimit=count=>({limit:count});window.fbStartAfter=doc=>({after:doc.id});window.fbGetDoc=()=>new Promise(()=>{});window.fbRunTransaction=()=>new Promise(()=>{});window.fbSetDoc=async()=>{};window.__directoryRequests=[];window.__turns=0;window.__inflight=0;window.__maxInflight=0;window.fbGetDocs=async query=>{const cap=query.parts?.find(p=>p.limit)?.limit;if(!cap||cap>10)throw Error('unbounded users query');const after=query.parts.find(p=>p.after)?.after;const start=after?Number(after.slice(5))+1:0;__directoryRequests.push({tab:currentActiveTabId,start,cap});__inflight++;__maxInflight=Math.max(__maxInflight,__inflight);await new Promise(resolve=>setTimeout(resolve,3));__inflight--;const docs=Array.from({length:Math.max(0,Math.min(cap,65-start))},(_,i)=>{const index=start+i;return {id:'user-'+String(index).padStart(3,'0'),data:()=>{setTimeout(()=>__turns++,0);const day=StudyTimeModel.dateKey(Date.now());return {playerName:'利用者 '+index,lastActiveAt:Date.now()-(index===0?30:0)*86400000,userTarget:'目標 '+index,profileCustomizationJson:JSON.stringify({unused:'x'.repeat(300000)}),userStats:{unusedArtwork:'x'.repeat(300000)},studyLedgerJson:JSON.stringify({version:1,epoch:'study-reset-2.62',offset:0,days:{[day]:{sources:{test:(index+5)*60000}}}}),learningRankingV2Json:JSON.stringify({version:2,epoch:'learning-reset-3.52',words:{['word'+index]:1},flash:{baseline:0,sources:{phone:index+1}}})};}};});return {docs};};const canvas=document.createElement('canvas');canvas.width=1280;canvas.height=720;const ctx=canvas.getContext('2d');ctx.fillStyle='#ffca80';ctx.fillRect(0,0,1280,720);localStorage.setItem('aiglish_app_background_'+myId,JSON.stringify({mode:'photo',image:canvas.toDataURL('image/jpeg',.65),position:30,updatedAt:Date.now()}));toggleSidebar(true);toggleSidebar(false);StudyTime.init();});
await page.locator('#nav-study').click();await page.waitForFunction(()=>document.getElementById('studyRefreshRanking').disabled===false);assert.equal(await page.locator('.place-1 .study-podium-name').textContent(),'利用者64');assert.equal(await page.locator('.study-podium-name').count(),3);assert.ok(await page.evaluate(()=>__turns)>=60);
await page.locator('#nav-community').click();await page.getByRole('button',{name:'利用者 64のプロフィール'}).waitFor();assert.equal(await page.getByRole('button',{name:'利用者 0のプロフィール'}).count(),1);await page.locator('#nav-titles').click();await page.waitForFunction(()=>document.getElementById('rankingRefresh').disabled===false);assert.equal(await page.locator('[data-podium-metric="flash"] .place-1 .podium-name').textContent(),'利用者64');assert.ok(await page.evaluate(()=>__directoryRequests.every(request=>request.cap===10)));
// A large vocabulary stays paged; the three understanding colors remain distinct.
await page.evaluate(()=>{switchTab('vocab');document.getElementById('vocabLibrarySelection').hidden=true;document.getElementById('vocabBookContents').hidden=false;currentTextbook='pwa-book';vocabList=migrateVocabData(Array.from({length:2000},(_,i)=>({num:i+1,word:'word-'+(i+1),meaning:'意味 '+(i+1)})));textbooksPool=[{id:'pwa-book',name:'検証用'}];textbooksCacheMap['pwa-book']=vocabList;document.getElementById('vocabRangeStart').value=1;document.getElementById('vocabRangeEnd').value=2000;renderVocabList();['ok','so','bad'].forEach((status,i)=>updateMeaningStatus(i+1,vocabList[i].meanings[0].id,status));});assert.equal(await page.locator('#vocabListContainer .word-row-container').count(),40);const colors=await page.locator('#vocabListContainer .word-row-container').evaluateAll(rows=>rows.slice(0,3).map(row=>getComputedStyle(row).backgroundImage));assert.equal(new Set(colors).size,3);
const surfaces=[];for(const tab of ['study','reader','community','titles']){await page.evaluate(tab=>switchTab(tab),tab);const cards=await page.locator('.tab-view.active .card,.tab-view.active .ranking-mini-panel').evaluateAll(els=>els.map(el=>({background:getComputedStyle(el).backgroundColor,filter:getComputedStyle(el).backdropFilter})));surfaces.push(...cards);}assert.ok(surfaces.length>3);assert.ok(surfaces.every(style=>style.background==='rgba(15, 23, 42, 0.68)'&&style.filter==='none'),JSON.stringify(surfaces));
let metrics=null,before=null;if(type===chromium){const cdp=await page.context().newCDPSession(page);await cdp.send('Performance.enable');await cdp.send('HeapProfiler.collectGarbage');metrics=async()=>{await cdp.send('HeapProfiler.collectGarbage');return Object.fromEntries((await cdp.send('Performance.getMetrics')).metrics.map(m=>[m.name,m.value]));};before=await metrics();}
for(let round=0;round<4;round++){for(const tab of ['vocab','study','community','titles','reader'])await page.evaluate(tab=>switchTab(tab),tab);await page.waitForTimeout(600);if(metrics)assert.ok((await metrics()).JSHeapUsedSize-before.JSHeapUsedSize<12*1024*1024);}
assert.equal(await page.evaluate(()=>LearningData.read('pwa-book')[1].status),'ok');assert.equal(await page.evaluate(()=>getComputedStyle(document.body).isolation),'auto');await page.evaluate(()=>switchTab('study'));await page.screenshot({path:'/tmp/pwa-uniform-'+type.name()+'.png'});
// Emulate an unclean foreground renderer restart, keeping the original image and ratings.
await page.addInitScript(()=>localStorage.setItem('__aiglish_render_guard',JSON.stringify({active:true,at:Date.now()})));await page.reload();await page.waitForFunction(()=>__learningBootReady===true);assert.equal(await page.locator('html').evaluate(el=>el.classList.contains('pwa-recovery-rendering')),true);assert.equal(await page.evaluate(()=>getComputedStyle(document.body,'::after').backgroundImage),'none');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('core_v4_user_vocab_progress_pwa-self_pwa-book'))[1].status),'ok');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('aiglish_app_background_pwa-self')).mode),'photo');assert.deepEqual(errors,[]);
console.log('PASS '+type.name()+': DPR3 iOS/PWA; 65 large user profiles read in ten-row pages; daily/total/people views yield; uniform contrast; 2000-word book retains understanding colors; repeated navigation bounded; unclean restart suppresses photos without deleting data');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
