const {test}=require('node:test'),assert=require('node:assert/strict'),m=require('../ranking-query.js'),vm=require('node:vm'),fs=require('node:fs');
test('one calendar month is measured in JST and clamps the previous month end',()=>{assert.equal(new Date(m.monthAgo(Date.parse('2026-03-31T00:30:00Z'))).toISOString(),'2026-02-28T00:30:00.000Z');assert.equal(new Date(m.monthAgo(Date.parse('2026-10-10T15:00:00Z'))).toISOString(),'2026-09-10T15:00:00.000Z');});
test('old logins and invalid/future activity are excluded; legacy activity remains usable',()=>{const now=Date.parse('2026-10-11T00:00:00Z');assert.ok(m.eligible({lastLoginAt:'2026-09-11T00:00:00Z'},now));assert.ok(!m.eligible({lastLoginAt:'2026-09-10T23:59:59Z',lastActiveAt:now},now));assert.ok(m.eligible({lastActiveAt:now},now));assert.ok(!m.eligible({lastLoginAt:now+1},now));assert.ok(!m.eligible({lastActiveAt:'invalid'},now));assert.ok(!m.eligible({lastActiveAt:now,deleted:true},now));});
test('battle and learning projections never request unseen metrics or full progress',()=>{const now=Date.now(),battle=m.query('battle',now).select.fields.map(f=>f.fieldPath),learning=m.query('learning',now).select.fields.map(f=>f.fieldPath);assert.ok(battle.includes('wordDuelRating')&&!battle.includes('wordDuelSoloBest'));assert.ok(!battle.includes('rankingLearningSummaryV1'));assert.ok(learning.includes('rankingLearningSummaryV1'));assert.ok(!learning.includes('wordDuelSoloBest'));assert.ok([...battle,...learning].every(field=>!m.legacy.includes(field)));const cursor={name:'projects/test/databases/(default)/documents/users/a',fields:{lastActiveAt:{stringValue:new Date(now).toISOString()}}};assert.equal(m.query('battle',now,cursor).startAt.before,false);assert.equal(m.query('battle',now).limit,20);});
test('a summary from a retired learning or study epoch cannot silently hide current data',()=>{const good={epoch:'learning-reset-3.52',studyEpoch:'study-reset-2.62',time:10,words:3,flash:5};assert.deepEqual(m.summary({rankingLearningSummaryV1:good}),good);assert.equal(m.summary({rankingLearningSummaryV1:{...good,studyEpoch:'old'}}),null);assert.equal(m.summary({rankingLearningSummaryV1:{...good,words:-1}}),null);});
function setup(responses){const calls=[],ctx={db:{app:{options:{projectId:'test-project'}}},Date,setTimeout,DOMException,console,fetch:async(url,options)=>{calls.push({url,body:JSON.parse(options.body),signal:options.signal});return responses.shift();}};ctx.window=ctx;vm.runInNewContext(fs.readFileSync('ranking-query.js','utf8'),ctx);return {ctx,calls};}
const response=data=>({ok:true,json:async()=>data});
const doc=(id,extra={})=>({name:'projects/test-project/databases/(default)/documents/users/'+id,fields:{playerName:{stringValue:id},lastActiveAt:{stringValue:new Date().toISOString()},...extra}});
test('only eligible legacy learning rows trigger a masked fallback; battle never does',async()=>{const old={lastLoginAt:{stringValue:'2020-01-01T00:00:00Z'}},a=doc('a'),b=doc('b',old),legacy=doc('a',{learningRankingV2Json:{stringValue:'saved-record'}});const {ctx,calls}=setup([response([{document:a},{document:b}]),response([{found:legacy}])]);const rows=await ctx.RankingQuery.fetch('learning',{now:Date.now()+1000});assert.equal(rows.length,1);assert.equal(rows[0].data.learningRankingV2Json,'saved-record');assert.equal(calls.length,2);assert.equal(calls[1].body.documents.length,1);assert.deepEqual(calls[1].body.mask.fieldPaths,m.legacy);const battle=setup([response([{document:a}])]);assert.equal((await battle.ctx.RankingQuery.fetch('battle',{now:Date.now()+1000})).length,1);assert.equal(battle.calls.length,1);});
test('a quota error throws instead of returning an empty leaderboard',async()=>{const {ctx}=setup([{ok:false,status:429,json:async()=>({error:{message:'Quota exceeded'}})}]);await assert.rejects(ctx.RankingQuery.fetch('battle'),{code:'resource-exhausted'});});
