const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const type=process.env.BROWSER==='webkit'?webkit:chromium,browser=await type.launch(type===chromium?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:{executablePath:process.env.WEBKIT_EXECUTABLE_PATH});try{
 const page=await browser.newPage({viewport:{width:393,height:852}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('crash',()=>errors.push('renderer crashed'));await page.route('https://**/*',r=>r.abort());await page.addInitScript(()=>localStorage.setItem('b3_tutorial_done','1'));await page.goto('http://127.0.0.1:8000');await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.waitForFunction(()=>__learningBootReady===true);
 await page.evaluate(()=>{window.__gcLoginShown=true;document.querySelectorAll('.gcModal').forEach(el=>el.remove());myId='load-self';myName='読み込み確認';userStats={};currentTextbook='load-book';vocabList=migrateVocabData([{num:1,word:'study',meaning:'学ぶ'}]);textbooksPool=[{id:'load-book',name:'クイズ用'}];textbooksCacheMap['load-book']=stripVocabProgressFromWords(vocabList);localStorage.setItem('core_v4_loadquiz_book','auto');window.db={};window.fbCollection=()=> 'users';window.fbDoc=(_, ...parts)=>parts.join('/');window.fbRunTransaction=()=>new Promise(()=>{});window.fbQuery=(_, ...parts)=>({parts});window.fbOrderBy=()=>({order:true});window.fbDocumentId=()=> '__name__';window.fbLimit=count=>({limit:count});window.fbStartAfter=doc=>({after:doc.id});window.__pages=[];window.__uiTurns=0;window.__rankRows=Array.from({length:120},(_,i)=>({id:'u-'+String(i).padStart(3,'0'),data:()=>({playerName:'利用者 '+i,profileCustomizationJson:'unused:'+ 'x'.repeat(200000),learningRankingV2Json:JSON.stringify({version:2,epoch:'learning-reset-3.52',words:{['word'+i]:1},flash:{baseline:0,sources:{phone:i+1}}})})}));window.fbGetDocs=async query=>{const cursor=query.parts?.find(p=>p.after)?.after;const start=cursor?__rankRows.findIndex(d=>d.id===cursor)+1:0;__pages.push(start);if(start===0)await new Promise(resolve=>window.__releaseRank=resolve);setTimeout(()=>__uiTurns++,0);const docs=__rankRows.slice(start,start+50);return {docs,forEach:fn=>docs.forEach(fn)};};window.fbGetDoc=()=>new Promise(()=>{});window.__oldTabHandlers=__tabChangeHandlers.length;});
 await page.locator('#nav-titles').click();await page.locator('#penguinLoadingOverlay #lqCard').waitFor({state:'visible'});assert.match(await page.locator('#penguinLoadingOverlay').textContent(),/ランキング/);
 await page.evaluate(()=>{__loadQuiz.answers.push({num:1,word:'study',status:'ok'});__releaseRank();});await page.waitForFunction(()=>document.getElementById('rankingRefresh').disabled===false);await page.waitForFunction(()=>!document.getElementById('penguinLoadingOverlay'));
 assert.deepEqual(await page.evaluate(()=>__pages),[0,50,100]);assert.ok(await page.evaluate(()=>__uiTurns)>=2);assert.equal(await page.locator('[data-podium-metric="flash"] .place-1 .podium-name').textContent(),'利用者119');assert.equal(await page.evaluate(()=>LearningData.read('load-book')[1].status),'ok');assert.equal(await page.evaluate(()=>__tabChangeHandlers.length),await page.evaluate(()=>__oldTabHandlers));
 // Cached detail opens even if a fresh detail request never completes.
 await page.getByRole('button',{name:'フラッシュのスワイプ数 1位 利用者 119の詳細'}).click();await page.locator('dialog.library-editor-dialog').waitFor({state:'visible'});assert.equal(await page.locator('dialog dd').last().textContent(),'120回');await page.getByRole('button',{name:'閉じる',exact:true}).click();
 // Background refresh retains the old podium, without a quiz or flickering replacement.
 await page.evaluate(()=>{window.__stableRank=document.querySelector('[data-podium-metric="flash"] .place-1');window.__secondRefresh=LearningRanking.refresh(true);});await page.waitForFunction(()=>typeof __releaseRank==='function');await page.waitForTimeout(350);assert.equal(await page.locator('#penguinLoadingOverlay').count(),0);await page.evaluate(()=>__releaseRank());await page.evaluate(()=>__secondRefresh);assert.equal(await page.evaluate(()=>__stableRank===document.querySelector('[data-podium-metric="flash"] .place-1')),true);
 // A missing response is bounded; late results cannot replace a newer successful refresh.
 await page.evaluate(()=>{const native=setTimeout;window.setTimeout=(fn,ms,...args)=>native(fn,ms===15000?800:ms,...args);window.__timedRefresh=LearningRanking.refresh(true,true);});await page.locator('#penguinLoadingOverlay').waitFor({state:'visible'});await page.evaluate(()=>__timedRefresh);await page.waitForFunction(()=>!document.getElementById('penguinLoadingOverlay'));assert.equal(await page.locator('#rankingRefresh').isEnabled(),true);assert.match(await page.locator('#rankingMessage').textContent(),/再試行/);await page.evaluate(()=>__releaseRank());assert.equal(await page.evaluate(()=>__stableRank===document.querySelector('[data-podium-metric="flash"] .place-1')),true);
 assert.deepEqual(errors,[]);console.log('PASS '+type.name()+': ranking does not wait for blocked sync; 50-row pages yield; delayed quiz answers retained; details immediate; cache stable; timeout releases UI and discards late results; no listener leak');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
