const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const type=process.env.BROWSER==='webkit'?webkit:chromium,browser=await type.launch(type===chromium?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:{executablePath:process.env.WEBKIT_EXECUTABLE_PATH});try{
 const page=await browser.newPage({viewport:{width:393,height:852}}),errors=[],requests=[],releases=[];let hold=true,fail=false;
 page.on('pageerror',e=>errors.push(e.message));page.on('crash',()=>errors.push('renderer crashed'));
 await page.route('https://**/*',r=>r.abort());
 const encoded=value=>typeof value==='string'?{stringValue:value}:typeof value==='number'?{integerValue:String(value)}:typeof value==='boolean'?{booleanValue:value}:{mapValue:{fields:Object.fromEntries(Object.entries(value).map(([key,v])=>[key,encoded(v)]))}};
 const now=Date.now(),rows=Array.from({length:42},(_,i)=>({id:'u-'+String(i).padStart(3,'0'),data:{playerName:'利用者 '+i,lastActiveAt:new Date(now-1000).toISOString(),lastLoginAt:new Date(now-1000).toISOString(),wordDuelRating:1500+i,wordDuelSoloBest:i*100,rankingLearningSummaryV1:{epoch:'learning-reset-3.52',studyEpoch:'study-reset-2.62',time:i*60,words:i+1,flash:i+1}}}));
 rows.push({id:'old-user',data:{playerName:'以前のログイン',lastActiveAt:new Date(now).toISOString(),lastLoginAt:'2020-01-01T00:00:00Z',wordDuelRating:9999,wordDuelSoloBest:999999,rankingLearningSummaryV1:{epoch:'learning-reset-3.52',studyEpoch:'study-reset-2.62',time:999999,words:99999,flash:99999}}});
 await page.route('https://firestore.googleapis.com/v1/projects/ranking-test/**',async route=>{
  const body=route.request().postDataJSON();requests.push(body);if(!body.structuredQuery)throw Error('unexpected unmasked/legacy read');const q=body.structuredQuery,after=q.startAt?.values[1]?.referenceValue.split('/').pop(),start=after?rows.findIndex(row=>row.id===after)+1:0;
  if(start===0&&hold)await new Promise(resolve=>releases.push(resolve));
  if(fail){await route.fulfill({status:429,contentType:'application/json',body:JSON.stringify({error:{message:'Quota exceeded'}})}).catch(()=>{});return;}
  const data=rows.slice(start,start+q.limit).map(row=>({document:{name:'projects/ranking-test/databases/(default)/documents/users/'+row.id,fields:Object.fromEntries(q.select.fields.filter(({fieldPath})=>fieldPath in row.data).map(({fieldPath})=>[fieldPath,encoded(row.data[fieldPath])]))}}));
  await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)}).catch(()=>{});
 });
 await page.goto('http://127.0.0.1:8000');await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.waitForFunction(()=>__learningBootReady===true);
 await page.evaluate(()=>{myId='load-self';myName='読み込み確認';userStats={};currentTextbook='load-book';vocabList=migrateVocabData([{num:1,word:'study',meaning:'学ぶ'}]);textbooksPool=[{id:'load-book',name:'クイズ用'}];textbooksCacheMap['load-book']=stripVocabProgressFromWords(vocabList);localStorage.setItem('core_v4_loadquiz_book','auto');window.db={app:{options:{projectId:'ranking-test'}}};window.fbDoc=(_, ...parts)=>parts.join('/');window.fbRunTransaction=()=>new Promise(()=>{});window.fbGetDoc=()=>new Promise(()=>{});window.fbGetDocs=()=>{throw Error('full collection scan is forbidden');};window.__oldTabHandlers=__tabChangeHandlers.length;});
 await page.locator('#nav-titles').click();await page.locator('#penguinLoadingOverlay #lqCard').waitFor({state:'visible'});assert.match(await page.locator('#penguinLoadingOverlay').textContent(),/ランキング/);
 await page.evaluate(()=>__loadQuiz.answers.push({num:1,word:'study',status:'ok'}));hold=false;releases.shift()();await page.waitForFunction(()=>document.getElementById('rankingRefresh').disabled===false);await page.waitForFunction(()=>!document.getElementById('penguinLoadingOverlay'));
 assert.equal(requests.length,3);assert.equal(requests.every(body=>body.structuredQuery.limit===20),true);assert.equal(requests.some(body=>body.structuredQuery.select.fields.some(f=>['wordDuelRating','wordDuelSoloBest','userStatsJson','studyLedgerJson'].includes(f.fieldPath))),false);
 assert.equal(await page.locator('[data-podium-metric="flash"] .place-1 .podium-name').textContent(),'利用者41');assert.equal(await page.evaluate(()=>LearningData.read('load-book')[1].status),'ok');assert.equal(await page.evaluate(()=>__tabChangeHandlers.length),await page.evaluate(()=>__oldTabHandlers));
 await page.getByRole('button',{name:'フラッシュのスワイプ数 1位 利用者 41の詳細'}).click();await page.locator('dialog.library-editor-dialog').waitFor({state:'visible'});assert.equal(await page.locator('dialog dd').last().textContent(),'42回');await page.getByRole('button',{name:'閉じる',exact:true}).click();
 await page.evaluate(()=>window.__stableRank=document.querySelector('[data-podium-metric="flash"] .place-1'));
 await page.getByRole('button',{name:'単語バトル',exact:true}).click();await page.locator('[data-podium-metric="solo"] .place-1 strong').waitFor();assert.equal(await page.locator('.ranking-mini-panel').count(),2);assert.equal(await page.locator('[data-podium-metric="rating"] .place-1 strong').textContent(),'1541');assert.equal(await page.locator('[data-podium-metric="solo"] .place-1 strong').textContent(),'4,100点');assert.equal(requests.length,6);
 for(const body of requests.slice(3)){const fields=body.structuredQuery.select.fields.map(f=>f.fieldPath);assert.ok(fields.includes('wordDuelRating')&&fields.includes('wordDuelSoloBest'));assert.ok(!fields.includes('rankingLearningSummaryV1'));}
 for(const viewport of [{width:393,height:852},{width:320,height:668}]){await page.setViewportSize(viewport);await page.waitForTimeout(350);const fit=await page.locator('.ranking-mini-panel').evaluateAll(panels=>panels.every(panel=>[...panel.querySelectorAll('.learning-podium-place')].every(column=>column.getBoundingClientRect().bottom<=panel.getBoundingClientRect().bottom+1)));assert.equal(fit,true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
 await page.screenshot({path:'/tmp/ranking-battle-'+type.name()+'.png'});
 await page.getByRole('button',{name:'学習',exact:true}).click();await page.locator('[data-podium-metric="flash"] .place-1 strong').waitFor();assert.equal(requests.length,6,'switching to a cached group must not read again');
 // Forced background reads preserve the existing DOM, then timeout cleanly.
 hold=true;await page.evaluate(()=>{window.__stableRank=document.querySelector('[data-podium-metric="flash"] .place-1');window.__refresh=LearningRanking.refresh(true);});await page.waitForTimeout(350);assert.equal(await page.locator('#penguinLoadingOverlay').count(),0);hold=false;releases.shift()();await page.evaluate(()=>__refresh);assert.equal(await page.evaluate(()=>__stableRank===document.querySelector('[data-podium-metric="flash"] .place-1')),true);
 hold=true;await page.evaluate(()=>{const native=setTimeout;window.setTimeout=(fn,ms,...args)=>native(fn,ms===15000?800:ms,...args);window.__refresh=LearningRanking.refresh(true,true);});await page.locator('#penguinLoadingOverlay').waitFor({state:'visible'});await page.evaluate(()=>__refresh);await page.waitForFunction(()=>!document.getElementById('penguinLoadingOverlay'));assert.equal(await page.locator('#rankingRefresh').isEnabled(),true);assert.match(await page.locator('#rankingMessage').textContent(),/再試行/);hold=false;releases.shift()();
 // Leaving a pending read cancels it, releases the loader and cannot replace another mode.
 hold=true;await page.evaluate(()=>window.__refresh=LearningRanking.refresh(true,true));await page.locator('#penguinLoadingOverlay').waitFor({state:'visible'});await page.evaluate(()=>switchTab('reader'));await page.evaluate(()=>__refresh);await page.waitForFunction(()=>!document.getElementById('penguinLoadingOverlay'));hold=false;releases.shift()();
 assert.deepEqual(errors,[]);console.log('PASS '+type.name()+': projected 20-row pages, only visible metrics, recent logins only, both battle podiums fit 393/320px, independent group caches, loading quiz preserves understanding, stable refresh, abort/timeout cleanup');
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exit(1)});
