const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict');
(async()=>{
 const type=process.env.BROWSER==='webkit'?webkit:chromium,browser=await type.launch(type===chromium?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:{executablePath:process.env.WEBKIT_EXECUTABLE_PATH});
 const records=new Map();let writes=0;const errors=[];
 async function device(){const context=await browser.newContext({viewport:{width:393,height:852}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());await page.exposeFunction('catalogRead',path=>structuredClone(records.get(path)||null));await page.exposeFunction('catalogWrite',(path,value)=>{writes++;records.set(path,structuredClone(value));});await page.exposeFunction('catalogCommit',(generation,value)=>{if((records.get('shared/backgrounds')?.generation||'')!==generation)return false;writes++;records.set('shared/backgrounds',structuredClone(value));return true;});await context.addInitScript(()=>{window.__installSharedBackend=()=>{window.db={};window.fbDoc=(db,...path)=>path.join('/');const snapshot=value=>({exists:()=>value!==null,data:()=>value});window.fbGetDocFromServer=window.fbGetDoc=async path=>{if(window.__quota){const error=Error('Quota exceeded');error.code='resource-exhausted';throw error;}if(window.__denyReads)throw Error('offline');return snapshot(await catalogRead(path));};window.fbSetDoc=async(path,value)=>{if(window.__denyWrites)throw Error('permission-denied');await catalogWrite(path,value);};window.fbRunTransaction=async(db,fn)=>{let generation='',value;const result=await fn({get:async path=>{const record=await catalogRead(path);generation=record?.generation||'';return snapshot(record);},set:(path,next)=>value=next});if(!result)return false;return catalogCommit(generation,value);};window.dispatchEvent(new Event('firebase-ready'));};});await page.goto('http://127.0.0.1:8000');await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.waitForFunction(()=>window.__learningBootReady===true);await page.evaluate(()=>__installSharedBackend());return {context,page};}
 const admin=await device(),viewer=await device();
 async function openAdmin(page){await page.evaluate(()=>toggleSidebar(true));await page.locator('#sidebarBackgroundAdmin').click();await page.locator('#backgroundAdminPassword').fill('tukinokopanda');await page.locator('#backgroundAdminAuth button').click();await page.waitForFunction(()=>document.querySelector('#sidebarBackgroundFile')?.disabled===false);}
 const fixture=await admin.page.evaluate(()=>{const c=document.createElement('canvas');c.width=1000;c.height=700;c.getContext('2d').fillRect(0,0,1000,700);return c.toDataURL('image/jpeg').split(',')[1];});
 // Existing personal artwork migrates only after the existing administrator password gate.
 await admin.page.evaluate(async data=>{localStorage.setItem('aiglish_app_background_catalog_'+myId,JSON.stringify({backgrounds:[{id:'old-admin-photo',image:'data:image/jpeg;base64,'+data,position:35}],updatedAt:1}));localStorage.setItem('aiglish_app_background_'+myId,JSON.stringify({mode:'photo',selected:'old-admin-photo',updatedAt:1}));await AppStorage.flush();},fixture);
 await admin.page.evaluate(()=>toggleSidebar(true));await admin.page.locator('#sidebarBackgroundAdmin').click();await admin.page.locator('#backgroundAdminPassword').fill('wrong');await admin.page.locator('#backgroundAdminAuth button').click();assert.equal(writes,0);await admin.page.evaluate(()=>__quota=true);await admin.page.locator('#backgroundAdminPassword').fill('tukinokopanda');await admin.page.locator('#backgroundAdminAuth button').click();await admin.page.locator('#backgroundAdminSaveStatus').filter({hasText:'利用上限'}).waitFor();assert.equal(await admin.page.locator('#backgroundAdminRetry').isVisible(),true);assert.equal(writes,0);assert.ok(await admin.page.evaluate(()=>localStorage.getItem('aiglish_app_background_catalog_'+myId).includes('old-admin-photo')));await admin.page.evaluate(()=>__quota=false);await admin.page.locator('#backgroundAdminRetry').click();await admin.page.locator('#backgroundAdminSaveStatus').filter({hasText:'以前の背景も全ユーザーに共有しました'}).waitFor();
 await viewer.page.evaluate(async()=>{__quota=true;try{await BackgroundCatalog.refresh(true)}catch(e){}});await viewer.page.locator('#headerBackgroundButton').click();await viewer.page.locator('#backgroundPickerStatus').filter({hasText:'利用上限'}).waitFor();assert.equal(await viewer.page.locator('#backgroundPickerRetry').isVisible(),true);assert.equal(await viewer.page.locator('[data-background="old-admin-photo"]').count(),0);await viewer.page.evaluate(()=>__quota=false);await viewer.page.locator('#backgroundPickerRetry').click();await viewer.page.locator('[data-background="old-admin-photo"]').waitFor();assert.equal(await viewer.page.locator('[data-background="old-admin-photo"]').count(),1);assert.equal(await viewer.page.locator('[data-background="default"]').getAttribute('aria-pressed'),'true');await viewer.page.locator('[data-background="old-admin-photo"]').click();await viewer.page.locator('#backgroundPickerStatus').filter({hasText:'背景を保存しました'}).waitFor();await viewer.page.locator('#backgroundPickerClose').click();
 // Explicit registration is acknowledged after a committed shared manifest, not just a local write.
 await admin.page.locator('#sidebarBackgroundFile').setInputFiles({name:'new.jpg',mimeType:'image/jpeg',buffer:Buffer.from(fixture,'base64')});await admin.page.locator('#backgroundAdminRegister').click();await admin.page.locator('#backgroundAdminSaveStatus').filter({hasText:'写真を登録しました'}).waitFor();assert.equal(await admin.page.locator('#backgroundAdminSelection option').count(),2);await viewer.page.evaluate(()=>BackgroundCatalog.refresh(true));await viewer.page.locator('#headerBackgroundButton').click();assert.equal(await viewer.page.locator('[data-background]:not([data-background="default"])').count(),2);assert.equal(await viewer.page.locator('[data-background="old-admin-photo"]').getAttribute('aria-pressed'),'true');await viewer.page.locator('#backgroundPickerClose').click();
 // A fresh browser context sees the shared catalogue, without receiving another user's choice.
 const fresh=await device();await fresh.page.waitForFunction(()=>BackgroundCatalog.readCache()?.backgrounds.length===2);await fresh.page.locator('#headerBackgroundButton').click();assert.equal(await fresh.page.locator('[data-background]:not([data-background="default"])').count(),2);assert.equal(await fresh.page.locator('[data-background="default"]').getAttribute('aria-pressed'),'true');await fresh.page.locator('#backgroundPickerClose').click();
 const manifest=structuredClone(records.get('shared/backgrounds'));await admin.page.evaluate(()=>__denyWrites=true);await admin.page.locator('#sidebarBackgroundFile').setInputFiles({name:'retry.jpg',mimeType:'image/jpeg',buffer:Buffer.from(fixture,'base64')});await admin.page.locator('#backgroundAdminRegister').click();await admin.page.locator('#backgroundAdminSaveStatus').filter({hasText:'保存できませんでした'}).waitFor();assert.deepEqual(records.get('shared/backgrounds'),manifest);await admin.page.evaluate(()=>__denyWrites=false);await admin.page.locator('#backgroundAdminRegister').click();await admin.page.locator('#backgroundAdminSaveStatus').filter({hasText:'写真を登録しました'}).waitFor();assert.equal(await admin.page.locator('#backgroundAdminSelection option').count(),3);
 // Deleted global artwork cannot be resurrected by the administrator's old personal catalogue.
 await admin.page.locator('#backgroundAdminSelection').selectOption('old-admin-photo');await admin.page.locator('#backgroundAdminDelete').click();await admin.page.locator('#backgroundAdminSaveStatus').filter({hasText:'背景を保存しました'}).waitFor();await admin.page.locator('#backgroundAdminClose').click();await admin.page.locator('#headerBackgroundButton').click();assert.equal(await admin.page.locator('[data-background="old-admin-photo"]').count(),0);await viewer.page.evaluate(()=>BackgroundCatalog.refresh(true));await viewer.page.locator('#headerBackgroundButton').click();assert.equal(await viewer.page.locator('[data-background="old-admin-photo"]').count(),0);assert.equal(await viewer.page.locator('[data-background="default"]').getAttribute('aria-pressed'),'true');const retained=await viewer.page.locator('[data-background]:not([data-background="default"])').first().getAttribute('data-background');await viewer.page.locator('[data-background="'+retained+'"]').click();await viewer.page.locator('#backgroundPickerStatus').filter({hasText:'背景を保存しました'}).waitFor();await viewer.page.locator('#backgroundPickerClose').click();
 // Offline clients retain the confirmed shared cache across reloads.
 await viewer.page.reload();await viewer.page.waitForFunction(()=>window.__learningBootReady===true);await viewer.page.evaluate(()=>{__installSharedBackend();__denyReads=true;});await viewer.page.locator('#headerBackgroundButton').click();assert.equal(await viewer.page.locator('[data-background]:not([data-background="default"])').count(),2);assert.equal(await viewer.page.locator('[data-background="'+retained+'"]').getAttribute('aria-pressed'),'true');const before=await viewer.page.evaluate(()=>localStorage.getItem(BackgroundCatalog.cacheKey));await assert.rejects(viewer.page.evaluate(()=>BackgroundCatalog.refresh(true)));assert.equal(await viewer.page.evaluate(()=>localStorage.getItem(BackgroundCatalog.cacheKey)),before);
 // Optimistic concurrent publishers merge against the latest manifest rather than losing an addition.
 await viewer.page.evaluate(()=>__denyReads=false);await Promise.all([viewer.page.evaluate(data=>BackgroundCatalog.publish({upserts:[{id:'concurrent-a',image:'data:image/jpeg;base64,'+data,position:50}]}),fixture),fresh.page.evaluate(data=>BackgroundCatalog.publish({upserts:[{id:'concurrent-b',image:'data:image/jpeg;base64,'+data,position:50}]}),fixture)]);await viewer.page.evaluate(()=>BackgroundCatalog.refresh(true));const ids=await viewer.page.evaluate(()=>BackgroundCatalog.readCache().backgrounds.map(item=>item.id));assert.ok(ids.includes('concurrent-a')&&ids.includes('concurrent-b'));// Larger photographs use bounded chunks; an incomplete generation never replaces the cache.
 const largePhoto=await viewer.page.evaluate(()=>{const c=document.createElement('canvas');c.width=960;c.height=540;const ctx=c.getContext('2d'),data=ctx.createImageData(960,540);for(let i=0;i<data.data.length;i+=4){data.data[i]=Math.random()*256;data.data[i+1]=Math.random()*256;data.data[i+2]=Math.random()*256;data.data[i+3]=255;}ctx.putImageData(data,0,0);return c.toDataURL('image/jpeg',.9);});await viewer.page.evaluate(image=>BackgroundCatalog.publish({upserts:[{id:'chunked-photo',image,position:50}]}),largePhoto);assert.ok(records.get('shared/backgrounds').partCount>1);for(const [path,value] of records)if(path.startsWith('shared/backgrounds/parts/'))assert.ok(value.d.length<=280000);const stable=await viewer.page.evaluate(()=>localStorage.getItem(BackgroundCatalog.cacheKey)),latest=structuredClone(records.get('shared/backgrounds'));records.set('shared/backgrounds',{...latest,generation:'missing-parts'});await assert.rejects(viewer.page.evaluate(()=>BackgroundCatalog.refresh(true)));assert.equal(await viewer.page.evaluate(()=>localStorage.getItem(BackgroundCatalog.cacheKey)),stable);records.set('shared/backgrounds',latest);
 assert.equal(await viewer.page.evaluate(()=>window.__collectGameSaveData().localStorage[BackgroundCatalog.cacheKey]),undefined);assert.deepEqual(errors,[]);
 console.log('PASS '+type.name()+': quota errors shown; immediate user/admin retry without losing photos; late Firebase initialization; password-gated legacy migration; registration shared across three isolated browsers; independent selection; denied publish/retry; global deletion tombstones; offline durable cache; concurrent publishers retain additions');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
