const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict');
(async()=>{
 const type=process.env.BROWSER==='webkit'?webkit:chromium,browser=await type.launch(type===chromium?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:{executablePath:process.env.WEBKIT_EXECUTABLE_PATH});
 const records=new Map();let writes=0;const errors=[];
 async function device(){const context=await browser.newContext({viewport:{width:393,height:852}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());await page.exposeFunction('catalogRead',path=>structuredClone(records.get(path)||null));await page.exposeFunction('catalogWrite',(path,value)=>{writes++;records.set(path,structuredClone(value));});await page.exposeFunction('catalogCommit',(generation,value)=>{if((records.get('shared/backgrounds')?.generation||'')!==generation)return false;writes++;records.set('shared/backgrounds',structuredClone(value));return true;});await context.addInitScript(()=>{window.__installSharedBackend=()=>{window.db={};window.fbDoc=(db,...path)=>path.join('/');const snapshot=value=>({exists:()=>value!==null,data:()=>value});window.fbGetDocFromServer=window.fbGetDoc=async path=>{if(window.__denyReads)throw Error('offline');return snapshot(await catalogRead(path));};window.fbSetDoc=async(path,value)=>{if(window.__denyWrites)throw Error('permission-denied');await catalogWrite(path,value);};window.fbRunTransaction=async(db,fn)=>{let generation='',value;const result=await fn({get:async path=>{const record=await catalogRead(path);generation=record?.generation||'';return snapshot(record);},set:(path,next)=>value=next});if(!result)return false;return catalogCommit(generation,value);};};});await page.goto('http://127.0.0.1:8000');await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.waitForFunction(()=>window.__learningBootReady===true);await page.evaluate(()=>__installSharedBackend());return {context,page};}
 const admin=await device(),viewer=await device();
 const fixture=await admin.page.evaluate(()=>{const c=document.createElement('canvas');c.width=1000;c.height=700;c.getContext('2d').fillRect(0,0,1000,700);return c.toDataURL('image/jpeg').split(',')[1];});
 // Seed previously registered backgrounds through the isolated backend, not a removed UI.
 await admin.page.evaluate(async data=>{await BackgroundCatalog.publish({upserts:[{id:'old-admin-photo',image:'data:image/jpeg;base64,'+data,position:35},{id:'existing-second-photo',image:'data:image/jpeg;base64,'+data,position:50}]});},fixture);
 await viewer.page.evaluate(()=>BackgroundCatalog.refresh(true));await viewer.page.locator('#headerBackgroundButton').click();await viewer.page.locator('[data-background="old-admin-photo"]').click();await viewer.page.locator('#backgroundPickerStatus').filter({hasText:'背景を保存しました'}).waitFor();await viewer.page.locator('#backgroundPickerClose').click();
 assert.equal(await admin.page.locator('#sidebarBackgroundAdmin, #backgroundAdminTemplate').count(),0);
 // A fresh browser context sees the shared catalogue, without receiving another user's choice.
 const fresh=await device();await fresh.page.evaluate(()=>BackgroundCatalog.refresh(true));await fresh.page.locator('#headerBackgroundButton').click();assert.equal(await fresh.page.locator('[data-background]:not([data-background="default"]):not([data-background^="bundled-"])').count(),2);assert.equal(await fresh.page.locator('[data-background="default"]').getAttribute('aria-pressed'),'true');await fresh.page.locator('#backgroundPickerClose').click();
 // Previously deleted IDs still suppress old personal catalogues.
 await admin.page.evaluate(data=>localStorage.setItem('aiglish_app_background_catalog_'+myId,JSON.stringify({backgrounds:[{id:'old-admin-photo',image:'data:image/jpeg;base64,'+data,position:35}]})),fixture);
 await admin.page.evaluate(()=>BackgroundCatalog.publish({remove:['old-admin-photo']}));await admin.page.locator('#headerBackgroundButton').click();assert.equal(await admin.page.locator('[data-background="old-admin-photo"]').count(),0);await admin.page.locator('#backgroundPickerClose').click();
 await viewer.page.evaluate(()=>BackgroundCatalog.refresh(true));await viewer.page.locator('#headerBackgroundButton').click();assert.equal(await viewer.page.locator('[data-background="old-admin-photo"]').count(),0);assert.equal(await viewer.page.locator('[data-background="default"]').getAttribute('aria-pressed'),'true');const retained='existing-second-photo';await viewer.page.locator('[data-background="'+retained+'"]').click();await viewer.page.locator('#backgroundPickerStatus').filter({hasText:'背景を保存しました'}).waitFor();await viewer.page.locator('#backgroundPickerClose').click();
 // Offline clients retain the confirmed shared cache across reloads.
 await viewer.page.reload();await viewer.page.waitForFunction(()=>window.__learningBootReady===true);await viewer.page.evaluate(()=>{__installSharedBackend();__denyReads=true;});await viewer.page.locator('#headerBackgroundButton').click();assert.equal(await viewer.page.locator('[data-background]:not([data-background="default"]):not([data-background^="bundled-"])').count(),1);assert.equal(await viewer.page.locator('[data-background="'+retained+'"]').getAttribute('aria-pressed'),'true');const before=await viewer.page.evaluate(()=>localStorage.getItem(BackgroundCatalog.cacheKey));await assert.rejects(viewer.page.evaluate(()=>BackgroundCatalog.refresh(true)));assert.equal(await viewer.page.evaluate(()=>localStorage.getItem(BackgroundCatalog.cacheKey)),before);
 // Optimistic concurrent publishers merge against the latest manifest rather than losing an addition.
 await viewer.page.evaluate(()=>__denyReads=false);await Promise.all([viewer.page.evaluate(data=>BackgroundCatalog.publish({upserts:[{id:'concurrent-a',image:'data:image/jpeg;base64,'+data,position:50}]}),fixture),fresh.page.evaluate(data=>BackgroundCatalog.publish({upserts:[{id:'concurrent-b',image:'data:image/jpeg;base64,'+data,position:50}]}),fixture)]);await viewer.page.evaluate(()=>BackgroundCatalog.refresh(true));const ids=await viewer.page.evaluate(()=>BackgroundCatalog.readCache().backgrounds.map(item=>item.id));assert.ok(ids.includes('concurrent-a')&&ids.includes('concurrent-b'));// Larger photographs use bounded chunks; an incomplete generation never replaces the cache.
 const largePhoto=await viewer.page.evaluate(()=>{const c=document.createElement('canvas');c.width=960;c.height=540;const ctx=c.getContext('2d'),data=ctx.createImageData(960,540);for(let i=0;i<data.data.length;i+=4){data.data[i]=Math.random()*256;data.data[i+1]=Math.random()*256;data.data[i+2]=Math.random()*256;data.data[i+3]=255;}ctx.putImageData(data,0,0);return c.toDataURL('image/jpeg',.9);});await viewer.page.evaluate(image=>BackgroundCatalog.publish({upserts:[{id:'chunked-photo',image,position:50}]}),largePhoto);assert.ok(records.get('shared/backgrounds').partCount>1);for(const [path,value] of records)if(path.startsWith('shared/backgrounds/parts/'))assert.ok(value.d.length<=280000);const stable=await viewer.page.evaluate(()=>localStorage.getItem(BackgroundCatalog.cacheKey)),latest=structuredClone(records.get('shared/backgrounds'));records.set('shared/backgrounds',{...latest,generation:'missing-parts'});await assert.rejects(viewer.page.evaluate(()=>BackgroundCatalog.refresh(true)));assert.equal(await viewer.page.evaluate(()=>localStorage.getItem(BackgroundCatalog.cacheKey)),stable);records.set('shared/backgrounds',latest);
 assert.equal(await viewer.page.evaluate(()=>window.__collectGameSaveData().localStorage[BackgroundCatalog.cacheKey]),undefined);assert.deepEqual(errors,[]);
 console.log('PASS '+type.name()+': existing shared backgrounds across three isolated browsers; removed admin UI; independent selection; global deletion tombstones; offline durable cache; concurrent publishers retain additions');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
