const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
 const page=await browser.newPage({viewport:{width:393,height:852},deviceScaleFactor:3,userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1',isMobile:true,hasTouch:true}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());await page.addInitScript(()=>localStorage.setItem('b3_tutorial_done','1'));await page.goto('http://127.0.0.1:8000');await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();
 await page.evaluate(async()=>{const docs=new Map(Array.from({length:12},(_,i)=>['products/item-'+i,{id:'item-'+i,kind:'frame',name:'商品 '+i,price:100,enabled:true,updatedAt:1}]));window.__products=docs;window.__writeCount=0;window.db={};window.fbDoc=(_,collection,id)=>'products/'+id;window.fbCollection=()=> 'products';window.fbGetDocs=async()=>({forEach:fn=>docs.forEach((data,id)=>fn({id:id.split('/')[1],data:()=>data}))});window.fbGetDoc=window.fbGetDocFromServer=async ref=>({exists:()=>docs.has(ref),data:()=>docs.get(ref)});window.fbSetDoc=async(ref,data)=>{__writeCount++;await new Promise(resolve=>window.__releaseWrite=resolve);docs.set(ref,structuredClone(data));};await ProfileShop.refresh(true);const pending={owner:myId,nonce:'editor-test',createdAt:Date.now()};sessionStorage.setItem('aiglish_admin_access_pending',JSON.stringify(pending));sessionStorage.setItem('aiglish_admin_access_ticket',JSON.stringify({owner:myId,nonce:pending.nonce,verifiedAt:Date.now()}));ProfileShop.restoreAdminAccess();});
 async function open(){await page.locator('#adminHub .appearance-admin-item').filter({hasText:'商品 0'}).click();await page.locator('.shop-editor-dialog').waitFor({state:'visible'});}
 for(const size of [{width:393,height:852},{width:360,height:640},{width:393,height:430}]){
  await page.setViewportSize(size);assert.equal(await page.locator('#adminHub .appearance-admin-item').count(),4);
  if(size.height>=640){const fits=await page.locator('#adminHub').evaluate(el=>({bottom:el.getBoundingClientRect().bottom,nav:document.getElementById('appMainBottomNavBar').getBoundingClientRect().top}));assert.ok(fits.bottom<=fits.nav,JSON.stringify(fits));}
  await open();const dimensions=await page.locator('.shop-editor-dialog').evaluate(el=>({scroll:el.scrollHeight,height:el.clientHeight,bottom:el.getBoundingClientRect().bottom,viewport:innerHeight}));assert.ok(dimensions.scroll<=dimensions.height+1,JSON.stringify(dimensions));assert.ok(dimensions.bottom<=dimensions.viewport,JSON.stringify(dimensions));
  const check=await page.locator('.shop-enabled').evaluate(el=>{const checkbox=el.querySelector('input').getBoundingClientRect(),span=el.querySelector('span').getBoundingClientRect();return {width:checkbox.width,spanHeight:span.height,spanWidth:span.width,labelHeight:el.getBoundingClientRect().height};});assert.equal(check.width,18);assert.ok(check.spanWidth>40&&check.spanHeight<=check.labelHeight);
  await page.getByRole('button',{name:'閉じる',exact:true}).click();
 }
 await page.setViewportSize({width:393,height:852});await open();await page.locator('#shopName').fill('確認済みの商品');
 const stable=await page.evaluate(async()=>{const modal=document.querySelector('.shop-editor-dialog');await new Promise(requestAnimationFrame);const original=modal.getBoundingClientRect.bind(modal);let reads=0;modal.getBoundingClientRect=()=>{reads++;return original();};const top=modal.style.top;for(let i=0;i<500;i++){visualViewport.dispatchEvent(new Event('scroll'));document.getElementById('shopName').dispatchEvent(new CompositionEvent('compositionupdate',{data:'商品名'}));}await new Promise(requestAnimationFrame);const scrollReads=reads;for(let i=0;i<100;i++)visualViewport.dispatchEvent(new Event('resize'));await new Promise(requestAnimationFrame);return {scrollReads,totalReads:reads,top,after:modal.style.top,hidden:getComputedStyle(document.querySelector('.container')).visibility};});assert.deepEqual(stable,{scrollReads:0,totalReads:0,top:'12px',after:'12px',hidden:'hidden'});
 await page.evaluate(()=>{currentTextbook='save-quiz-book';vocabList=[{num:1,word:'quiz-word',meaning:'クイズの意味',meanings:[{text:'クイズの意味'}],status:'none',history:[]}];localStorage.setItem('core_v4_loadquiz_book','auto');});await page.getByRole('button',{name:'保存',exact:true}).click();await page.getByRole('button',{name:'保存中…',exact:true}).waitFor({state:'visible'});assert.equal(await page.locator('.shop-admin-form').getAttribute('aria-busy'),'true');
 await page.locator('.shop-save-quiz-dialog #lqCardWrap').waitFor({state:'visible'});assert.ok((await page.locator('.shop-save-quiz-dialog').textContent()).includes('quiz-word'));
 await page.evaluate(()=>window.__answerLoadQuiz(window.__pgLoad.overlay,document.getElementById('lqCardWrap'),vocabList[0],'ok',100,0));
 await page.getByRole('button',{name:'保存を確認',exact:true}).waitFor({state:'visible',timeout:15000});assert.equal(await page.locator('.shop-save-quiz-dialog').count(),0);await page.waitForFunction(()=>vocabList[0].status==='ok');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(getVocabProgressStorageKey('save-quiz-book')))[1].status),'ok','quiz response must reach canonical local storage');assert.match(await page.locator('.shop-save-status').textContent(),/入力内容を保持/);assert.equal(await page.locator('#shopName').inputValue(),'確認済みの商品');assert.equal(await page.locator('.shop-admin-form').getAttribute('aria-busy'),'false');assert.equal(await page.evaluate(()=>__writeCount),1);
 await page.getByRole('button',{name:'保存を確認',exact:true}).click();await page.evaluate(()=>__releaseWrite());await page.locator('.shop-editor-dialog').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>__writeCount),1,'confirmation must not enqueue another write');assert.equal(await page.evaluate(()=>__products.get('products/item-0').name),'確認済みの商品');assert.equal(await page.evaluate(()=>ProfileShop.lookup('item-0').name),'確認済みの商品');
 await page.locator('#adminHub .appearance-admin-item').filter({hasText:'確認済みの商品'}).click();await page.locator('#shopName').fill('拒否後も残る名前');await page.evaluate(()=>{window.fbSetDoc=async()=>{const error=Error('denied');error.code='permission-denied';throw error;};});await page.getByRole('button',{name:'保存',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.shop-save-status').textContent.includes('拒否'));assert.equal(await page.locator('#shopName').inputValue(),'拒否後も残る名前');assert.equal(await page.locator('#shopName').isEnabled(),true);assert.equal(await page.getByRole('button',{name:'保存',exact:true}).isEnabled(),true);assert.equal(await page.evaluate(()=>ProfileShop.lookup('item-0').name),'確認済みの商品');
 await page.context().setOffline(true);await page.getByRole('button',{name:'保存',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.shop-save-status').textContent.includes('オフライン'));assert.equal(await page.locator('#shopName').inputValue(),'拒否後も残る名前');assert.equal(await page.getByRole('button',{name:'保存',exact:true}).isEnabled(),true);await page.context().setOffline(false);
 await page.evaluate(()=>window.fbSetDoc=async(ref,data)=>__products.set(ref,structuredClone(data)));await page.getByRole('button',{name:'保存',exact:true}).click();await page.locator('.shop-editor-dialog').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>ProfileShop.lookup('item-0').name),'拒否後も残る名前');
 await page.locator('#adminHub .appearance-admin-item').filter({hasText:'拒否後も残る名前'}).click();
 const noisyPhoto=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=600;const ctx=canvas.getContext('2d'),pixels=ctx.createImageData(600,600);let seed=1234;for(let i=0;i<pixels.data.length;i+=4){for(let j=0;j<3;j++){seed=(seed*1664525+1013904223)>>>0;pixels.data[i+j]=seed>>>24;}pixels.data[i+3]=i<600*4?0:255;}ctx.putImageData(pixels,0,0);return canvas.toDataURL('image/png').split(',')[1];});
 await page.locator('#shopImage').setInputFiles({name:'large-frame.png',mimeType:'image/png',buffer:Buffer.from(noisyPhoto,'base64')});
 await page.getByRole('button',{name:'保存',exact:true}).waitFor({state:'visible'});await page.waitForFunction(()=>!document.querySelector('.shop-admin-form [type=submit]').disabled);
 await page.getByRole('button',{name:'保存',exact:true}).click();await page.locator('.shop-editor-dialog').waitFor({state:'detached'});
 const photo=await page.evaluate(()=>__products.get('products/item-0').image);assert.ok(photo.length<=175000,`compressed frame is ${photo.length} characters`);assert.match(photo,/^data:image\/png;/);
 await page.evaluate(()=>window.fbSetDoc=async(ref,data)=>{await new Promise(resolve=>window.__finishClosedSave=resolve);__products.set(ref,structuredClone(data));});
 await page.locator('#adminHub').getByRole('button',{name:'次へ',exact:true}).click();await page.locator('#adminHub .appearance-admin-item').filter({hasText:'商品 1'}).click();await page.locator('#shopName').fill('閉じた後の保存');await page.getByRole('button',{name:'保存',exact:true}).click();await page.getByRole('button',{name:'編集に戻る',exact:true}).click();await page.getByRole('button',{name:'閉じる',exact:true}).click();
 await page.locator('#shopAdd').click();await page.locator('#shopName').fill('別の商品を入力中');await page.evaluate(()=>__finishClosedSave());await page.waitForFunction(()=>ProfileShop.lookup('item-1').name==='閉じた後の保存');assert.equal(await page.locator('#shopName').inputValue(),'別の商品を入力中','a late response must not close or change a newer editor');await page.getByRole('button',{name:'閉じる',exact:true}).click();
 assert.deepEqual(errors,[]);console.log('PASS: compact editor; zero input-time geometry reads; save quiz and canonical answer retention; single-write timeout confirmation; denied/offline retries; compressed PNG; safe late responses');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
