const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
 const page=await browser.newPage({viewport:{width:393,height:852},userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Mobile Safari/604.1'}),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));await page.route('https://**/*',r=>r.abort());await page.addInitScript(()=>localStorage.setItem('b3_tutorial_done','1'));await page.goto('http://127.0.0.1:8000');await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();
 assert.equal(await page.locator('#view-vocab').evaluate(el=>el.classList.contains('active')),true);assert.equal(await page.locator('#view-home,#nav-home,#homeProfile,#homeShop,#view-admin,.app-starfield').count(),0);assert.equal(requests.some(url=>/profile-shop|profile-customization|product-admin|admin-access/.test(url)),false);
 await page.evaluate(()=>{const key=getVocabProgressStorageKey('preserved');localStorage.setItem(key,JSON.stringify({'1':{status:'ok',note:'保存済み'}}));window.__preservedKey=key;localStorage.setItem('core_v4_profile_shop_owned_'+myId,JSON.stringify(['wood','archived']));localStorage.setItem('core_v4_profile_customization_'+myId,JSON.stringify({updatedAt:1,nickname:myName,frame:'archived',loadingQuiz:{bookId:'quiz-book',from:2,to:3}}));});
 await page.locator('.menu-trigger').click();const form=page.locator('#sidebarProfileForm');assert.equal(await form.locator('input').count(),2);assert.equal(await form.locator('input[type=color],textarea,select').count(),0);await page.locator('#sideInputName').fill('名前 アイコン');
 const photo=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=1600;canvas.height=1200;canvas.getContext('2d').fillRect(0,0,1600,1200);return canvas.toDataURL('image/png').split(',')[1];});await page.locator('#sidebarAvatarFile').setInputFiles({name:'icon.png',mimeType:'image/png',buffer:Buffer.from(photo,'base64')});await page.getByText('写真を選びました。保存で確定します。',{exact:true}).waitFor();await page.getByRole('button',{name:'プロフィールを保存',exact:true}).click();
 assert.equal(await page.locator('#sideOptPlayerName').textContent(),'名前 アイコン');const avatar=await page.evaluate(()=>localStorage.getItem('core_v4_user_avatar_'+myId));assert.match(avatar,/^data:image\/jpeg;base64,/);assert.ok(avatar.length<40000);assert.ok(await page.locator('.sidebar-header img').evaluate(img=>img.naturalWidth<=240));await page.locator('#sidebarOverlay').click({position:{x:370,y:400}});
 await page.reload();await page.waitForFunction(()=>window.UserProfile);assert.equal(await page.locator('#sideOptPlayerName').textContent(),'名前 アイコン');assert.equal(await page.evaluate(()=>localStorage.getItem('core_v4_user_avatar_'+myId)),avatar);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(getVocabProgressStorageKey('preserved')))['1'].status),'ok');assert.ok(await page.evaluate(()=>JSON.parse(localStorage.getItem('core_v4_profile_shop_owned_'+myId)).includes('archived')));
 // A stale backup must retain the newer identity and the archived purchase IDs.
 await page.evaluate(()=>{const id=myId,profileKey='core_v4_profile_customization_'+id,ownedKey='core_v4_profile_shop_owned_'+id;const data={localStorage:{[profileKey]:JSON.stringify({nickname:'古い名前',updatedAt:0}),[ownedKey]:JSON.stringify(['wood'])}};LibraryState.sanitizeSave({data},id);window.__mergedProfile=JSON.parse(data.localStorage[profileKey]);window.__mergedOwned=JSON.parse(data.localStorage[ownedKey]);});assert.equal(await page.evaluate(()=>__mergedProfile.nickname),'名前 アイコン');assert.ok(await page.evaluate(()=>__mergedOwned.includes('archived')));
 // Cloud rejection retains edits; a retry merges into existing user data.
 await page.evaluate(()=>{myId='profile-test';myName='初期';window.__cloud={profileCustomizationJson:JSON.stringify({updatedAt:1,nickname:'初期',loadingQuiz:{bookId:'quiz-book',from:2,to:3}}),userStats:{gold:77}};window.db={};window.fbDoc=(db,...path)=>path.join('/');window.fbRunTransaction=async()=>{throw Error('offline');};});await page.locator('.menu-trigger').click();await page.locator('#sideInputName').fill('同期する名前');await page.getByRole('button',{name:'プロフィールを保存',exact:true}).click();await page.waitForTimeout(100);assert.equal(await page.locator('#sideOptPlayerName').textContent(),'同期する名前');
 await page.evaluate(async()=>{fbRunTransaction=async(db,fn)=>fn({get:async()=>({exists:()=>true,data:()=>__cloud}),set:(ref,fields)=>Object.assign(__cloud,fields)});await UserProfile.sync();});assert.equal(await page.evaluate(()=>__cloud.playerName),'同期する名前');assert.equal(await page.evaluate(()=>__cloud.userStats.gold),77);assert.equal(await page.evaluate(()=>JSON.parse(__cloud.profileCustomizationJson).loadingQuiz.from),2);
 await page.evaluate(()=>{textbooksPool=[{id:'quiz-book',name:'クイズ確認'}];window.__getBookMasterWords=async()=>[{num:1},{num:2},{num:3}];});await page.locator('#sidebarOverlay').click({position:{x:370,y:400}});await page.evaluate(()=>openLoadingQuizSettings('quiz-book'));await page.locator('#quizUseBook').waitFor({state:'visible'});await page.locator('#quizUseBook').check();await page.locator('#quizFrom').fill('2');await page.locator('#quizTo').fill('3');await page.getByRole('button',{name:'設定を保存',exact:true}).click();assert.deepEqual(await page.evaluate(()=>filterLoadingQuizWords([{num:1},{num:2},{num:3}],'quiz-book').map(w=>w.num)),[2,3]);assert.equal(await page.evaluate(()=>UserProfile.read().nickname),'同期する名前');assert.deepEqual(errors,[]);
 console.log('PASS: no home/shop/admin runtime; sidebar name/photo save and reload; compressed icon; retained learning/purchases; stale backup preservation; offline cloud retry and independent vocabulary quiz');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
