const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const type=process.env.BROWSER==='webkit'?webkit:chromium,browser=await type.launch(type===chromium?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:{executablePath:process.env.WEBKIT_EXECUTABLE_PATH});try{
 const page=await browser.newPage({viewport:{width:393,height:852}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('crash',()=>errors.push('renderer crashed'));await page.route('https://**/*',r=>r.abort());await page.addInitScript(()=>{window.__nativeBackgroundStorage=window.localStorage;localStorage.setItem('b3_tutorial_done','1');Object.defineProperty(navigator,'userAgent',{value:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Mobile Safari/604.1'});Object.defineProperty(navigator,'standalone',{value:true});});await page.goto('http://127.0.0.1:8000');await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.waitForFunction(()=>window.__learningBootReady===true);
 await page.evaluate(()=>{window.__gcLoginShown=true;document.querySelectorAll('.gcModal').forEach(el=>el.remove());localStorage.setItem(getVocabProgressStorageKey('preserved'),JSON.stringify({'1':{status:'ok',note:'保存済み'}}));toggleSidebar(true);});
 await page.evaluate(()=>toggleSidebar(false));await page.locator('#headerBackgroundButton').click();
 const photos=page.locator('[data-background]:not([data-background="default"])'),photo=photos.first(),original=page.locator('[data-background="default"]');assert.equal(await photos.count(),0);assert.equal(await original.getAttribute('aria-pressed'),'true');await page.locator('#backgroundPickerClose').click();await page.locator('#backgroundPickerDialog').waitFor({state:'detached'});assert.equal(await page.locator('#backgroundPickerDialog').count(),0);await page.evaluate(()=>toggleSidebar(true));
 await page.locator('#sidebarBackgroundAdmin').click();await page.locator('#backgroundAdminPassword').fill('wrong');await page.locator('#backgroundAdminAuth button').click();assert.match(await page.locator('#backgroundAdminAuthStatus').textContent(),/違います/);assert.equal(await page.locator('#backgroundAdminControls').isHidden(),true);await page.locator('#backgroundAdminPassword').fill('tukinokopanda');await page.locator('#backgroundAdminAuth button').click();await page.locator('#backgroundAdminControls').waitFor({state:'visible'});assert.equal(await page.locator('#auth-gate-screen').isHidden(),true);const fixture=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=2000;canvas.height=1000;const ctx=canvas.getContext('2d'),gradient=ctx.createLinearGradient(0,0,2000,0);gradient.addColorStop(0,'orange');gradient.addColorStop(1,'navy');ctx.fillStyle=gradient;ctx.fillRect(0,0,2000,1000);return canvas.toDataURL('image/png').split(',')[1];});await page.locator('#sidebarBackgroundFile').setInputFiles({name:'landscape.png',mimeType:'image/png',buffer:Buffer.from(fixture,'base64')});assert.equal(await page.locator('#backgroundAdminSelection option').count(),0);await page.locator('#backgroundAdminRegister').click();await page.locator('#backgroundAdminSaveStatus').filter({hasText:'写真を登録しました'}).waitFor();assert.equal(await page.locator('#backgroundAdminSelection option').count(),1);
 const dimensions=await page.evaluate(async()=>{const record=JSON.parse(localStorage.getItem('aiglish_app_background_catalog_'+myId)),img=new Image();img.src=record.backgrounds[0].image;await img.decode();return {width:img.naturalWidth,height:img.naturalHeight,length:record.backgrounds[0].image.length};});assert.ok(await page.evaluate(()=>localStorage.getItem('aiglish_app_background_'+myId).length<250));assert.equal(dimensions.width,960);assert.equal(dimensions.height,480);assert.ok(dimensions.length<1000000);
 await page.locator('#sidebarBackgroundPosition').evaluate(el=>{el.value='80';el.dispatchEvent(new Event('input'));el.dispatchEvent(new Event('change'));});await page.locator('#backgroundAdminSaveStatus').filter({hasText:'背景を保存しました。'}).waitFor();assert.equal(await page.locator('#backgroundAdminName').count(),0);await page.locator('#sidebarBackgroundFile').setInputFiles({name:'second.png',mimeType:'image/png',buffer:Buffer.from(fixture,'base64')});await page.locator('#backgroundAdminRegister').click();await page.waitForFunction(()=>document.querySelector('#backgroundAdminSelection').options.length===2);await page.locator('#backgroundAdminClose').click();await page.locator('#headerBackgroundButton').click();assert.equal(await photos.count(),2);assert.equal(await photos.nth(1).getAttribute('aria-label'),'背景 2');assert.equal(await original.getAttribute('aria-pressed'),'true');assert.equal(await page.locator('.background-preview span').count(),0);assert.ok(await page.locator('#backgroundPickerSlides').evaluate(el=>el.scrollWidth>el.clientWidth));assert.ok(await photo.locator('img').evaluate(el=>Math.abs(el.getBoundingClientRect().width/el.getBoundingClientRect().height-innerWidth/innerHeight)<.02));await original.click();assert.equal(await original.getAttribute('aria-pressed'),'true');await photo.click();await page.locator('#backgroundPickerStatus').filter({hasText:'背景を保存しました。'}).waitFor();
 // Rapid changes retain the latest UI selection even when durable flush resolves out of order.
 await page.evaluate(async()=>{const flush=AppStorage.flush,pending=[];AppStorage.flush=()=>new Promise(resolve=>pending.push(resolve));document.querySelector('[data-background="default"]').click();document.querySelector('[data-background]:not([data-background="default"])').click();pending[1]();await Promise.resolve();pending[0]();await Promise.resolve();AppStorage.flush=flush;});assert.equal(await photo.getAttribute('aria-pressed'),'true');
 // Both the small preference and photograph catalogue must have confirmed IDB copies.
 await page.evaluate(async()=>{await AppStorage.flush();const pref='aiglish_app_background_'+myId,cat='aiglish_app_background_catalog_'+myId;await new Promise((resolve,reject)=>{const request=indexedDB.open('aiglish-local-values',1);request.onsuccess=()=>{const db=request.result,tx=db.transaction('values','readonly');let remaining=2;for(const key of [pref,cat]){const read=tx.objectStore('values').get(key);read.onsuccess=()=>{if(read.result!==localStorage.getItem(key)){reject(Error('Missing durable background record: '+key));return;}if(!--remaining){db.close();resolve();}};}tx.onabort=()=>reject(tx.error);};request.onerror=()=>reject(request.error);});__nativeBackgroundStorage.removeItem(pref);});
 await page.reload();await page.waitForFunction(()=>window.__learningBootReady===true);await page.locator('#headerBackgroundButton').click();assert.equal(await photo.getAttribute('aria-pressed'),'true');assert.equal(await page.evaluate(()=>String(JSON.parse(localStorage.getItem('aiglish_app_background_catalog_'+myId)).backgrounds[0].position)),'80');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(getVocabProgressStorageKey('preserved')))['1'].status),'ok');
 // An older surviving native preference must not replace the newer confirmed selection.
 await page.locator('#backgroundPickerClose').click();await page.evaluate(()=>__nativeBackgroundStorage.setItem('aiglish_app_background_'+myId,JSON.stringify({mode:'default',selected:'',updatedAt:1})));await page.reload();await page.waitForFunction(()=>window.__learningBootReady===true);await page.locator('#headerBackgroundButton').click();assert.equal(await photos.count(),2);assert.equal(await photo.getAttribute('aria-pressed'),'true');
 const style=await page.evaluate(()=>{const bg=getComputedStyle(document.body,'::after');return {size:bg.backgroundSize,position:bg.backgroundPosition,animation:bg.animationName,width:document.documentElement.scrollWidth,viewport:innerWidth};});assert.match(style.size,/cover/);assert.match(style.position,/80%/);assert.equal(style.animation,'none');assert.ok(style.width<=style.viewport);
 await page.locator('#backgroundPickerClose').click();await page.evaluate(()=>{window.__backgroundOwner=myId;myId='other-account';toggleSidebar(true);});await page.evaluate(()=>toggleSidebar(false));await page.locator('#headerBackgroundButton').click();assert.equal(await original.getAttribute('aria-pressed'),'true');assert.equal(await photos.count(),0);await page.locator('#backgroundPickerClose').click();await page.evaluate(()=>{myId=__backgroundOwner;toggleSidebar(true);});await page.evaluate(()=>toggleSidebar(false));await page.locator('#headerBackgroundButton').click();assert.equal(await photo.getAttribute('aria-pressed'),'true');assert.deepEqual(errors,[]);
 await page.evaluate(()=>toggleSidebar(false));await page.locator('#sidebarMenu').evaluate(el=>el.style.transition='none');for(const width of [393,320]){await page.setViewportSize({width,height:852});const boxes=await page.locator('.menu-trigger,#headerBackgroundButton,#headerStudyTime,#hfStableBox,#headerSaveBtn').evaluateAll(els=>els.map(el=>{const r=el.getBoundingClientRect();return {id:el.id||'menu',left:r.left,right:r.right};}).sort((a,b)=>a.left-b.left));assert.equal(boxes.length,5);for(let i=1;i<boxes.length;i++)assert.ok(boxes[i].left>=boxes[i-1].right-1,JSON.stringify(boxes));}await page.setViewportSize({width:393,height:852});await page.screenshot({path:'/tmp/sidebar-background-'+type.name()+'.png'});await page.locator('#backgroundPickerClose').click();await page.locator('#backgroundPickerDialog').waitFor({state:'detached'});
 // An independently recovered catalogue remains visible even when its preference is absent.
 await page.evaluate(async()=>{myId='orphan-gallery';const canvas=document.createElement('canvas');canvas.width=100;canvas.height=50;const image=canvas.toDataURL('image/jpeg');localStorage.setItem('aiglish_app_background_catalog_'+myId,JSON.stringify({backgrounds:[{id:'retained',image,position:50}],mode:'photo',selected:'retained',updatedAt:5}));await AppStorage.flush();});await page.locator('#headerBackgroundButton').click();assert.equal(await photos.count(),1);assert.equal(await photo.getAttribute('aria-pressed'),'true');assert.equal(await page.evaluate(()=>localStorage.getItem('aiglish_app_background_'+myId)),null);await page.locator('#backgroundPickerClose').click();
 // Legacy single-photo preferences remain selectable and migrate only after an explicit save.
 await page.evaluate(()=>{myId='legacy-background-owner';const canvas=document.createElement('canvas');canvas.width=100;canvas.height=50;const image=canvas.toDataURL('image/jpeg');localStorage.setItem('aiglish_app_background_'+myId,JSON.stringify({mode:'photo',image,position:65,updatedAt:1}));});
 await page.locator('#headerBackgroundButton').click();assert.equal(await photos.count(),1);assert.equal(await photo.getAttribute('aria-label'),'背景 1');assert.equal(await photo.getAttribute('aria-pressed'),'true');await original.click();await photo.click();await page.locator('#backgroundPickerStatus').filter({hasText:'背景を保存しました。'}).waitFor();await page.locator('#backgroundPickerClose').click();await page.reload();await page.waitForFunction(()=>window.__learningBootReady===true);await page.evaluate(()=>{myId='legacy-background-owner';});await page.locator('#headerBackgroundButton').click();assert.equal(await photos.count(),1);assert.equal(await photo.getAttribute('aria-pressed'),'true');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('aiglish_app_background_catalog_'+myId)).backgrounds[0].position),65);await page.keyboard.press('Escape');await page.locator('#backgroundPickerDialog').waitFor({state:'detached'});
 // Removal affects background artwork only, and closed dialogs release their image elements.
 await page.evaluate(()=>toggleSidebar(true));await page.locator('#sidebarBackgroundAdmin').click();await page.locator('#backgroundAdminPassword').fill('tukinokopanda');await page.locator('#backgroundAdminAuth button').click();await page.locator('#backgroundAdminDelete').click();await page.waitForFunction(()=>document.querySelector('#backgroundAdminSelection').options.length===0);await page.locator('#backgroundAdminClose').click();await page.locator('#headerBackgroundButton').click();assert.equal(await photos.count(),0);await page.locator('#backgroundPickerClose').click();await page.locator('#backgroundPickerDialog').waitFor({state:'detached'});assert.equal(await page.locator('.background-preview img').count(),0);assert.deepEqual(errors,[]);
 console.log('PASS '+type.name()+': header controls fit 320/393px; multi-photo portrait slider; admin gate; bounded thumbnails; small selection writes; legacy migration; deletion; rapid changes; confirmed IDB catalogue/preferences; missing-native recovery; stale-native protection; orphan catalogue recovery; durable reload; account isolation; learning retained; dialogs release previews; no runtime error');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
