const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const type=process.env.BROWSER==='webkit'?webkit:chromium,browser=await type.launch(type===chromium?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:{executablePath:process.env.WEBKIT_EXECUTABLE_PATH});try{
 const page=await browser.newPage({viewport:{width:393,height:852}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('crash',()=>errors.push('renderer crashed'));await page.route('https://**/*',r=>r.abort());await page.addInitScript(()=>localStorage.setItem('b3_tutorial_done','1'));await page.goto('http://127.0.0.1:8000');await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.waitForFunction(()=>__learningBootReady===true);
 await page.evaluate(()=>{window.__gcLoginShown=true;document.querySelectorAll('.gcModal').forEach(el=>el.remove());localStorage.setItem(getVocabProgressStorageKey('preserved'),JSON.stringify({'1':{status:'ok',note:'保存済み'}}));toggleSidebar(true);});
 const photo=page.locator('[data-background="photo"]'),original=page.locator('[data-background="default"]');assert.equal(await photo.isDisabled(),true);assert.equal(await original.getAttribute('aria-pressed'),'true');
 const fixture=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=2000;canvas.height=1000;const ctx=canvas.getContext('2d'),gradient=ctx.createLinearGradient(0,0,2000,0);gradient.addColorStop(0,'orange');gradient.addColorStop(1,'navy');ctx.fillStyle=gradient;ctx.fillRect(0,0,2000,1000);return canvas.toDataURL('image/png').split(',')[1];});await page.locator('#sidebarBackgroundFile').setInputFiles({name:'landscape.png',mimeType:'image/png',buffer:Buffer.from(fixture,'base64')});await page.getByText('背景を保存しました。',{exact:true}).waitFor();assert.equal(await photo.getAttribute('aria-pressed'),'true');
 const dimensions=await page.evaluate(async()=>{const record=JSON.parse(localStorage.getItem('aiglish_app_background_'+myId)),img=new Image();img.src=record.image;await img.decode();return {width:img.naturalWidth,height:img.naturalHeight,length:record.image.length};});assert.equal(dimensions.width,1280);assert.equal(dimensions.height,640);assert.ok(dimensions.length<1000000);
 await page.locator('#sidebarBackgroundPosition').evaluate(el=>{el.value='80';el.dispatchEvent(new Event('input'));el.dispatchEvent(new Event('change'));});await page.getByText('背景を保存しました。',{exact:true}).waitFor();await original.click();assert.equal(await original.getAttribute('aria-pressed'),'true');await photo.click();await page.getByText('背景を保存しました。',{exact:true}).waitFor();
 // Rapid changes retain the latest UI selection even when durable flush resolves out of order.
 await page.evaluate(async()=>{const flush=AppStorage.flush,pending=[];AppStorage.flush=()=>new Promise(resolve=>pending.push(resolve));document.querySelector('[data-background="default"]').click();document.querySelector('[data-background="photo"]').click();pending[1]();await Promise.resolve();pending[0]();await Promise.resolve();AppStorage.flush=flush;});assert.equal(await photo.getAttribute('aria-pressed'),'true');
 await page.reload();await page.waitForFunction(()=>__learningBootReady===true);await page.evaluate(()=>toggleSidebar(true));assert.equal(await photo.getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#sidebarBackgroundPosition').inputValue(),'80');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(getVocabProgressStorageKey('preserved')))['1'].status),'ok');
 const style=await page.evaluate(()=>{const bg=getComputedStyle(document.body,'::after');return {size:bg.backgroundSize,position:bg.backgroundPosition,animation:bg.animationName,width:document.documentElement.scrollWidth,viewport:innerWidth};});assert.match(style.size,/cover/);assert.match(style.position,/80%/);assert.equal(style.animation,'none');assert.ok(style.width<=style.viewport);
 await page.evaluate(()=>{window.__backgroundOwner=myId;myId='other-account';toggleSidebar(true);});assert.equal(await original.getAttribute('aria-pressed'),'true');assert.equal(await photo.isDisabled(),true);await page.evaluate(()=>{myId=__backgroundOwner;toggleSidebar(true);});assert.equal(await photo.getAttribute('aria-pressed'),'true');assert.deepEqual(errors,[]);
 await page.evaluate(()=>toggleSidebar(false));await page.locator('#sidebarMenu').evaluate(el=>el.style.transition='none');await page.screenshot({path:'/tmp/sidebar-background-'+type.name()+'.png'});console.log('PASS '+type.name()+': compressed static cover background; position adjustment; rapid changes; durable reload; account isolation; learning retained; no horizontal overflow or runtime error');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
