const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const type=process.env.BROWSER==='webkit'?webkit:chromium,browser=await type.launch(type===chromium?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:{executablePath:process.env.WEBKIT_EXECUTABLE_PATH});try{
const page=await browser.newPage({viewport:{width:393,height:852},deviceScaleFactor:3,isMobile:true,hasTouch:true,userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Mobile Safari/604.1'}),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('crash',()=>errors.push('renderer crash'));page.on('request',r=>requests.push(r.url()));await page.route('https://**/*',r=>r.abort());
await page.addInitScript(()=>{Object.defineProperty(navigator,'standalone',{value:true});window.__openedDatabases=[];const open=indexedDB.open.bind(indexedDB);indexedDB.open=(name,...args)=>{__openedDatabases.push(name);return open(name,...args);};window.__intervalStacks=[];const interval=setInterval;window.setInterval=(fn,ms,...args)=>{__intervalStacks.push({ms,stack:new Error().stack});return interval(fn,ms,...args);};if(localStorage.getItem('startup-seeded'))return;localStorage.setItem('startup-seeded','1');localStorage.setItem('core_v4_userId','startup-user');localStorage.setItem('core_v4_userName','検証');localStorage.setItem('core_v4_current_textbook_id','startup-book');const master=[{num:1,word:'study',meaning:'学ぶ'}],progress={1:{sig:'1::study::学ぶ',status:'ok',history:['ok'],meanings:{'1-0':{status:'ok',history:['ok']}}}},stats={gold:321,gacha_ticket_char:4,gacha_ticket_item:5};localStorage.setItem('core_v4_cache_startup-book',JSON.stringify(master));localStorage.setItem('core_v4_user_stats_startup-user',JSON.stringify(stats));localStorage.setItem('core_v4_user_vocab_progress_startup-user_startup-book',JSON.stringify(progress));localStorage.setItem('core_v4_user_vocab_progress_startup-user_startup-book__ts','1000');localStorage.setItem('save_studio_startup-user_main',JSON.stringify({savedAt:new Date(1000).toISOString(),data:{localStorage:{},memory:{myName:'検証',userStats:stats,vocabBookKey:'startup-book',vocabMaster:master,vocabProgress:progress,vocabBooks:{'startup-book':{master,progress,savedAt:new Date(1000).toISOString()}},unusedRestorePayload:'x'.repeat(2000000)}}}));});
await page.goto('http://127.0.0.1:8000');await page.waitForFunction(()=>window.__learningBootReady===true);await page.waitForTimeout(2200);assert.equal(await page.locator('#b3TutOverlay,#b3TutCss,.gcModal').count(),0);assert.equal(await page.evaluate(()=>localStorage.getItem('b3_tutorial_done')),null);assert.equal(await page.evaluate(()=>__openedDatabases.includes('aiglish_flags')),false);assert.equal(await page.evaluate(()=>__intervalStacks.some(entry=>/loginBonusWatch|_lbWatch|fixTutorialOnce/.test(entry.stack))),false);assert.equal(await page.evaluate(()=>window.__pendingGameSaveMemory),null);assert.equal(await page.evaluate(()=>LearningData.read('startup-book')[1].status),'ok');assert.equal(await page.evaluate(()=>userStats.gold),321);assert.equal(await page.evaluate(()=>userStats.gacha_ticket_char),4);assert.equal(await page.evaluate(()=>userStats.gacha_ticket_item),5);assert.equal(await page.locator('.gcRoot').count(),0);assert.equal(requests.some(url=>/intro\.mp4|fonts\.googleapis|fonts\.gstatic/.test(url)),false,JSON.stringify(requests.filter(url=>/intro\.mp4|fonts\.googleapis|fonts\.gstatic/.test(url))));
// Sync only the book index: no unselected masters are fetched or kept in the heap.
const prefetch=await page.evaluate(async()=>{let indexes=0,masters=0;window.__startupDb=window.db;window.__startupGet=window.fbGetDoc;window.__startupDoc=window.fbDoc;window.__startupSync=syncTextbooksIndexFromFirestore;window.db={};window.fbDoc=(...args)=>args.join('/');window.fbGetDoc=async()=>{masters++;return {exists:()=>true,data:()=>({custom_words:[]})};};window.syncTextbooksIndexFromFirestore=async()=>{indexes++;};await preloadAllTextbooksAndVocab();window.db=__startupDb;window.fbGetDoc=__startupGet;window.fbDoc=__startupDoc;window.syncTextbooksIndexFromFirestore=__startupSync;return {indexes,masters};});assert.deepEqual(prefetch,{indexes:1,masters:0});
// The game tab is still usable; the unopened pool does not mount all its artwork.
await page.evaluate(()=>switchTab('party'));await page.locator('#pgfBtnGasha').click();await page.locator('.gcRoot').waitFor({state:'visible'});assert.equal(await page.locator('#gcPoolList img').count(),0);await page.evaluate(()=>{document.querySelector('.gcRoot')?.remove();switchTab('reader');switchTab('party');});await page.locator('#pgfBtnGasha').click();await page.locator('#gcPoolToggle').click();await page.waitForFunction(()=>document.querySelectorAll('#gcPoolList .gcPoolItem').length>0);assert.equal(await page.locator('#gcPoolBox').evaluate(el=>el.style.display),'block');await page.evaluate(()=>switchTab('vocab'));assert.equal(await page.locator('#gcPoolList .gcPoolItem').count(),0);
assert.equal(await page.locator('#introVideo,#video-overlay').count(),0);const starts=await page.evaluate(()=>{let count=0;window.startMultiBattlePlay=()=>count++;playIntroVideoBeforeBattle();return count;});assert.equal(starts,1);
for(let round=0;round<3;round++){await page.reload();await page.waitForFunction(()=>window.__learningBootReady===true);assert.equal(await page.evaluate(()=>window.__pendingGameSaveMemory),null);assert.equal(await page.evaluate(()=>LearningData.read('startup-book')[1].status),'ok');assert.equal(await page.evaluate(()=>userStats.gold),321);assert.equal(await page.locator('#b3TutOverlay,.gcModal').count(),0);}assert.deepEqual(errors,[]);console.log('PASS '+type.name()+': first saved login without tutorial flag, bonus/modal/watchers/flag DB removed; balance/ratings retained; transient full backup released; index-only prefetch; no iOS web-font/video requests; lazy game/pool remains usable; three reloads');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
