const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
 const context=await browser.newContext({viewport:{width:393,height:852},userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Mobile Safari/604.1'});await context.route('https://**/*',route=>route.abort());await context.addInitScript(()=>localStorage.setItem('b3_tutorial_done','1'));
 const page=await context.newPage(),errors=[],requests=[];page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>requests.push(request.url()));await page.goto('http://127.0.0.1:8000');await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.waitForTimeout(700);assert.equal(await page.evaluate(()=>typeof lucide.createIcons),'function');assert.ok(await page.locator('svg.lucide').count()>15);assert.equal(requests.some(url=>url.includes('unpkg.com')),false);
 await page.evaluate(()=>{localStorage.setItem('core_v4_user_avatar_'+myId,'');const key=getVocabProgressStorageKey('startup-record');localStorage.setItem(key,JSON.stringify({'1':{status:'ok',note:'起動で保持'}}));window.__key=key;});const retained=await page.evaluate(()=>({key:__key,value:localStorage.getItem(__key)}));
 for(let round=0;round<3;round++){for(const tab of ['vocab','reader','community','study','titles','party'])await page.evaluate(tab=>switchTab(tab),tab);await page.reload();await page.waitForFunction(()=>window.UserProfile&&document.getElementById('auth-gate-screen').style.display==='none');await page.waitForTimeout(300);assert.deepEqual(await page.evaluate(()=>AppErrors.snapshot()),[]);assert.equal(await page.evaluate(key=>localStorage.getItem(key),retained.key),retained.value);}
 assert.deepEqual(errors,[]);assert.equal(await page.locator('#b3ErrToast').count(),1);
 // A real error before the main application scripts must retain its original file/line.
 const fixture=await context.newPage();await fixture.route('**/startup-error-fixture.js',route=>route.fulfill({contentType:'application/javascript',body:'\nthrow new Error("起動時の検証エラー");'}));await fixture.route('**/index.html',async route=>{const response=await route.fetch();const html=(await response.text()).replace('<script src="rendering-safety.js','<script src="startup-error-fixture.js"></script><script src="rendering-safety.js');await route.fulfill({response,body:html});});await fixture.goto('http://127.0.0.1:8000/index.html');await fixture.locator('#b3ErrToast.show').waitFor();const early=await fixture.evaluate(()=>AppErrors.snapshot());assert.equal(early.length,1);assert.equal(early[0].file,'startup-error-fixture.js');assert.equal(early[0].line,2);assert.match(await fixture.locator('#b3ErrToast').textContent(),/起動時の検証エラー.*startup-error-fixture.js:2/);assert.equal(await fixture.locator('#b3ErrToast').count(),1);
 await fixture.route('**/async-error-fixture.js',route=>route.fulfill({contentType:'application/javascript',body:'Promise.reject(new Error("非同期の検証エラー"));'}));await fixture.addScriptTag({url:'http://127.0.0.1:8000/async-error-fixture.js'});await fixture.waitForFunction(()=>AppErrors.snapshot().some(entry=>entry.kind==='promise'));const asynchronous=await fixture.evaluate(()=>AppErrors.snapshot().find(entry=>entry.kind==='promise'));assert.equal(asynchronous.file,'async-error-fixture.js');assert.equal(asynchronous.line,1);
 await fixture.evaluate(()=>{for(let i=0;i<12;i++)window.dispatchEvent(new ErrorEvent('error',{message:'検証 '+i,filename:location.origin+'/source.js?private-token=secret',lineno:4}));});const bounded=await fixture.evaluate(()=>AppErrors.snapshot());assert.equal(bounded.length,8);assert.equal(bounded[7].file,'source.js');assert.equal(JSON.stringify(bounded).includes('private-token'),false);assert.match(await fixture.locator('#b3ErrToast').textContent(),/source.js:4/);
 console.log('PASS: local pinned icons with external network blocked; saved-session startup and reload; retained learning; early real error with file/line; bounded diagnostics; no duplicate error listeners/toast');
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exit(1)});
