const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
 const context=await browser.newContext({viewport:{width:393,height:852},userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Mobile Safari/604.1'});await context.route('https://**/*',r=>r.abort());
 await context.addInitScript(()=>{
  window.__nativeStorage=localStorage;
  const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(window.__forceQuota&&this===__nativeStorage)throw new DOMException('The quota has been exceeded.','QuotaExceededError');return original.call(this,key,value);};
  if(localStorage.getItem('quota-test-seeded'))return;
  localStorage.setItem('quota-test-seeded','1');localStorage.setItem('b3_tutorial_done','1');localStorage.setItem('core_v4_userId','GUEST-000');localStorage.setItem('core_v4_userName','容量検証');
  localStorage.setItem('other-app-preserved','F'.repeat(70000));
  const words=Array.from({length:2000},(_,i)=>({num:i+1,word:'word-'+i,meaning:'意味 '+i}));
  localStorage.setItem('core_v4_custom_words_GUEST-000_quota-book',JSON.stringify(words));localStorage.setItem('core_v4_cache_quota-book',JSON.stringify(words));localStorage.setItem('core_v4_personal_library_GUEST-000',JSON.stringify({books:[{id:'quota-book',name:'容量検証の単語帳',personal:true,ownerId:'GUEST-000'}],hidden:[]}));
  localStorage.setItem('quota-preserved-progress',JSON.stringify({1:{status:'ok',note:'保存済みの理解度'}}));localStorage.setItem('vv4_works_GUEST-000','[{"id":"keep-work","title":"保持するワーク"}]');localStorage.setItem('core_v4_profile_shop_owned_GUEST-000','["wood","past-purchase"]');localStorage.setItem('aiglish_profile_shop_catalog','historical-catalog:'+ 'P'.repeat(250000));localStorage.setItem('save_studio_GUEST-000_preserved','saved-snapshot:'+ 'S'.repeat(250000));
  for(let i=0;i<200;i++){try{localStorage.setItem('core_v4_cache_quota_padding_'+i,'X'.repeat(65536));}catch(error){break;}}
  let lo=0,hi=65536;while(lo<hi){const mid=Math.ceil((lo+hi)/2);try{localStorage.setItem('quota-tail','Y'.repeat(mid));lo=mid;}catch(error){hi=mid-1;}}
  try{localStorage.setItem('core_v4_study_today_secs','600');window.__beforeQuota='unexpected success';}catch(error){window.__beforeQuota=error.name;}
 });
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('crash',()=>errors.push('renderer crashed'));await page.goto('http://127.0.0.1:8000');await page.waitForFunction(()=>window.UserProfile&&document.getElementById('appStartupStatus').hidden);assert.equal(await page.evaluate(()=>__beforeQuota),'QuotaExceededError','baseline must actually reproduce the displayed quota error');
 assert.equal(await page.evaluate(()=>__nativeStorage.getItem('other-app-preserved').length),70000);assert.equal(await page.evaluate(()=>__nativeStorage.getItem('aiglish_profile_shop_catalog')),null);assert.equal(await page.evaluate(()=>localStorage.getItem('aiglish_profile_shop_catalog').length),250019);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('quota-preserved-progress'))[1].status),'ok');assert.equal(await page.evaluate(()=>localStorage.getItem('save_studio_GUEST-000_preserved').length),250015);assert.ok(await page.evaluate(()=>Object.keys(localStorage).includes('core_v4_custom_words_GUEST-000_quota-book')));
 await page.getByRole('heading',{name:'単語帳を選ぶ',exact:true}).waitFor();await page.locator('#vocabLibraryBooks [data-book-id="quota-book"]').click();await page.waitForFunction(()=>vocabList.length===2000);assert.equal(await page.locator('#vocabListContainer .word-row-container').count(),40);await page.evaluate(()=>updateMeaningStatus(2,vocabList[1].meanings[0].id,'ok'));assert.equal(await page.evaluate(()=>Object.values(JSON.parse(localStorage.getItem(getVocabProgressStorageKey('quota-book')))[2].meanings).some(meaning=>meaning.status==='ok')),true);
 // Force continuing native quota failures, including the timer's small display writes.
 await page.evaluate(()=>{window.__forceQuota=true;localStorage.setItem('quota-small-record','new learning');});await page.waitForTimeout(1600);await page.evaluate(()=>AppStorage.flush());assert.equal(await page.evaluate(()=>AppStorage.error),null);assert.equal(await page.evaluate(()=>localStorage.getItem('quota-small-record')),'new learning');assert.deepEqual(await page.evaluate(()=>AppErrors.snapshot()),[]);const timeBefore=await page.locator('#headerStudyTime').textContent();await page.waitForTimeout(1200);assert.notEqual(await page.locator('#headerStudyTime').textContent(),timeBefore);
 await page.evaluate(async()=>{localStorage.setItem('quota-race','A'.repeat(70000));localStorage.setItem('quota-race','B'.repeat(70000));await AppStorage.flush();localStorage.removeItem('quota-race');localStorage.setItem('quota-race','C'.repeat(70000));await AppStorage.flush();});
 await page.reload();await page.waitForFunction(()=>window.UserProfile&&document.getElementById('appStartupStatus').hidden);assert.equal(await page.evaluate(()=>localStorage.getItem('quota-race')[0]),'C');assert.equal(await page.evaluate(()=>localStorage.getItem('quota-small-record')),'new learning');assert.equal(await page.evaluate(()=>Object.values(JSON.parse(localStorage.getItem(getVocabProgressStorageKey('quota-book')))[2].meanings).some(meaning=>meaning.status==='ok')),true);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('core_v4_profile_shop_owned_GUEST-000'))[1]),'past-purchase');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('vv4_works_GUEST-000'))[0].id),'keep-work');assert.equal(await page.evaluate(()=>localStorage.getItem('save_studio_GUEST-000_preserved').length),250015);assert.deepEqual(errors,[]);
 // Cross-tab updates to IndexedDB-backed keys remain visible to the other app.
 const peer=await context.newPage();await peer.goto('http://127.0.0.1:8000');await peer.waitForFunction(()=>window.AppStorage&&window.UserProfile);await page.evaluate(async()=>{localStorage.setItem('quota-race','D'.repeat(70000));await AppStorage.flush();});await peer.waitForFunction(()=>localStorage.getItem('quota-race')?.[0]==='D');
 // Full-save success must wait for the durable transaction; a failed write cannot claim success.
 await page.evaluate(async()=>{myId='quota-backup-user';window.__confirmedSave=await __backgroundSaveAll();await AppStorage.flush();});assert.equal(await page.evaluate(()=>__confirmedSave.localSaved),true);
 await page.evaluate(()=>{window.__storageTransaction=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(...args){const tx=__storageTransaction.apply(this,args);if(this.name==='aiglish-local-values'&&args[1]==='readwrite')tx.abort();return tx;};userStats.quotaTestMarker=1;});const rejected=await page.evaluate(async()=>{try{await __backgroundSaveAll();return false;}catch(error){return true;}});assert.equal(rejected,true,'failed IndexedDB save must not return a saved result');assert.ok(await page.evaluate(()=>AppStorage.pending>0));await page.evaluate(async()=>{IDBDatabase.prototype.transaction=__storageTransaction;await AppStorage.flush();});assert.equal(await page.evaluate(()=>AppStorage.error),null);
 // Failed migration cannot erase the only native copy or boot over missing state.
 const failureContext=await browser.newContext();await failureContext.route('https://**/*',r=>r.abort());await failureContext.addInitScript(()=>{window.__nativeStorage=localStorage;localStorage.setItem('core_v4_test_migration_preserved','K'.repeat(70000));const transaction=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(...args){const tx=transaction.apply(this,args);if(this.name==='aiglish-local-values'&&args[1]==='readwrite')tx.abort();return tx;};});const failed=await failureContext.newPage();await failed.goto('http://127.0.0.1:8000');await failed.waitForFunction(()=>window.AppStorage?.error);assert.equal(await failed.evaluate(()=>__nativeStorage.getItem('core_v4_test_migration_preserved').length),70000);assert.equal(await failed.evaluate(()=>typeof window.UserProfile),'undefined');assert.equal(await failed.locator('#appStartupStatus').isVisible(),true);await failureContext.close();
 console.log('PASS: real native quota reproduced; large-value migration preserves records and frees capacity; book open/rating and study timer survive quota; reload retains data; latest write/deletion and cross-tab sync; aborted migration preserves native data and blocks unsafe startup');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
