const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const source=fs.readFileSync('study-time.js','utf8');const ctx={window:{}};vm.runInNewContext(source.slice(0,source.indexOf('    let user='))+'})();',ctx);const m=ctx.window.StudyTimeModel;
const empty=()=>({version:1,days:{},offset:0});
test('elapsed milliseconds accumulate exactly and split at midnight',()=>{const ledger=empty(),start=new Date(2026,9,7,23,59,58).getTime();m.accrue(ledger,'device',start,start+4500);assert.equal(m.dayMilliseconds(ledger.days['2026-10-07']),2000);assert.equal(m.dayMilliseconds(ledger.days['2026-10-08']),2500);assert.equal(m.total(ledger),4500);});
test('cloud merge is idempotent and combines separate devices without restoring stale counters',()=>{const a=empty(),b=empty(),now=new Date(2026,9,7,12).getTime();m.accrue(a,'a',now,now+1234);m.accrue(b,'b',now,now+2345);const both=m.merge(a,b);assert.equal(m.total(both),3579);assert.equal(m.total(m.merge(both,a)),3579);});
test('manual corrections can reduce a day and later elapsed time continues from that value',()=>{const ledger=empty(),now=new Date(2026,9,7,12).getTime();m.accrue(ledger,'device',now,now+120000);const old=JSON.parse(JSON.stringify(ledger));m.editDay(ledger,'2026-10-07',30000,now+120001);assert.equal(m.total(m.merge(ledger,old)),30000);m.accrue(ledger,'device',now+120000,now+121500);assert.equal(m.total(ledger),31500);});
test('historical weekday logs are dated from their actual last recorded day, not today',()=>{const ledger=m.legacy({study_total_secs:600},{date:'2026-9-30',today:60,log:[0,0,1,0,0,0,0]},new Date(2026,9,7).getTime());assert.equal(m.dayMilliseconds(ledger.days['2026-09-30']),60000);assert.equal(m.rangeValue(ledger,'daily',new Date(2026,9,7).getTime()),0);assert.equal(m.total(ledger),600000);});
test('weekly totals use calendar dates and exclude last week',()=>{const ledger=empty(),old=new Date(2026,9,4,12).getTime(),now=new Date(2026,9,7,12).getTime();m.accrue(ledger,'d',old,old+60000);m.accrue(ledger,'d',now,now+120000);assert.equal(m.rangeValue(ledger,'weekly',now),120000);assert.equal(m.total(ledger),180000);});

test('reset discards old local and cloud time once and preserves new-generation saves',()=>{const old=empty();m.accrue(old,'old',0,999999);const fresh=m.mergeCurrent(null,old);assert.equal(m.total(fresh),0);m.accrue(fresh,'new',0,1500);assert.equal(m.total(m.mergeCurrent(fresh,old)),1500);assert.equal(m.total(m.mergeCurrent(null,fresh)),1500);});

test('weekly graph always has seven calendar dates across month boundaries',()=>{const data=empty();m.accrue(data,'d',new Date(2026,8,30,12).getTime(),new Date(2026,8,30,12).getTime()+60000);const values=m.weekValues(data,'2026-09-28');assert.equal(values.length,7);assert.equal(values[2].ms,60000);assert.equal(values[6].date,'2026-10-04');});

test('rankings read current stats beside stale or malformed JSON without reviving pre-reset time',()=>{const fresh=m.mergeCurrent(null,null);m.accrue(fresh,'remote',0,300000);const stats=m.readStats({userStatsJson:JSON.stringify({study_total_secs:999999}),userStats:{study_calendar_v2:fresh}});assert.equal(m.total(stats.study_calendar_v2),300000);assert.equal(m.total(m.readStats({userStatsJson:'broken',userStats:{study_calendar_v2:fresh}}).study_calendar_v2),300000);});

test('legacy public counters cannot reintroduce retired accounts into study rankings',()=>{const now=new Date(2026,9,8,12).getTime(),stats={study_total_secs:3600,study_today_secs:600,study_today_date:'2026-10-08'};assert.equal(m.rankingSeconds(stats,'total',now),0);assert.equal(m.rankingSeconds(stats,'daily',now),0);assert.equal(m.total(m.resetLedger(stats.study_calendar_v2)),0);assert.equal(m.rankingSeconds({...stats,study_calendar_v2:{epoch:'old'}},'total',now),0);});

test('real profile storage with null userStats reads stats for daily and total podiums',()=>{const now=new Date(2026,9,8,12).getTime(),ledger=m.mergeCurrent(null,null);m.accrue(ledger,'remote',now,now+1500000);const doc={userStats:null,stats:{study_calendar_v2:ledger,study_today_secs:1500,study_today_date:'2026-10-8',study_total_secs:1500}};const parsed=m.readStats(doc);assert.equal(m.rankingSeconds(parsed,'daily',now),1500);assert.equal(m.rankingSeconds(parsed,'total',now),1500);assert.deepEqual(doc.userStats,null);});

test('independent cloud ledger survives empty profile statistics',()=>{const time=new Date(2026,9,8,12).getTime(),ledger=m.mergeCurrent(null,null);m.accrue(ledger,'device',time,time+900000);const recovered=m.readStats({userStats:null,stats:{study_calendar_v2:m.mergeCurrent(null,null)},studyLedgerJson:JSON.stringify(ledger)});assert.equal(m.rankingSeconds(recovered,'daily',time),900);assert.equal(m.total(recovered.study_calendar_v2),900000);});
