const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
 const context=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Asia/Tokyo'});const page=await context.newPage();page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());await page.addInitScript(()=>{localStorage.setItem('b3_tutorial_done','1');if(!localStorage.getItem('reset-test-seeded')){localStorage.setItem('aiglish_study_ledger_GUEST-000',JSON.stringify({version:1,days:{'2026-10-07':{sources:{old:999999}}},offset:999999}));localStorage.setItem('reset-test-seeded','1');}});await page.goto('http://127.0.0.1:8000',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.StudyTime);await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();
 assert.equal(await page.evaluate(()=>todayStudySeconds),0);assert.equal(await page.locator('#nav-game').count(),0);await page.locator('#nav-study').click();await page.getByRole('button',{name:'開始',exact:true}).click();await page.waitForTimeout(600);
 const start=await page.evaluate(()=>todayStudySeconds);await page.waitForTimeout(2600);const end=await page.evaluate(()=>todayStudySeconds);assert.ok(end-start>=2&&end-start<=3,'must count actual elapsed seconds once');assert.equal(await page.locator('#todayStudyTimeDisplay').textContent(),await page.locator('#studyLiveTime').textContent());
 await page.getByRole('button',{name:'一時停止',exact:true}).click();const stopped=await page.evaluate(()=>todayStudySeconds);await page.waitForTimeout(1500);assert.equal(await page.evaluate(()=>todayStudySeconds),stopped);assert.ok(await page.locator('#studyCalendar button').count()>=28);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.getByRole('button',{name:'この日の時間を編集',exact:true}).click();await page.locator('#studyEditMinutes').fill('2');await page.getByRole('button',{name:'保存',exact:true}).click();assert.equal(await page.evaluate(()=>todayStudySeconds),120);await page.screenshot({path:'/tmp/study-time-tab.png'});
 await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.StudyTime);assert.equal(await page.evaluate(()=>todayStudySeconds),120);await page.locator('#nav-study').click();assert.equal(await page.locator('#studyLiveTime').textContent(),'00:02:00');
 // Merely selecting a library or waiting on the home page must not count.
 await page.locator('#nav-vocab').click();await page.waitForTimeout(1100);assert.equal(await page.evaluate(()=>todayStudySeconds),120);
 await page.evaluate(()=>{textbooksPool=[{id:'time-book',name:'計測テスト',cover:'📔'}];textbooksCacheMap['time-book']=[{num:1,word:'study',meaning:'学ぶ'}];window.renderVocabLibrarySelection();});await page.locator('#vocabLibraryBooks .textbook-list-item').click();await page.waitForTimeout(1700);assert.ok(await page.evaluate(()=>todayStudySeconds)>120);
 const beforeHidden=await page.evaluate(()=>todayStudySeconds);await page.evaluate(()=>{Object.defineProperty(document,'visibilityState',{value:'hidden',configurable:true});document.dispatchEvent(new Event('visibilitychange'));});await page.waitForTimeout(1200);const hidden=await page.evaluate(()=>todayStudySeconds);assert.ok(hidden-beforeHidden<=1);await page.evaluate(()=>{Object.defineProperty(document,'visibilityState',{value:'visible',configurable:true});document.dispatchEvent(new Event('visibilitychange'));});await page.waitForTimeout(1200);assert.ok(await page.evaluate(()=>todayStudySeconds)>hidden);
 // Two open tabs share one timer ownership lock and cannot double-count.
 await page.locator('#nav-study').click();await page.getByRole('button',{name:'開始',exact:true}).click();
 const other=await page.context().newPage();other.setDefaultTimeout(10000);await other.route('https://**/*',r=>r.abort());await other.goto('http://127.0.0.1:8000',{waitUntil:'domcontentloaded'});await other.waitForFunction(()=>window.StudyTime);await other.locator('#nav-study').click();await other.getByRole('button',{name:'開始',exact:true}).click();
 const concurrentStart=await page.evaluate(()=>todayStudySeconds);await page.waitForTimeout(2500);const concurrentEnd=await page.evaluate(()=>todayStudySeconds);assert.ok(concurrentEnd-concurrentStart>=2&&concurrentEnd-concurrentStart<=3);await other.close();await page.getByRole('button',{name:'一時停止',exact:true}).click();
 // All-user podium ignores pre-reset stats and includes non-friends with >=5 minutes today.
 await page.evaluate(()=>{window.__gcLoginShown=true;myId='time-user';myName='自分';myFriendList=[];window.db={};window.fbCollection=(_, ...path)=>path.join('/');const day=window.StudyTimeModel.dateKey(Date.now());const stats=seconds=>({study_calendar_v2:{version:1,epoch:'study-reset-2.62',days:{[day]:{sources:{test:seconds*1000}}},offset:0}});window.fbGetDocs=async()=>({forEach:cb=>{[['a','非フレンドA',600],['b','非フレンドB',900],['c','非フレンドC',300],['short','短時間',299]].forEach(([id,name,seconds])=>cb({id,data:()=>({playerName:name,userStats:stats(seconds)})}));cb({id:'old',data:()=>({playerName:'旧データ',userStats:{study_today_secs:99999,study_total_secs:99999}})});}});window.fbDoc=(_, ...path)=>path.join('/');window.fbGetDoc=async()=>({exists:()=>true,data:()=>({userStats:{study_total_secs:999999,study_burst:999}})});window.fbSetDoc=async()=>{};window.StudyTime.init();localStorage.setItem('core_v4_multi_best_floor','42');});await page.locator('#nav-study').click();await page.locator('.place-1 .study-podium-name').waitFor();assert.equal(await page.locator('.place-1 .study-podium-name').textContent(),'非フレンドB');assert.equal(await page.locator('.study-podium-name').count(),3);assert.equal(await page.locator('#studyRankRanges').count(),0);assert.equal(await page.locator('#activityBarChart').count(),0);assert.equal(await page.locator('#studyTimerStatus').count(),0);assert.equal(await page.locator('#view-study .vocab-library-header').count(),0);assert.equal(await page.locator('#studyFriendRanking').getByText('旧データ').count(),0);await page.evaluate(async()=>{await window.saveUserStats();});assert.equal(await page.evaluate(()=>userStats.study_total_secs),0);assert.equal(await page.evaluate(()=>userStats.study_burst),0);await page.screenshot({path:'/tmp/study-podium.png',fullPage:true});
 await page.evaluate(()=>window.toggleSidebar(true));await page.getByRole('button',{name:'単語の迷宮',exact:true}).click();assert.equal(await page.locator('#view-game').evaluate(el=>el.classList.contains('active')),true);assert.equal(await page.locator('#game-start-screen .tower-title-text').textContent(),'単語の迷宮');assert.equal(await page.evaluate(()=>localStorage.getItem('core_v4_multi_best_floor')),'42');
 assert.deepEqual(errors,[]);console.log('PASS: elapsed time, pause, home/study consistency, dated calendar edit/restart, library exclusion, study auto-count, hidden pause, all-user daily podium and preserved tower');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
