const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const helper=fs.readFileSync('vocab-master.js','utf8'),multi=fs.readFileSync('multi.js','utf8');
function setup(){const values=new Map(),ctx={myId:'user',console,textbooksCacheMap:{},__manualVocabDrafts:{},localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)}};ctx.window=ctx;vm.runInNewContext(helper,ctx);return {ctx,values};}
test('empty and corrupt restore entries cannot overwrite a surviving master',async()=>{
const {ctx,values}=setup(),key='core_v4_cache_history',draftKey='core_v4_vocab_draft_user_history';const words=[{num:1,word:'大化の改新'}];values.set(key,JSON.stringify(words));values.set(draftKey,JSON.stringify({master:words,savedAt:'2000-01-01T00:00:00Z'}));values.set('save',JSON.stringify({savedAt:'2099-01-01T00:00:00Z',data:{localStorage:{[key]:'[]',[draftKey]:JSON.stringify({master:[],savedAt:'2099-01-01T00:00:00Z'}),'core_v4_custom_words_user_history':'broken'}}}));Object.assign(ctx,{loginUid:()=> 'user',localKey:()=> 'save',cloudMetaKey:()=> 'meta',localMetaKey:()=> 'local-meta'});const start=multi.indexOf('async function autoLoadOnce()');vm.runInNewContext(multi.slice(start,multi.indexOf('\nfunction openPanel()',start)),ctx);await ctx.autoLoadOnce();assert.deepEqual(JSON.parse(values.get(key)),words);assert.equal(JSON.parse(values.get(draftKey)).master.length,1);assert.equal(values.has('core_v4_custom_words_user_history'),false);
});
test('an explicitly empty saved book can restore both master keys',()=>{const {ctx}=setup();const memory={vocabBooks:{history:{master:[],emptyConfirmed:true}}};assert.equal(ctx.VocabMaster.canRestoreStorage('core_v4_cache_history','[]',memory,'user'),true);assert.equal(ctx.VocabMaster.canRestoreStorage('core_v4_custom_words_user_history','[]',memory,'user'),true);assert.equal(ctx.VocabMaster.canRestoreStorage('core_v4_cache_other','[]',memory,'user'),false);});
test('recovery honors deletion tombstones and does not resurrect partial word deletions',()=>{const {ctx,values}=setup();values.set('core_v4_cache_history',JSON.stringify([{num:1},{num:2}]));const preferred={master:[{num:1}]};assert.equal(ctx.VocabMaster.resolve('history',preferred),preferred);ctx.LibraryState={isDeleted:()=>true};assert.equal(ctx.VocabMaster.resolve('history',preferred),null);});
test('explicit empty permission is scoped to the account and book',()=>{const {ctx}=setup();ctx.VocabMaster.confirmEmpty('history');assert.equal(ctx.VocabMaster.canCapture('history',[]),true);assert.equal(ctx.VocabMaster.canCapture('other',[]),false);ctx.myId='another';assert.equal(ctx.VocabMaster.canCapture('history',[]),false);ctx.myId='user';ctx.VocabMaster.canCapture('history',[{num:1}]);assert.equal(ctx.VocabMaster.canCapture('history',[]),false);});
