const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const type=process.env.BROWSER==='webkit'?webkit:chromium;const browser=await type.launch(type===chromium?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:{executablePath:process.env.WEBKIT_EXECUTABLE_PATH});try{
const page=await browser.newPage({viewport:{width:393,height:852}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());if(process.env.BASELINE_DIR)for(const name of ['app','multi','vocab_ui'])await page.route('**/'+name+'.js?*',r=>r.fulfill({contentType:'application/javascript',body:fs.readFileSync(process.env.BASELINE_DIR+'/'+name+'.js','utf8')}));await page.addInitScript(()=>localStorage.setItem('b3_tutorial_done','1'));await page.goto('http://127.0.0.1:8000');await page.waitForFunction(()=>window.VocabMaster&&window.__saveCoordinatorApplied);await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.waitForFunction(()=>window.__learningBootReady===true);
const result=await page.evaluate(async()=>{
const words=[{num:1,word:'大化の改新',meaning:'645年'},{num:2,word:'墾田永年私財法',meaning:'743年'}];
const failures=[];const check=(condition,message)=>{if(!condition)failures.push(message)};
myId='history-recovery-user';textbooksPool=[{id:'history-cold',name:'一問一答 日本史'}];window.db={};window.fbDoc=(db,...path)=>path.join('/');let reads=[];window.fbGetDoc=async ref=>{reads.push(ref);return {exists:()=>ref.startsWith('shared/vocab_'),data:()=>({custom_words:words})}};window.loadUserVocabProgress=async()=>{currentUserVocabProgress={}};
currentTextbook='history-cold';await loadCurrentTextbookData();check(vocabList.length===2,'cold cache fetch');check(reads.includes('shared/vocab_history-cold'),'shared book fetched on demand');
// Empty newer draft cannot hide a surviving nonempty cache.
currentTextbook='history-cache';localStorage.setItem('core_v4_vocab_draft_'+myId+'_history-cache',JSON.stringify({master:[],progress:{},savedAt:'2099-01-01T00:00:00Z'}));localStorage.setItem('core_v4_custom_words_'+myId+'_history-cache','[]');localStorage.setItem('core_v4_cache_history-cache',JSON.stringify(words));reads=[];await loadCurrentTextbookData();check(vocabList.length===2,'empty draft recovered from cache');check(reads.length===0,'local recovery does not wait for network');
// A failed fetch leaves the loading gate closed, does not overwrite/cache/capture empty data.
currentTextbook='history-failure';window.fbGetDoc=async()=>{throw Error('quota exceeded')};let refused=false;try{await loadCurrentTextbookData()}catch(e){refused=true}check(refused,'failed fetch rejected');check(!LearningData.canSave(currentTextbook),'failed fetch cannot save');vocabList=[];check(!__captureManualVocabDraft(),'empty failed load not captured');check(!localStorage.getItem(__manualVocabLocalKey(currentTextbook)),'failed load no empty draft');
window.fbGetDoc=async ref=>({exists:()=>ref.startsWith('shared/vocab_'),data:()=>({custom_words:words})});await loadCurrentTextbookData();check(vocabList.length===2&&LearningData.canSave(currentTextbook),'retry recovers book');
// An unexpected empty display cannot erase the canonical master even after the load finished.
__captureManualVocabDraft();const before=localStorage.getItem(__manualVocabLocalKey(currentTextbook));vocabList=[];check(!__captureManualVocabDraft(),'unconfirmed empty display rejected');check(localStorage.getItem(__manualVocabLocalKey(currentTextbook))===before,'existing draft preserved');
// Explicit last-word deletion survives reload without resurrecting shared words.
VocabMaster.confirmEmpty(currentTextbook);const empty=__captureManualVocabDraft();check(empty&&empty.emptyConfirmed,'explicit empty saved');await loadCurrentTextbookData();check(vocabList.length===0,'explicit empty reload');
// Partial deletion is also authoritative.
currentTextbook='history-partial';localStorage.setItem(__manualVocabLocalKey(currentTextbook),JSON.stringify({master:[words[0]],progress:{},savedAt:new Date().toISOString()}));localStorage.setItem('core_v4_cache_history-partial',JSON.stringify(words));await loadCurrentTextbookData();check(vocabList.length===1,'partial deletion retained');
// Larger saved snapshot is read only if per-book copies are missing.
currentTextbook='history-backup';localStorage.setItem('save_studio_'+myId+'_main',JSON.stringify({data:{memory:{vocabBooks:{'history-backup':{master:words,progress:{},savedAt:new Date().toISOString()}}}}}));reads=[];await loadCurrentTextbookData();check(vocabList.length===2,'full backup recovery');
// Both faces use the same per-meaning understanding color, including status without history.
currentTextbook='history-rim';vocabList=migrateVocabData([{num:1,word:'history',meaning:'歴史',meanings:[{id:'1-0',text:'歴史',status:'bad',history:['bad']}]}]);const card={num:1,en:'history',ja:'歴史',meaningId:'1-0'};const style=getFlashcardStyleByHistory(card);const colors=[];for(const face of ['front','back']){const el=document.createElement('div');el.className='flashcard-face-'+face;el.style.cssText=style;document.body.append(el);colors.push(getComputedStyle(el).outlineColor);el.remove()}check(colors.every(c=>c==='rgb(239, 68, 68)'),'red outline on both faces');
vocabList[0].meanings.push({id:'1-1',text:'別の意味',status:'ok',history:['ok']});check(getFlashcardStyleByHistory({...card,meaningId:'1-1'}).includes('--flashcard-rim-color:rgb(16,185,129)'),'each meaning has own rim');vocabList[0].meanings[0].history=[];check(getFlashcardStyleByHistory(card).includes('--flashcard-rim-color:#ef4444'),'status-only rim');
return {failures,colors};});if(result.failures.length)console.log(result);assert.deepEqual(result.failures,[]);assert.deepEqual(errors,[]);console.log('PASS '+type.name()+': Japan history cold/cache/backup recovery, failed-load save gate, explicit deletions and understanding rims');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
