const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const type=process.env.BROWSER==='webkit'?webkit:chromium,browser=await type.launch(type===chromium?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:{executablePath:process.env.WEBKIT_EXECUTABLE_PATH});try{
 const page=await browser.newPage({viewport:{width:393,height:852},hasTouch:true,isMobile:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());await page.addInitScript(()=>localStorage.setItem('aiglish_sound_settings',JSON.stringify({enabled:false})));await page.goto('http://127.0.0.1:8000');await page.waitForFunction(()=>window.LearningWallet);await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.waitForFunction(()=>window.__learningBootReady===true);
 await page.evaluate(async()=>{
  const m=LearningRewardsModel,start=m.weekStart(Date.now()),previous=m.shiftDay(start,-1);myId='weekly-self';userStats={};window.db={};window.fbDoc=(db,...p)=>p.join('/');window.fbCollection=()=>'';
  const fixtures=[['old',{time:900000,ratings:0,swipes:0,day:previous}],['new',{time:120000,ratings:5,swipes:3,day:start}],['third',{time:60000,ratings:3,swipes:1,day:start}]];
  window.__weeklyDocs=fixtures.map(([id,data])=>{let activity=m.activity();for(let i=0;i<data.ratings;i++)activity=m.add(activity,'ratings',id,Date.parse(data.day+'T12:00:00+09:00'));for(let i=0;i<data.swipes;i++)activity=m.add(activity,'swipes',id,Date.parse(data.day+'T12:00:00+09:00'));const total=LearningRankingModel.empty();total.words.a=1;total.flash.sources[id]=20;return {id,data:()=>({playerName:id,learningRankingV2Json:JSON.stringify(total),learningActivityV1Json:JSON.stringify(activity),studyLedgerJson:JSON.stringify({version:1,epoch:'study-reset-2.62',offset:0,days:{[data.day]:{sources:{[id]:data.time}}}})})};});
  window.fbGetDocs=async()=>({forEach:fn=>__weeklyDocs.forEach(fn)});await LearningRanking.refresh(true);switchTab('titles');
 });
 await page.locator('[data-ranking-period="weekly"]').click();assert.equal(await page.locator('[data-ranking-period="weekly"]').getAttribute('aria-pressed'),'true');assert.match(await page.locator('#rankingPeriodCaption').textContent(),/\d{4}-\d{2}-\d{2} 〜/);
 assert.match(await page.locator('[data-podium-metric="time"] [data-place="1"]').textContent(),/new/);assert.match(await page.locator('[data-podium-metric="words"] h3').textContent(),/回数/);assert.match(await page.locator('[data-podium-metric="words"] [data-place="1"] strong').textContent(),/5回/);assert.match(await page.locator('[data-podium-metric="flash"] [data-place="1"] strong').textContent(),/3回/);
 await page.locator('.ranking-stage').dispatchEvent('pointerdown',{clientX:100,clientY:140,isPrimary:true});await page.locator('.ranking-stage').dispatchEvent('pointerup',{clientX:250,clientY:145,isPrimary:true});assert.equal(await page.locator('[data-ranking-period="total"]').getAttribute('aria-pressed'),'true');assert.match(await page.locator('[data-podium-metric="time"] [data-place="1"]').textContent(),/old/);
 await page.locator('.ranking-stage').dispatchEvent('pointerdown',{clientX:250,clientY:140,isPrimary:true});await page.locator('.ranking-stage').dispatchEvent('pointerup',{clientX:100,clientY:145,isPrimary:true});assert.equal(await page.locator('[data-ranking-period="weekly"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('dialog[open]').count(),0);
 const before=await page.evaluate(()=>LearningRewardsModel.count(LearningActivity.read(),'ratings',LearningRewardsModel.dateKey(Date.now())));await page.evaluate(()=>{recordRankedWord('book',1);recordRankedWord('book',1);});assert.equal(await page.evaluate(()=>LearningRewardsModel.count(LearningActivity.read(),'ratings',LearningRewardsModel.dateKey(Date.now()))),before+2);assert.equal(await page.evaluate(()=>LearningRankingModel.wordCount(LearningRanking.snapshot())),1,'existing unique-word cumulative record remains compatible');
 assert.deepEqual(errors,[]);console.log('PASS '+type.name()+': weekly dated time/ratings/swipes; prior week excluded; cumulative preserved; two-way swipe without opening podium; repeat ratings count independently');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
