const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const type=process.env.BROWSER==='webkit'?webkit:chromium,browser=await type.launch(type===chromium?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:{executablePath:process.env.WEBKIT_EXECUTABLE_PATH});try{
 const page=await browser.newPage({viewport:{width:393,height:852}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());await page.addInitScript(()=>localStorage.setItem('aiglish_sound_settings',JSON.stringify({enabled:false})));await page.goto('http://127.0.0.1:8000');await page.waitForFunction(()=>window.WeeklyRewards);await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.waitForFunction(()=>window.__learningBootReady===true);await page.clock.setFixedTime(new Date('2026-10-12T08:00:00+09:00'));
 const result=await page.evaluate(async()=>{
  const m=LearningRewardsModel,week='2026-10-05';myId='a';userStats={gold:100};window.db={};window.fbDoc=(db,...path)=>path.join('/');window.fbCollection=(db,...path)=>path.join('/');window.__rewardDb={};let scans=0,writes=0;
  for(const [id,minutes,ratings,swipes] of [['a',60,5,7],['b',30,6,5],['c',10,2,1],['zero',0,0,0]]){let activity=m.activity();for(let i=0;i<ratings;i++)activity=m.add(activity,'ratings',id,Date.parse(week+'T12:00:00+09:00'));for(let i=0;i<swipes;i++)activity=m.add(activity,'swipes',id,Date.parse(week+'T12:00:00+09:00'));__rewardDb['users/'+id]={userStats:{gold:100},learningActivityV1Json:JSON.stringify(activity),studyLedgerJson:JSON.stringify({version:1,epoch:'study-reset-2.62',offset:0,days:{[week]:{sources:{[id]:minutes*60000}}}})};}
  window.fbGetDocs=async ref=>{scans++;return {forEach:fn=>Object.entries(__rewardDb).filter(([key])=>key.startsWith('users/')).forEach(([key,data])=>fn({id:key.slice(6),data:()=>structuredClone(data)}))};};
  window.fbRunTransaction=async(db,fn)=>fn({get:async ref=>({exists:()=>Object.hasOwn(__rewardDb,ref),data:()=>structuredClone(__rewardDb[ref])}),set:(ref,fields,options)=>{__rewardDb[ref]=options?.merge?{...__rewardDb[ref],...structuredClone(fields)}:structuredClone(fields);writes++;}});
  await Promise.all([WeeklyRewards.settle(),WeeklyRewards.settle()]);const letters=WeeklyRewards.letters(),scanOnce=scans;for(const letter of letters)await WeeklyRewards.claim({...letter,amount:999999});const paid=m.balance(LearningWallet.read());for(const letter of letters)await WeeklyRewards.claim(letter);const twice=m.balance(LearningWallet.read());
  localStorage.removeItem('core_v4_weekly_mail_v1_a');await WeeklyRewards.settle();const reusedScans=scans;let future=false;try{await WeeklyRewards.claim({...letters[0],week:'2026-10-12'});}catch{future=true;}
  myId='b';userStats={gold:100};await WeeklyRewards.settle();for(const letter of WeeklyRewards.letters())await WeeklyRewards.claim(letter);const secondUser=m.balance(LearningWallet.read());
  return {letters:letters.map(l=>[l.metric,l.place,l.amount]),paid,twice,scanOnce,reusedScans,secondUser,future,writes,complete:__rewardDb['learningWeeklyResultsV1/'+week].complete,zeroIncluded:__rewardDb['learningWeeklyResultsV1/'+week].rows.some(r=>r.id==='zero')};
 });
 assert.equal(result.scanOnce,1);assert.equal(result.reusedScans,1);assert.equal(result.paid,25100);assert.equal(result.twice,25100);assert.equal(result.secondUser,20100);assert.equal(result.complete,true);assert.equal(result.zeroIncluded,false);assert.equal(result.future,true);assert.deepEqual(errors,[]);
 console.log('PASS '+type.name()+': Monday settlement; one shared user scan; reuse across accounts; per-metric awards; idempotent wallet claims; forged amounts/future weeks rejected; zero excluded');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
