const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const type=process.env.BROWSER==='webkit'?webkit:chromium,browser=await type.launch(type===chromium?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:{executablePath:process.env.WEBKIT_EXECUTABLE_PATH});try{
const docs=new Map(),versions=new Map(),listeners=new Map(),pages=[],errors=[];
for(const id of ['duel-a','duel-b','duel-c','duel-d'])docs.set('users/'+id,{playerName:id,avatar:'http://127.0.0.1:8000/aiglish.png',wordDuelRating:1500,lastActiveAt:Date.now(),protected:'learning-preserved',wordDuelSoloBest:777});
async function notify(path){for(const {page,key} of listeners.values())if(key===path)await page.evaluate(({path,value})=>{window.__duelListeners[path]?.({exists:()=>!!value,data:()=>structuredClone(value)});},{path,value:docs.get(path)});}
async function pageFor(id){const page=await browser.newPage({viewport:{width:393,height:852}});pages.push(page);page.on('pageerror',error=>errors.push(error.message));await page.clock.install();await page.route('https://**/*',r=>r.abort());await page.addInitScript(()=>localStorage.setItem('aiglish_sound_settings',JSON.stringify({enabled:false})));
await page.exposeFunction('__duelRead',path=>({value:docs.get(path)||null,version:versions.get(path)||0}));
await page.exposeFunction('__duelCommit',async({reads,writes})=>{for(const [path,version] of Object.entries(reads))if((versions.get(path)||0)!==version)return false;for(const write of writes){docs.set(write.path,write.merge?{...docs.get(write.path),...write.value}:write.value);versions.set(write.path,(versions.get(write.path)||0)+1);}for(const write of writes)await notify(write.path);return true;});
await page.exposeFunction('__duelSubscribe',async path=>{listeners.set(id,{page,key:path});return docs.get(path)||null;});await page.exposeFunction('__duelUnsubscribe',()=>listeners.delete(id));await page.exposeFunction('__duelList',()=>Array.from(docs.entries()).filter(([path])=>/^users\/[^/]+$/.test(path)).map(([path,value])=>({id:path.split('/')[1],value})));
await page.goto('http://127.0.0.1:8000');await page.waitForFunction(()=>window.WordDuel);await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.waitForFunction(()=>window.__learningBootReady===true);
await page.evaluate(id=>{myId=id;myName=id;textbooksPool=[{id:'duel-book',name:'対戦テスト'}];currentTextbook='duel-book';localStorage.setItem('core_v4_cache_duel-book',JSON.stringify(Array.from({length:20},(_,i)=>({num:i,word:'word'+i,meaning:'意味'+i}))));window.db={};window.fbDoc=(_, ...parts)=>parts.join('/');window.fbCollection=(_, ...parts)=>parts.join('/');window.fbServerTimestamp=()=>Date.now();window.fbGetDoc=async path=>{const {value}=await __duelRead(path);return {exists:()=>!!value,data:()=>structuredClone(value)};};window.RankingQuery.fetch=async()=> (await __duelList()).map(doc=>({id:doc.id,data:doc.value}));window.fbGetDocs=async()=>({docs:(await __duelList()).map(doc=>({id:doc.id,data:()=>doc.value}))});window.fbRunTransaction=async(_,fn)=>{for(let attempt=0;attempt<20;attempt++){const reads={},writes=[];const result=await fn({get:async path=>{const {value,version}=await __duelRead(path);reads[path]=version;return {exists:()=>!!value,data:()=>structuredClone(value)};},set:(path,value,options)=>writes.push({path,value,merge:options?.merge===true||!!options?.mergeFields})});if(await __duelCommit({reads,writes}))return result;}throw Error('transaction conflict');};window.__duelListeners={};window.fbOnSnapshot=(path,callback)=>{__duelListeners[path]=callback;__duelSubscribe(path).then(value=>callback({exists:()=>!!value,data:()=>value}));return ()=>{delete __duelListeners[path];__duelUnsubscribe();};};},id);return page;}
const clients=[];for(const id of ['duel-a','duel-b','duel-c','duel-d'])clients.push(await pageFor(id));const [a,b,c,d]=clients;
for(const [i,page]of clients.entries())await page.evaluate(i=>{StudyTime.mergeCloud({version:1,epoch:'study-reset-2.62',days:{},offset:3600000});localStorage.setItem('core_v4_user_avatar_'+myId,'http://127.0.0.1:8000/aiglish.png');localStorage.setItem('core_v4_profile_customization_'+myId,JSON.stringify({frame:i?'stone':'wood'}));},i);
async function lobby(page){await page.locator('#nav-community').click();await page.locator('.duel-entry').click();}
async function answer(page,correct=true){const prompt=await page.locator('.duel-prompt').textContent(),meaning='意味'+prompt.slice(4),texts=await page.locator('.duel-options button').allTextContents(),right=texts.includes(meaning)?texts.indexOf(meaning):9;await page.locator('.duel-options button').nth(correct?right:(right+1)%10).click();if(correct){assert.equal(await page.locator('.duel-options button.is-selected').count(),1);assert.equal(await page.locator('.duel-options button:disabled').count(),10);await page.clock.fastForward(200);}}
async function join(page,code){await lobby(page);await page.getByRole('textbox',{name:'部屋番号'}).fill(code);await page.getByRole('button',{name:'参加',exact:true}).click();}
await lobby(a);await a.getByLabel('プレイ時間').selectOption('120000');await a.getByRole('button',{name:'一人プレイ',exact:true}).click();await a.locator('.duel-options button').first().waitFor();assert.equal(await a.locator('.duel-clock').textContent(),'120');assert.equal(await a.locator('.duel-player').count(),1);assert.equal(await a.locator('.duel-content').textContent().then(value=>value.includes('自己ベスト')),false);await answer(a);await answer(a);await answer(a);await answer(a,false);assert.equal(await a.locator('.duel-correction').isVisible(),true);await a.getByRole('button',{name:'次の問題',exact:true}).click();await answer(a);await a.clock.fastForward(61000);assert.equal(await a.locator('.duel-solo-result').count(),0);await a.clock.fastForward(61000);await a.locator('.duel-solo-result').waitFor();assert.equal(await a.locator('.duel-solo-result strong').textContent(),'380点');assert.equal(docs.get('users/duel-a').wordDuelSoloBest,777);assert.equal(await a.evaluate(()=>localStorage.getItem('core_v4_word_duel_solo_duel-a')),null);await a.getByRole('button',{name:'閉じる',exact:true}).click();
for(const page of clients)await page.clock.setSystemTime(Date.now());await lobby(a);await a.getByLabel('プレイ時間').selectOption('30000');await a.getByLabel('対戦人数').selectOption('4');await a.getByRole('button',{name:'部屋を作る',exact:true}).click();await a.locator('.duel-wait strong').waitFor();const code=await a.locator('.duel-wait strong').textContent();await join(b,code);assert.equal(await a.locator('.duel-options').count(),0);await join(c,code);assert.match(await a.locator('[data-wait-count]').textContent(),/3 \/ 4人/);
// A waiting guest frees the seat using a full replacement of the players map.
await c.getByRole('button',{name:'フレンドに戻る'}).click();await a.waitForFunction(code=>Object.keys(window.__duelListeners).includes('wordDuelRooms/'+code),code);for(let i=0;i<100&&Object.keys(docs.get('wordDuelRooms/'+code).players).length!==2;i++)await a.waitForTimeout(10);assert.equal(Object.keys(docs.get('wordDuelRooms/'+code).players).length,2);await join(c,code);await join(d,code);
for(const page of clients){await page.locator('.duel-options button').first().waitFor();await page.clock.fastForward(4000);assert.equal(await page.locator('.duel-player').count(),4);await page.locator('.duel-player-avatar img').last().waitFor();}
assert.equal(new Set(await Promise.all(clients.map(page=>page.locator('.duel-prompt').textContent()))).size,1);
await a.setViewportSize({width:320,height:668});assert.equal(await a.locator('.word-duel-screen').evaluate(node=>node.scrollWidth<=node.clientWidth),true);await a.screenshot({path:'/tmp/battle-four-'+type.name()+'.png'});await a.setViewportSize({width:393,height:852});
for(let i=0;i<3;i++)await answer(a);for(let i=0;i<2;i++)await answer(b);await answer(c);await answer(d,false);await a.waitForFunction(()=>Array.from(document.querySelectorAll('.duel-player strong')).some(node=>node.textContent==='-50'));
for(const page of clients)await page.clock.fastForward(31000);for(const page of clients)await page.locator('.duel-results').waitFor();
const result=docs.get('wordDuelRooms/'+code).result;assert.deepEqual(Object.values(result.deltas),[30,15,-15,-30]);assert.deepEqual(Object.values(result.scores),[330,210,100,-50]);for(const [i,id]of ['duel-a','duel-b','duel-c','duel-d'].entries()){assert.equal(result.places[id],i+1);assert.equal(docs.get('users/'+id).wordDuelRating,1500+[30,15,-15,-30][i]);assert.equal(docs.get('users/'+id).protected,'learning-preserved');assert.equal(docs.get('users/'+id).wordDuelSoloBest,777);}
const games=docs.get('users/duel-a').wordDuelGames;await a.evaluate(code=>WordDuel.settle(code),code);assert.equal(docs.get('users/duel-a').wordDuelGames,games);assert.ok(Object.values(JSON.parse(docs.get('users/duel-d/vocabProgress/duel-book').wordsJson)).some(word=>word.status==='bad'));for(const page of clients)await page.getByRole('button',{name:'閉じる',exact:true}).click();
// Three players: a tie shares first/second, and the lower score loses 30.
for(const page of clients)await page.clock.setSystemTime(Date.now());await lobby(a);await a.getByLabel('プレイ時間').selectOption('30000');await a.getByLabel('対戦人数').selectOption('3');await a.getByRole('button',{name:'部屋を作る',exact:true}).click();await a.locator('.duel-wait strong').waitFor();const triple=await a.locator('.duel-wait strong').textContent();await join(b,triple);await join(c,triple);await join(d,triple);assert.match(await d.locator('.duel-status').textContent(),/参加できません/);await d.getByRole('button',{name:'フレンドに戻る'}).click();for(const page of [a,b,c]){await page.locator('.duel-options button').first().waitFor();await page.clock.fastForward(4000);}await answer(a);await answer(b);await answer(c,false);for(const page of [a,b,c])await page.clock.fastForward(31000);for(const page of [a,b,c])await page.locator('.duel-results').waitFor();assert.deepEqual(Object.values(docs.get('wordDuelRooms/'+triple).result.deltas),[15,15,-30]);for(const page of [a,b,c])await page.getByRole('button',{name:'閉じる',exact:true}).click();
// Two players: scoreless draw is zero; an abandoned player loses 30 after finish.
for(const page of [a,b])await page.clock.setSystemTime(Date.now());await lobby(a);await a.getByLabel('プレイ時間').selectOption('30000');await a.getByRole('button',{name:'部屋を作る',exact:true}).click();await a.locator('.duel-wait strong').waitFor();const pair=await a.locator('.duel-wait strong').textContent();await join(b,pair);for(const page of [a,b]){await page.locator('.duel-options button').first().waitFor();await page.clock.fastForward(4000);}await b.getByRole('button',{name:'終了する',exact:true}).click();await a.clock.fastForward(31000);await a.locator('.duel-results').waitFor();await b.locator('.duel-results').waitFor();assert.equal(docs.get('wordDuelRooms/'+pair).result.deltas['duel-a'],30);assert.equal(docs.get('wordDuelRooms/'+pair).result.deltas['duel-b'],-30);for(const page of [a,b])await page.getByRole('button',{name:'閉じる',exact:true}).click();
await a.locator('#nav-titles').click();await a.getByRole('button',{name:'対戦レート',exact:true}).click();await a.locator('[data-podium-metric=rating] .place-1 strong').waitFor();assert.equal(await a.locator('[data-podium-metric=solo]').count(),0);assert.equal(await a.locator('.ranking-mini-panel').count(),1);await a.locator('.rating-roster summary').click();assert.equal(await a.locator('.rating-roster li').count(),1);await a.screenshot({path:'/tmp/rate-expanded-'+type.name()+'.png'});assert.deepEqual(errors,[]);console.log('PASS '+type.name()+': timed solo without best writes, 4-player live scores/place changes, 3-player tie/overfill rejection, 2-player forfeit, waiting exit/rejoin, atomic idempotent settlement, understanding preservation and expandable rate list');
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exit(1)});
