const test=require('node:test'),assert=require('node:assert/strict'),m=require('../word-duel-model.js');
const words=m.pool(Array.from({length:20},(_,i)=>({word:'word'+i,meaning:'意味'+i})));
test('ten options are deterministic, unique and sometimes omit the answer',()=>{let absent=0;for(let i=0;i<100;i++){const q=m.question(words,123,i);assert.deepEqual(q,m.question(words,123,i));assert.equal(q.options.length,10);assert.equal(new Set(q.options).size,10);if(q.correct===9)absent++;}assert.ok(absent>0&&absent<100);});
test('combo is additive 10 percent and resets after a minus-50 miss',()=>{const right=i=>m.question(words,1,i).correct;const log=[{choice:right(0),at:0},{choice:right(1),at:100},{choice:right(2),at:200},{choice:(right(3)+1)%10,at:300},{choice:right(4),at:400}];assert.deepEqual(m.score(words,1,log),{total:380,combo:1});assert.throws(()=>m.score(words,1,[{choice:0,at:60000}]));assert.throws(()=>m.score(words,1,[{choice:10,at:0}]));});
test('Elo starts at 1500; wins, losses, draws and unequal strength use K32',()=>{assert.equal(m.rating(undefined),1500);assert.deepEqual(m.elo(undefined,undefined,1),[1516,1484]);assert.deepEqual(m.elo(1500,1500,.5),[1500,1500]);assert.deepEqual(m.elo(1500,1500,0),[1484,1516]);assert.deepEqual(m.elo(1700,1500,1),[1708,1492]);});
test('forfeits override score and two abandoned players cancel',()=>{const room={host:'a',guest:'b',pool:words,seed:1,players:{a:{answers:[],abandoned:true},b:{answers:[],abandoned:false}}};assert.equal(m.outcome(room),0);room.players.b.abandoned=true;assert.equal(m.outcome(room),null);});
test('malformed and incompatible room snapshots are rejected before they reach the UI',()=>{const room={version:3,book:'test-book',status:'playing',host:'a',guest:'b',pool:words.map((word,i)=>({...word,ref:{num:String(i),mid:i+'-0',sig:i+'::'+word.prompt+'::'+word.meaning,count:1}})),seed:1,players:{a:{answers:[]},b:{answers:[]}}};assert.equal(m.validRoom(room),true);assert.equal(m.validRoom({...room,version:1}),false);assert.equal(m.validRoom({...room,pool:[]}),false);assert.equal(m.validRoom({...room,players:{a:{answers:[{choice:11,at:0}]},b:{answers:[]}}}),false);assert.equal(m.validRoom({...room,status:'finished'}),false);});
test('prompts cover every word before repeating and distractors rotate instead of repeating a subset',()=>{const full=m.pool(Array.from({length:120},(_,i)=>({word:'word'+i,meaning:'意味'+i})));const questions=full.map((_,i)=>m.question(full,5566,i));assert.equal(new Set(questions.map(q=>q.prompt)).size,120);const options=questions.slice(0,12).flatMap(q=>q.options.slice(0,9));assert.ok(new Set(options).size>90);for(let i=1;i<12;i++){const previous=new Set(questions[i-1].options.slice(0,9));assert.ok(questions[i].options.slice(0,9).filter(text=>previous.has(text)).length<=3);}});
test('sampling includes the entire book, stays bounded and is deterministic for each match',()=>{const source=Array.from({length:3000},(_,i)=>({word:'word'+i,meaning:'意味'+i})),pool=m.pool(source,42);assert.equal(pool.length,120);assert.deepEqual(pool,m.pool(source,42));assert.ok(pool.some(item=>Number(item.prompt.slice(4))>2000));assert.equal(new Set(pool.map(item=>item.meaning)).size,120);});
test('the correct meaning is available when none of the nine choices is correct',()=>{let q;for(let i=0;i<100;i++){q=m.question(words,123,i);if(q.correct===9)break;}assert.equal(q.correct,9);assert.equal(q.options.slice(0,9).includes(q.meaning),false);assert.ok(q.meaning.startsWith('意味'));assert.equal(m.bestScore(-50),-50);assert.equal(m.bestScore(0),0);assert.equal(m.bestScore(9999999),null);assert.equal(m.bestScore(undefined),null);});

test('stable word references survive sampling and shuffled questions',()=>{const source=Array.from({length:300},(_,i)=>({word:'w'+i,meaning:'m'+i,duelRef:{num:String(i),mid:i+'-0',sig:'sig'+i,count:2}})),pool=m.pool(source,42);for(let i=0;i<120;i++){const q=m.question(pool,42,i);assert.equal(q.ref.sig,'sig'+q.prompt.slice(1));assert.equal(q.ref.count,2);}});
