const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const type=process.env.BROWSER==='webkit'?webkit:chromium,browser=await type.launch(type===chromium?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:{executablePath:process.env.WEBKIT_EXECUTABLE_PATH});try{
const docs=new Map(),versions=new Map(),listeners=new Map(),pages=[],errors=[];
for(const id of ['duel-a','duel-b'])docs.set('users/'+id,{playerName:id,avatar:'http://127.0.0.1:8000/aiglish.png',wordDuelRating:1500,lastActiveAt:Date.now(),protected:'learning-preserved'});
async function notify(path){for(const {page,key} of listeners.values())if(key===path)await page.evaluate(({path,value})=>{window.__duelListeners[path]?.({exists:()=>!!value,data:()=>structuredClone(value)});},{path,value:docs.get(path)});}
async function pageFor(id){const page=await browser.newPage({viewport:{width:393,height:852}});pages.push(page);page.on('pageerror',error=>errors.push(error.message));await page.clock.install();await page.route('https://**/*',r=>r.abort());await page.addInitScript(()=>localStorage.setItem('aiglish_sound_settings',JSON.stringify({enabled:false})));
await page.exposeFunction('__duelRead',path=>({value:docs.get(path)||null,version:versions.get(path)||0}));
await page.exposeFunction('__duelCommit',async({reads,writes})=>{for(const [path,version] of Object.entries(reads))if((versions.get(path)||0)!==version)return false;for(const write of writes){docs.set(write.path,write.merge?{...docs.get(write.path),...write.value}:write.value);versions.set(write.path,(versions.get(write.path)||0)+1);}for(const write of writes)await notify(write.path);return true;});
await page.exposeFunction('__duelSubscribe',async path=>{listeners.set(id,{page,key:path});return docs.get(path)||null;});await page.exposeFunction('__duelUnsubscribe',()=>listeners.delete(id));await page.exposeFunction('__duelList',()=>Array.from(docs.entries()).filter(([path])=>/^users\/[^/]+$/.test(path)).map(([path,value])=>({id:path.split('/')[1],value})));
await page.goto('http://127.0.0.1:8000');await page.waitForFunction(()=>window.WordDuel);await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.waitForFunction(()=>window.__learningBootReady===true);
await page.evaluate(id=>{myId=id;myName=id;textbooksPool=[{id:'duel-book',name:'対戦テスト'}];currentTextbook='duel-book';localStorage.setItem('core_v4_cache_duel-book',JSON.stringify(Array.from({length:20},(_,i)=>({num:i,word:'word'+i,meaning:'意味'+i}))));window.db={};window.fbDoc=(_, ...parts)=>parts.join('/');window.fbCollection=(_, ...parts)=>parts.join('/');window.fbServerTimestamp=()=>Date.now();window.fbGetDoc=async path=>{const {value}=await __duelRead(path);return {exists:()=>!!value,data:()=>structuredClone(value)};};window.RankingQuery.fetch=async()=> (await __duelList()).map(doc=>({id:doc.id,data:doc.value}));window.fbGetDocs=async()=>({docs:(await __duelList()).map(doc=>({id:doc.id,data:()=>doc.value}))});window.fbRunTransaction=async(_,fn)=>{for(let attempt=0;attempt<20;attempt++){const reads={},writes=[];const result=await fn({get:async path=>{const {value,version}=await __duelRead(path);reads[path]=version;return {exists:()=>!!value,data:()=>structuredClone(value)};},set:(path,value,options)=>writes.push({path,value,merge:options?.merge===true})});if(await __duelCommit({reads,writes}))return result;}throw Error('transaction conflict');};window.__duelListeners={};window.fbOnSnapshot=(path,callback)=>{__duelListeners[path]=callback;__duelSubscribe(path).then(value=>callback({exists:()=>!!value,data:()=>value}));return ()=>{delete __duelListeners[path];__duelUnsubscribe();};};},id);return page;}
const a=await pageFor('duel-a'),b=await pageFor('duel-b');
await a.evaluate(()=>{StudyTime.mergeCloud({version:1,epoch:'study-reset-2.62',days:{},offset:3600000});localStorage.setItem('core_v4_user_avatar_duel-a','http://127.0.0.1:8000/aiglish.png');localStorage.setItem('core_v4_profile_customization_duel-a',JSON.stringify({frame:'wood'}));});await b.evaluate(()=>{StudyTime.mergeCloud({version:1,epoch:'study-reset-2.62',days:{},offset:3600000});localStorage.setItem('core_v4_user_avatar_duel-b','http://127.0.0.1:8000/aiglish.png');localStorage.setItem('core_v4_profile_customization_duel-b',JSON.stringify({frame:'stone'}));});
await a.locator('#nav-community').click();await a.locator('.duel-entry').click();assert.equal(await a.locator('.word-duel-screen').evaluate(node=>node.tagName),'SECTION');assert.deepEqual(await a.locator('.word-duel-screen').boundingBox(),{x:0,y:0,width:393,height:852});await a.getByRole('button',{name:'一人プレイ',exact:true}).click();await a.locator('.duel-options button').first().waitFor();assert.equal(await a.locator('.duel-options button').count(),10);assert.equal(await a.locator('[data-self-avatar] img').count(),1);assert.equal(await a.locator('[data-self-avatar] .frame-wood').count(),1);
await a.setViewportSize({width:320,height:668});assert.equal(await a.locator('.word-duel-screen').evaluate(node=>node.scrollWidth<=node.clientWidth),true);await a.setViewportSize({width:393,height:852});await a.screenshot({path:'/tmp/word-duel-fullscreen.png'});
async function answer(page,correct=true){const prompt=await page.locator('.duel-prompt').textContent(),meaning='意味'+prompt.slice(4),texts=await page.locator('.duel-options button').allTextContents(),right=texts.includes(meaning)?texts.indexOf(meaning):9;await page.locator('.duel-options button').nth(correct?right:(right+1)%10).click();if(correct){assert.equal(await page.locator('.duel-options button.is-selected').count(),1);assert.equal(await page.locator('.duel-options button:disabled').count(),10);await page.clock.fastForward(200);}}
await answer(a);await answer(a);await answer(a);assert.equal(await a.locator('[data-duel-score]').textContent(),'330');const missedPrompt=await a.locator('.duel-prompt').textContent();await answer(a,false);assert.equal(await a.locator('[data-duel-score]').textContent(),'280');assert.equal(await a.locator('.duel-correction strong').textContent(),'意味'+missedPrompt.slice(4));assert.equal(await a.locator('.duel-options button.is-correct').count(),1);await a.clock.fastForward(1200);assert.equal(await a.locator('.duel-options button:disabled').count(),10);assert.equal(await a.locator('.duel-prompt').textContent(),missedPrompt);await a.screenshot({path:'/tmp/word-duel-correction.png'});await a.getByRole('button',{name:'次の問題',exact:true}).click();assert.notEqual(await a.locator('.duel-prompt').textContent(),missedPrompt);await answer(a);assert.equal(await a.locator('[data-duel-score]').textContent(),'380');await a.clock.fastForward(61000);await a.waitForFunction(()=>document.querySelector('.duel-status')?.textContent.includes('保存・同期しました'));assert.equal(docs.get('users/duel-a').wordDuelSoloBest,380);assert.equal(docs.get('users/duel-a').wordDuelRating,1500);assert.ok(Object.keys(JSON.parse(docs.get('users/duel-a/vocabProgress/duel-book').wordsJson)).length>=5);assert.ok(Object.values(JSON.parse(docs.get('users/duel-a/vocabProgress/duel-book').wordsJson)).some(word=>word.status==='bad'));await a.getByRole('button',{name:'閉じる',exact:true}).click();assert.equal(await a.locator('.word-duel-screen').count(),0);assert.equal(await a.locator('#nav-community').evaluate(node=>node.closest('[inert]')),null);
// Quitting early is not a personal-best record; a weaker completed run cannot replace the best.
await a.locator('.duel-entry').click();await a.getByRole('button',{name:'一人プレイ',exact:true}).click();await answer(a);await a.getByRole('button',{name:'終了する',exact:true}).click();assert.equal(docs.get('users/duel-a').wordDuelSoloBest,380);await a.getByRole('button',{name:'閉じる',exact:true}).click();await a.locator('.duel-entry').click();await a.getByRole('button',{name:'一人プレイ',exact:true}).click();await a.clock.fastForward(61000);assert.equal(docs.get('users/duel-a').wordDuelSoloBest,380);assert.equal(await a.evaluate(()=>WordDuelSolo.best()),380);await a.getByRole('button',{name:'閉じる',exact:true}).click();
await a.clock.setSystemTime(Date.now());await b.clock.setSystemTime(Date.now());await a.locator('.duel-entry').click();await a.getByRole('button',{name:'部屋を作る',exact:true}).click();await a.locator('.duel-wait strong').waitFor();const code=await a.locator('.duel-wait strong').textContent();await b.locator('#nav-community').click();await b.locator('.duel-entry').click();await b.getByRole('textbox',{name:'部屋番号'}).fill(code);await b.getByRole('button',{name:'参加',exact:true}).click();await a.locator('.duel-options button').first().waitFor();await b.locator('.duel-options button').first().waitFor();
const ratingA=1500,ratingB=1500,code2=code;await a.clock.fastForward(4000);await b.clock.fastForward(4000);await a.locator('[data-opponent-avatar] img').waitFor();await b.locator('[data-opponent-avatar] img').waitFor();assert.equal(await a.locator('[data-opponent-avatar] .frame-stone').count(),1);assert.equal(await b.locator('[data-opponent-avatar] .frame-wood').count(),1);assert.equal(docs.get('wordDuelRooms/'+code).players['duel-a'].avatar,undefined);assert.equal(await a.locator('.duel-prompt').textContent(),await b.locator('.duel-prompt').textContent());await answer(a);await answer(b,false);await a.waitForFunction(()=>document.querySelector('[data-opponent-score]')?.textContent==='-50');await b.waitForFunction(()=>document.querySelector('[data-opponent-score]')?.textContent==='100');await a.clock.fastForward(60000);await b.clock.fastForward(60000);await a.locator('.duel-result').waitFor();await b.locator('.duel-result').waitFor();assert.equal(await a.locator('.duel-result').textContent(),'勝利');assert.equal(await b.locator('.duel-result').textContent(),'敗北');const expected=await a.evaluate(({a,b})=>WordDuelModel.elo(a,b,1),{a:ratingA,b:ratingB});assert.equal(docs.get('users/duel-a').wordDuelRating,expected[0]);assert.equal(docs.get('users/duel-b').wordDuelRating,expected[1]);assert.ok(Object.values(JSON.parse(docs.get('users/duel-b/vocabProgress/duel-book').wordsJson)).some(word=>word.status==='bad'));const games=docs.get('users/duel-a').wordDuelGames;await a.evaluate(code=>WordDuel.settle(code),code2);assert.equal(docs.get('users/duel-a').wordDuelGames,games);assert.equal(docs.get('users/duel-a').protected,'learning-preserved');
await a.getByRole('button',{name:'閉じる',exact:true}).click();await a.locator('#nav-titles').click();await a.getByRole('button',{name:'単語バトル',exact:true}).click();await a.locator('[data-podium-metric=rating]').waitFor();assert.match(await a.locator('#headerDuelRating').textContent(),new RegExp(String(expected[0])));await a.locator('[data-podium-metric=solo] .place-1 strong').waitFor();assert.equal(await a.locator('[data-podium-metric=solo] .place-1 strong').textContent(),'380点');assert.equal(await a.locator('[data-podium-metric=rating]').count(),1);assert.equal(await a.locator('.ranking-mini-panel').count(),2);assert.equal(docs.get('users/duel-a').protected,'learning-preserved');await a.waitForFunction(()=>Number(getComputedStyle(document.querySelector('[data-podium-metric=solo] .place-1')).opacity)>.99,{},{polling:50});await a.screenshot({path:'/tmp/word-duel-solo-ranking.png'});assert.deepEqual(errors,[]);console.log('PASS '+type.name()+': full screen 393/320px, framed player icons, correction with answer lock, completed solo best sync/ranking, lower-score and early-exit preservation; two-client rooms/common questions/live scores/Elo/idempotence');
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exit(1)});
