const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
 try{
 const page=await browser.newPage({viewport:{width:390,height:844}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',error=>errors.push(error.message));await page.route('https://**/*',route=>route.abort());
 await page.addInitScript(()=>{localStorage.setItem('b3_tutorial_done','1');if(!localStorage.getItem('vv4_works_GUEST-000'))localStorage.setItem('vv4_works_GUEST-000',JSON.stringify([{id:'legacy',name:'以前の数学',from:1,to:2,entries:{1:{q:'昔の問題',ans:'答え',memo:'計算ミス',status:'bad',history:['bad'],lastReview:Date.now()-7*86400000,nextReview:Date.now()-86400000,subs:[{sub:1,q:'昔の小問',status:'ok',history:['ok']}]}},nonums:[]}]));});
 await page.goto('http://127.0.0.1:8000',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.WorkbookModel);
 await page.getByRole('button',{name:'ゲストとしてテストプレイ'}).click();await page.locator('#nav-vocab').click();
 assert.equal(await page.locator('#vocabLibraryWorks .textbook-list-arrow').count(),0);assert.equal(await page.locator('#vocabLibraryWorks .vocab-library-flash-button').count(),0);
 await page.getByRole('button',{name:'以前の数学の復習 1件',exact:true}).click();await page.getByText('昔の問題',{exact:true}).waitFor();assert.equal(await page.locator('#workbookUnitList .word-row-container').count(),1);await page.getByRole('button',{name:'以前の数学 単語帳一覧に戻る'}).click();
 await page.getByRole('button',{name:'＋ ワークを作る',exact:true}).click();assert.equal(await page.locator('dialog.library-editor-dialog').count(),1);
 await page.locator('#workbookName').fill('ページで復習');await page.locator('#workbookUnit').selectOption('page');await page.locator('#workbookFrom').fill('12');await page.locator('#workbookTo').fill('14');await page.locator('#workbookReviewMode').selectOption('interval');await page.locator('#workbookReviewDays').fill('5');
 await page.locator('#workbookCover').setInputFiles('Header.png');await page.waitForFunction(()=>document.querySelector('#workbookCoverPreview').src.startsWith('data:image/jpeg'));
 await page.locator('dialog summary').click();await page.locator('#workbookImport').fill('12:2x+1=5:x=2:一次方程式\n13:::');
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async value=>window.__workbookPrompt=value}}));await page.locator('#workbookCopyPrompt').click();assert.match(await page.evaluate(()=>window.__workbookPrompt),/ページ番号/);
 await page.screenshot({path:'/tmp/workbook-editor.png'});
 await page.getByRole('button',{name:'ワークを作る',exact:true}).click();assert.equal(await page.locator('dialog').count(),0);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'/tmp/workbook-library.png'});
 await page.locator('#vocabLibraryWorks .textbook-list-item').filter({hasText:'ページで復習'}).click();assert.equal(await page.locator('#workbookUnitList .word-row-container').count(),3);await page.getByText('ページ範囲:',{exact:true}).waitFor();
 await page.getByRole('button',{name:'AIで解説を見る',exact:true}).click();await page.getByText('メニューの「Gemini AI APIキー」にキーを設定してください。',{exact:true}).waitFor();await page.getByRole('button',{name:'閉じる',exact:true}).click();await page.getByRole('button',{name:'p.12の理解度 ○',exact:true}).click();
 let data=await page.evaluate(()=>JSON.parse(localStorage.getItem('vv4_works_GUEST-000')).find(w=>w.name==='ページで復習'));assert.equal(data.units.find(u=>u.num===12).status,'ok');assert.equal(data.units.find(u=>u.num===12).nextReview,await page.evaluate(()=>WorkbookModel.addDays(Date.now(),5)));
 await page.getByRole('button',{name:'まとめて記録・復習設定'}).click();await page.locator('#workbookBatchFrom').fill('13');await page.locator('#workbookBatchTo').fill('14');await page.locator('#workbookBatchStatus').selectOption('bad');await page.locator('#workbookBatchChangeRule').check();await page.locator('#workbookBatchReviewMode').selectOption('none');await page.getByRole('button',{name:'まとめて保存'}).click();
 data=await page.evaluate(()=>JSON.parse(localStorage.getItem('vv4_works_GUEST-000')).find(w=>w.name==='ページで復習'));assert.equal(data.units.filter(u=>u.status==='bad').length,2);assert.equal(data.units.find(u=>u.num===14).nextReview,0);
 await page.locator('[data-unit-id="12"] .workbook-postpone').click();await page.locator('#workbookPostpone').selectOption('3');await page.getByRole('button',{name:'延期する',exact:true}).click();
 data=await page.evaluate(()=>JSON.parse(localStorage.getItem('vv4_works_GUEST-000')).find(w=>w.name==='ページで復習'));assert.equal(data.units.find(u=>u.num===12).nextReview,await page.evaluate(()=>WorkbookModel.addDays(Date.now(),3)));assert.equal(data.review.days,5);
 // Set a date on an unreviewed item; it must appear in today's review count.
 await page.getByRole('button',{name:'p.14を編集',exact:true}).click();await page.locator('#workbookUseDefault').uncheck();await page.locator('#workbookUnitReviewMode').selectOption('date');await page.locator('#workbookUnitReviewDate').fill(await page.evaluate(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}));await page.locator('#workbookNote').fill('符号のミス');await page.getByRole('button',{name:'変更を保存',exact:true}).click();
 await page.screenshot({path:'/tmp/workbook-study.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.WorkbookModel);await page.locator('#nav-vocab').click();await page.getByRole('button',{name:'ページで復習の復習 1件',exact:true}).waitFor();
 await page.locator('#workbookToday').click();await page.getByText('ページで復習 · p.14',{exact:true}).waitFor();await page.getByRole('button',{name:'閉じる',exact:true}).click();
 // Problem-number creation uses the same dialog, without review scheduling.
 await page.getByRole('button',{name:'＋ ワークを作る',exact:true}).click();await page.locator('#workbookName').fill('番号で復習');await page.locator('#workbookUnit').selectOption('problem');await page.getByText('問題番号範囲',{exact:true}).waitFor();await page.locator('#workbookTo').fill('2');await page.locator('#workbookReviewMode').selectOption('none');await page.getByRole('button',{name:'ワークを作る',exact:true}).click();
 // Cloud catalogue and writes are mocks, never production writes.
 await page.evaluate(()=>{window.__gcLoginShown=true;myId='work-test';window.db={};window.__workWrites=[];window.fbDoc=(_, ...path)=>path.join('/');window.fbCollection=window.fbDoc;window.fbSetDoc=async(...args)=>window.__workWrites.push(args);window.fbDeleteDoc=async(...args)=>window.__workWrites.push(['delete',...args]);window.fbGetDocs=async()=>({forEach:cb=>cb({id:'public-example',data:()=>({masterJson:JSON.stringify({id:'public-example',name:'公開数学',unitKind:'page',from:10,to:10,units:[{id:'10',num:10,q:'問題',ans:'答え',memo:'補足',note:'private note',status:'bad',history:['bad'],nextReview:1}]})})})});window.showVocabLibrarySelection();});
 await page.getByRole('button',{name:'みんなのワーク',exact:true}).click();await page.getByRole('button',{name:'自分用に追加',exact:true}).click();await page.getByRole('button',{name:'閉じる',exact:true}).click();
 data=await page.evaluate(()=>JSON.parse(localStorage.getItem('vv4_works_work-test'))[0]);assert.equal(data.units[0].status,'none');assert.equal(data.units[0].note,'');assert.equal(data.units[0].nextReview,0);
 await page.getByRole('button',{name:'公開数学の管理',exact:true}).click();await page.getByRole('button',{name:'名前・表紙・復習設定 / 問題を追加',exact:true}).click();await page.locator('#workbookVisibility').selectOption('public');await page.getByRole('button',{name:'変更を保存',exact:true}).click();
 const payload=await page.evaluate(()=>window.__workWrites[0][1]);assert.equal(payload.ownerId,'work-test');assert.equal(JSON.parse(payload.masterJson).units[0].status,undefined);assert.equal(JSON.parse(payload.masterJson).review,undefined);
 await page.getByRole('button',{name:'公開数学の管理',exact:true}).click();await page.getByRole('button',{name:'ワークを削除',exact:true}).click();await page.getByRole('button',{name:'削除する',exact:true}).click();assert.equal(await page.getByRole('button',{name:'公開数学の管理',exact:true}).count(),0);assert.equal(await page.evaluate(()=>window.__workWrites[1][0]),'delete');
 assert.deepEqual(errors,[]);console.log('PASS: shared library UI, legacy migration, page/problem creation, import, photo, prompt, interval, batch recording, no review, postponement, custom date, restart, today list and private public copies');
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exit(1);});
